Makefile
bin/check

This extends our pre-install check (formerly just `which docker`) to also check
for an inability to talk to the docker server and output a more informative
error including boot2docker-specific instructions in that case.

Add a more comprehensive pre-install check

---

lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

@codeclimate/review @brynary This PR adds additional directories to be autoexcluded in `codeclimate init`.
This PR adds `db`, `config`, `features`, `spec`, `test`.
Adds two additional directories to test case in spec.

Abh extend autoexclude paths

---

Gemfile.lock
lib/cc/analyzer/filesystem.rb
lib/cc/cli/engines/engine_command.rb
lib/cc/cli/init.rb
spec/cc/analyzer/filesystem_spec.rb
spec/cc/cli/command_spec.rb

@codeclimate/review This PR updates the `init` and `update_yaml` commands to set the `.codeclimate.yml` file `uid` and `gid` to match that of the root directory. 
After some experimenting, I found stubbing the `File.chown()` call in testing somewhat unfeasible. Meaningful tests seemed to require execution with `sudo` prefixed to `bundle exec rake`, which we probably would prefer to avoid. Happy to hear other thoughts though.

patch writes to .codeclimate.yml file to always set the file owner as the root directory user

---

.codeclimate.yml
Gemfile.lock
lib/cc/analyzer/filesystem.rb
spec/cc/analyzer/filesystem_spec.rb

* Existing `file_paths` method was unused... Removed it.
* Renamed `all` as `file_paths` and made it only emit files (not dirs)
* Shell out to `find` instead of using `Dir.glob`... Fixes issue where CTRL+C won't kill an in-process init.
* Exclude `config` and `spec` from analysis
/c @codeclimate/review

Use find to walk directories in init

---

lib/cc/cli/analyze.rb

Adds `-dev` flag to analyze command. Allows for easy local testing with CLI during engine hacking. Steps to test your in-progress engine locally with the CLI now become:
1. Add the engine name to the `.codeclimate.yml` file in the project you wish to analyze
2. Run `codeclimate analyze -dev` in that directory
The CLI will look for `codecliamte/codeclimate-YOUR_ENGINE_NAME:latest` in the Docker registry.

Add -dev flag to analyze command

---

config/engines.yml
lib/cc/analyzer/engine.rb
lib/cc/cli/analyze.rb
lib/cc/cli/engines/install.rb
spec/cc/analyzer/engine_spec.rb
spec/cc/cli/engines/install_spec.rb

The image key represents the argument given to `docker run` to run the 
engine's image. It is equally valid to use a name, an id, or any other 
identifier that `docker run` supports.
This change will allow Builder to pass exact image IDs and coordinate a 
version bump along with any change in the engine images that are run.

Remove image_id, rename image_name to image

---

lib/cc/analyzer/engine.rb
spec/cc/analyzer/engine_spec.rb

Example output:
```console
~/git_repos/codeclimate_test (master) 🐖  codeclimate analyze -f json
error: (CC::Analyzer::Engine::EngineFailure) Config for engine rubocop exceeds 64k character limit
```

Raise error if config json is too big

---

lib/cc/cli/analyze.rb
spec/cc/cli/analyze_spec.rb
spec/support/factory.rb

I was taking a look at https://github.com/codeclimate/codeclimate-fixme and how I could create an engine. I noticed that it has a [`.codeclimate.yml`](https://github.com/codeclimate/codeclimate-fixme/blob/2bea75025808e35182cc574b3ef9672dbe9d2ff0/.codeclimate.yml) file so I attempted to run codeclimate on it. But I received the following error: 
```
codeclimate-fixme[master] $ codeclimate analyze
Starting analysis
Running fixme: Done!
error: (NoMethodError) undefined method `[]' for nil:NilClass
```
First, `codeclimate-fixme` isn't in `config/engines.yml` nor could I find it in the docker registry. Are there plans to add it? 
Second, I guess we should not try to run engines if they're not in `config/engines.yml`. I took a similar approach as [this …

Do no run unregistered engines

---

lib/cc/analyzer/formatters/json_formatter.rb
spec/cc/analyzer/formatters/json_formatter_spec.rb

@codeclimate/review This PR updates output of `JSONFormatter` to print a valid json object - an array of json issue documents.
I updated the `started` and `finished` methods on JSONFormatter to print brackets (previously only parent class `Formatter` used these. They called in `anlayze` but they're empty methods).
I also added a `@has_begun` instance variable to keep track of started state. I investigated using `"\r "` and `"\b"` characters to remove the last `", "` when printing `document.json + ", "` but didn't get those strategies to work. Happy to hear feedback. 
```
Ashleys-MacBook-Pro:codeclimate ashleybaldwin-hunter$ codeclimate analyze -f json
[ {"type":"Issue","check_name":"Rubocop/Style/StringLiterals","description":"Prefer single-quoted strings 
when you don't need string …
```

Abh update json formatter

---

codeclimate-wrapper
lib/cc/analyzer/formatters/spinner.rb

@codeclimate/review This PR updates the codeclimate-wrapper script to run `docker --tty` only if stdout is a `tty`.
Impact: piping to a file with `codeclimate analyze` will result in plain text. Running `codeclimate analyze` will still produce normal colorful output and spinner.
Sample output post `codeclimate analyze > test.txt`:
terminal: nothing
file:

Abh update wrapper script

---

codeclimate-wrapper

@codeclimate/review @brynary PR refactors wrapper script to keep `--interactive` as arg in docker run command no matter what. (Since it's related to `STDIN`, I shouldn't have made its inclusion conditional in recent update to wrapper script.)
Tested locally by running `./codeclimate-wrapper analyze` and `./codeclimate-wrapper analyze > test.txt`

always keep --interactive as arg in docker run command

---

Gemfile.lock
codeclimate.gemspec

@codeclimate/review Bump `cc-yaml` version to latest release, to get updated warnings for incompatibility of `languages` and `engines` keys.

update gem file, particularly cc-yaml version bump

---

Gemfile.lock
codeclimate.gemspec

@codeclimate/review bumps to `cc-yaml 0.0.7`, which fixes `languages` parsing to use traditional format:
```
languages:
Ruby: true
JavaScript: true
```

bump to cc-yaml version 0.0.7 - fix languages key parsing

---

lib/cc/analyzer/engine.rb

I was trying to get an engine up for scss-lint and ran into this behavior:
```
Starting analysis
Running rubocop: Done!
Running scss-lint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine scss-lint failed with status 1 and stderr "/usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/file_finder.rb:33:in `find': All files matched by the patterns [nested/test2.scss, test.scss] were excluded by the patterns: [/code/nested/test2.scss, /code/test.scss, /code/vendor/bundle, /code/vendor/bundle/ruby, /code/vendor/bundle/ruby/2.1.0] (SCSSLint::Exceptions::AllFilesFilteredError)\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:58:in `scan_for_lints'\n\tfrom /usr/lib/ruby/gems/2.2.0/gems/scss_lint-0.40.1/lib/scss_lint/cli.rb:51:in `act_on_options'\n\tfrom …
```

Displaying error when engine raises exception

---

Gemfile.lock
codeclimate.gemspec

@codeclimate/review bump `cc-yaml` from `v0.0.7` to `v0.0.9`, which [fixes bug] (https://github.com/codeclimate/codeclimate-yaml/commit/4f7111b8607c86cf07632a347e4530a1ce2bd746#diff-db2eff17b198a77ecc2de173e25cf913R90) in `v0.0.8` and [keeps v0.0.8 new functionality] (https://github.com/codeclimate/codeclimate-yaml/commit/03b144bfd1b49b17ba4049b5957c93dbd773beb6):
1) Adds warning if no `engines` or `languages` key is found.
```
$ codeclimate validate-config
WARNING: No languages or engines key found. Must have analysis key. 
```
2) Updates language in warning for when both `engines` and `languages` keys are present.
old warning:
```
$ codeclimate validate-config
WARNING: engines key already found, dropping key: languages. Analysis settings for Languages and 
Engines are both valid but …
```

bump to v0.0.9 of cc-yaml

---

Gemfile.lock
codeclimate.gemspec

@codeclimate/review Bumps `cc/yaml` gem from `v0.0.9` => `v0.0.10` (latest version).
Diff [here] (https://github.com/codeclimate/codeclimate-yaml/commit/c35f416bc072ab052edccd33b3a29628bc61d38a). Changes analysis key issues from being counted as `warnings` to `errors`.
In CLI, user-facing difference:
before:
```console
$ codeclimate validate-config
WARNING: No languages or engines key found. Must have analysis key.
$ codeclimate validate-config
WARNING: Use either a Languages key or an Engines key, but not both. They are mutually exclusive.
```
after:
```console
$ codeclimate validate-config 
ERROR: No languages or engines key found. Must have analysis key.
$ codeclimate validate-config
ERROR: Use either a Languages key or an Engines key, but not both. They are mutually exclusive.
```

bump cc-yaml to 0.0.10

---

lib/cc/analyzer/formatters/formatter.rb
lib/cc/analyzer/formatters/json_formatter.rb
lib/cc/analyzer/formatters/plain_text_formatter.rb
spec/cc/analyzer/formatters/json_formatter_spec.rb
spec/cc/analyzer/formatters/plain_text_formatter_spec.rb

These are some behavior-neutral changes I have in my branch for ignoring
checks. I'm opening this separately so the eventual diff for the feature is
clearer.
- Change whitespace in JSONFormatter
The document itself doesn't use spaces between tokens, so we shouldn't have
whitespace after/before the overall brackets.
- Fix JSONFormatter spec
- Include Factory to cut down on noise
- Actually send in empty data for empty data spec
- Use must_equal not must_match which always succeeds if given the empty
string (causing pass-by-coincidence)
- Centralize engine_running behavior into superclass
- Sub classes shouldn't need to duplicate this
- Ensures a consistent instance variable (current_engine) is used
- Provide an attr_reader for it
- Paves the way for formatter-centralized issue exlusion …

Refactors during implementation of ignore-check

---

.rubocop.yml
lib/cc/analyzer.rb
lib/cc/analyzer/engine.rb
lib/cc/analyzer/engine_output_filter.rb
spec/cc/analyzer/engine_output_filter_spec.rb
spec/cc/analyzer/engine_spec.rb

Engines are instantiated with a string a json that corresponds to a modified
version of the YAML object under the engines key for the given engine. Within
this object, we'll now support a "checks" key that can hold check-specific
configuration including an enabled boolean.
This commit introduces an EngineOutputFilter that accepts this engine 
configuration and decides if the output of the engine should be written to the
formatter.
There is a lot of JSON generation and re-parsing going on that can seem 
redundant; I'm leaving this in place for now because orchestrating the various
parts that would need to change to address that is difficult.
One possible approach would be to enrich the interfaces involved and not pass
strings around so much. Engine would take a Hash of configuration and …

Add EngineOutputFilter, filter by check name

---

lib/cc/analyzer/engines_runner.rb
spec/cc/analyzer/engines_runner_spec.rb

Eventually, all engines will be updated to use the new hash format, but until then we need to pass a string `config` value to engines if that is the only thing present.

Temporarily handle codeclimate-yaml's config default

---

lib/cc/analyzer/engine_registry.rb
lib/cc/cli/command.rb
lib/cc/cli/console.rb
lib/cc/cli/engines/engine_command.rb
lib/cc/cli/engines/install.rb
lib/cc/cli/engines/list.rb
lib/cc/cli/init.rb
lib/cc/cli/validate_config.rb
spec/cc/cli/engines/install_spec.rb
spec/cc/cli/validate_config_spec.rb

@codeclimate/review This PR:
1) adds warning for invalid engines to the `validate-config` command
2) makes `engine_exists?` and `engine_registry_list` accessible via the `Engines` module through composition.

composition

---

lib/cc/analyzer/engine_registry.rb
lib/cc/analyzer/engines_runner.rb
spec/cc/analyzer/engines_runner_spec.rb
spec/cc/cli/analyze_spec.rb

@codeclimate/review Now that `validate-config` provides information about invalid engines, we can let `EnginesRunner` silently skip invalid engines.

dont raise on invalid engine

---

README.md

In `codeclimate help` the console command is listed but there is nothing
in the README.md to describe it's purpose.

Updating README.md to include the console command

---

spec/cc/analyzer/engine_spec.rb
spec/spec_helper.rb

- Replace OpenStruct with mocha stub
- Load anything in spec/support
- Nested describe to avoid namespacing
These are just some zero-impact improvements to the spec that I find useful in
another branch I'm working on (specifically the namespacing), and I'd like to
merge it first here to keep that eventual diff easier to review.

Improve Engine spec

---

lib/cc/analyzer.rb
lib/cc/analyzer/engine.rb
lib/cc/analyzer/engines_runner.rb
lib/cc/analyzer/null_container_log.rb
spec/cc/analyzer/engine_spec.rb
spec/cc/analyzer/engines_runner_spec.rb
spec/support/test_container_log.rb

We want to log the actions of starting, finishing, or timing out containers
into the database via Kafka/Wally. We will initially expose this information in
Admin and eventually to users via some kind of Builds dashboard.
Unfortunately, these actions occur very far away from the code that is actually
able to perform the logging:
CC::Builder  |  CC::Analyzer
=============|============================
Runner      -|-> EnginesRunner -> Engine
|                                 |
V                                 V
Kafka                           docker run
The approach implemented here passes a ContainerLogger object into
EnginesRunner and onto each Engine. This object responds to event methods which
the Engine invokes as it starts and stops containers.
Within this code base, the object is a …

Support container logging within Engine

---

lib/cc/analyzer.rb
lib/cc/analyzer/container.rb
lib/cc/analyzer/engine.rb
lib/cc/analyzer/engine/container_log.rb
lib/cc/analyzer/null_container_log.rb
spec/cc/analyzer/container_spec.rb
spec/cc/analyzer/engine/container_log_spec.rb
spec/cc/analyzer/engine_spec.rb
spec/support/test_container.rb
spec/support/test_container_log.rb

New responsibility breakdown:
**Container**: launch a docker container, give its stdout to the caller,
capture its stderr, monitor its process, handle timeouts, call life-cycle
events on the container-log given.
**Engine::ContainerLog**: perform the statsd calls on container life-cycle
events and then forward those events to the log its been given; sort of a
ContainerLog middleware stack idea.
**Engine**: launch and run a Container for the engine, specify how to shuttle
null-delimited stdout to the formatter, compose its container-log with the one
given.
Benefits:
- Engine is smaller
- Engine#run is smaller
- Container is singly-responsible and reusable for Clone in builder
- Easier to reason about (complex timeout logic is clearer IMO)
- Better tested
Notable change:
Rather than spawning …

Extract Container class from Engine

---

lib/cc/analyzer/container.rb
lib/cc/analyzer/engine/container_log.rb
lib/cc/analyzer/null_container_log.rb
spec/cc/analyzer/container_spec.rb
spec/cc/analyzer/engine/container_log_spec.rb
spec/support/test_container_log.rb

More than just the start event needs to know about container-specific
information (so far the container image and name). One solution to this would
be to instantiate a new log per container and pass in those values at
construction. This does not work for the following reasons:
- The object instantiating the log does not know these values
- The log also needs to know *build*-specific values (e.g. host and snapshot),
so we really want to instantiate a single log for the build with these values
passed in at construction (and the constructing object does know these)
The solution chosen is to pass in the container-specific values for every
life-cycle event, not just started.
/cc @codeclimate/review and h/t @noahd1 for spotting this originally

Pass container image and name to all logged events

---

README.md

Updated to https://hub.docker.com/u/codeclimate/ (previously: https://registry.hub.docker.com/repos/codeclimate/)

Update URL for Code Climate's Docker Hub Page

---

config/eslint/.eslintrc

Based on https://github.com/codeclimate/eslint/blob/master/conf/eslint.json. 
Equivalent to `extends: 'eslint:recommended'`.

Add default eslint config

---

Dockerfile

The version bundled with the base image is too old to handle whatever
SSL version get.docker.com requires. Updating wget when building the
container allows us to grab docker correctly.
This fixes the issue [building the image](https://circleci.com/gh/codeclimate/codeclimate/245)

Update version of wget inside of container

---

bin/check

If bin/check is run as root (i.e. via sudo make install), and the user is
unable to connect to docker (as root), the error message is confusing since it
instructs them to ensure docker version succeeds (which it likely does). In
fact, *sudo* docker version is the failing command that must succeed before
sudo make install would.
To address this confusion, we include sudo in the example command if the check
script is being run as root (UID=0).
Note: we're purposely ignoring the edge case where a user is running the check
script as root but not via sudo (e.g. su root) and our example command
incorrectly instructs them to try sudo docker version.
/cc @codeclimate/review @brynary

Update check message to use sudo when appropriate

---

lib/cc/analyzer/engines_runner.rb
lib/cc/analyzer/include_paths_builder.rb
lib/cc/cli/analyze.rb
spec/cc/analyzer/engines_runner_spec.rb
spec/cc/analyzer/include_paths_builder_spec.rb
spec/cc/cli/analyze_spec.rb

Caveat: At the moment, specifying the path part only works for `codeclimate-eslint` - which uses include paths instead of exclude paths internally.

Let users specify engines and paths as options to analyze command for easier debugging

---

lib/cc/analyzer/formatters.rb
lib/cc/cli/analyze.rb
spec/cc/cli/analyze_spec.rb

Formatters are meant to be instantiated with an instance of FileSystem,
however when handling the -f option we were instantiating it with the raw
directory. To fix this, Formatters.resolve now returns the class itself and
the caller instantiates it with the FileSystem instance it holds already.
Fixes #111
Note: my initial attempts at getting a meaningful failing spec around this
before implementing the fix were not successful, but I should probably figure
something out along those lines before merging.

Fix formatter instantiation

---

lib/cc/analyzer/include_paths_builder.rb
spec/cc/analyzer/include_paths_builder_spec.rb

IncludePathsBuilder was erroring on repos where .gitignore was a
directory (most likely due to developer error). Now it just skips
.gitignore instead.

Skip .gitignore if it's a directory.

---

.codeclimate.yml
Gemfile.lock
config/engines.yml
lib/cc/cli/config.rb
lib/cc/cli/init.rb
spec/cc/cli/config_spec.rb
spec/cc/cli/init_spec.rb

This adds the `default_config` option which is used to add default
configuration options to an engine. This also marks the duplication
engine as a default engine when ruby files are present.

Add `default_config` key with nested values

---

Gemfile.lock

Not sure what's best protocol for handling bundler differences. 
I think we want `0.6.4` for CC in gemfile.lock though. Looks like the last update might not have used a bundle.

update gemfile - unless we intentionally switched back to 0.6.3

---

.codeclimate.yml
.dockerignore
.rubocop.yml
config/engines.yml
lib/cc/cli/config.rb
lib/cc/cli/config_generator.rb
lib/cc/cli/init.rb
lib/cc/cli/upgrade_config_generator.rb
spec/cc/cli/config_generator_spec.rb
spec/cc/cli/config_spec.rb
spec/cc/cli/init_spec.rb
spec/cc/cli/upgrade_config_generator_spec.rb
spec/spec_helper.rb
spec/support/factory.rb
spec/support/file_system_helpers.rb

This adds an `--upgrade` flag the `init` command will recognize to upgrade classic configuration.
In the upgrade case, the logic for each individual engine should be:
* Enable it if its language was supported by the classic platform & was enabled in the user's existing classic config.
* Enable it if its language was not supported by classic platform, but it meets the normal criteria for inclusion.
* Do not enable it if its language was supported by the classic platform but it was not enabled in the user's classic config.
Additionally, if upgrading a classic config, do not alter `exclude_paths`, since this key existed for classic config & should be respected.
Basically, do what we would normally do unless it contradicts existing config.
There's definitely still opportunity for me clean …

`init --upgrade`

---

config/engines.yml
spec/cc/cli/config_generator_spec.rb

Looks like this was using the wrong yaml key: I don't see any reference
to `enable_patterns` in the code.

enable bundler-audit when Gemfile.lock present

---

bin/codeclimate-init
codeclimate.gemspec

To eliminate collisions between `bin/codeclimate` here, and the `codeclimate` binstub we distribute with out Docker image, we:
* Create a new `bin/codeclimate-init` binary, which can be used in Platform and is included as an executable in the gemspec
* Remove `bin/codeclimate` from the gemspec. It's still in the repo and directly findable, just not installed anywhere by `gem install` or `bundle install`.

Add codeclimate-init.

---

Gemfile.lock
codeclimate.gemspec

The `codeclimate-yaml` gem has to be upgraded for this gem to support
nested `config` for certain engines to work properly.

Upgrade codeclimate-yaml

---

lib/cc/analyzer/container.rb
lib/cc/analyzer/engine.rb

This PR allows the running container to stop analysis immediately in case of an output processing error.

Add a Container#stop method to exit early and send a finished event

---

lib/cc/analyzer/engine_output_filter.rb
lib/cc/analyzer/formatters/json_formatter.rb
lib/cc/analyzer/formatters/plain_text_formatter.rb
spec/cc/analyzer/engine_output_filter_spec.rb
spec/cc/analyzer/formatters/json_formatter_spec.rb

This prevents processing errors when the engine output is parsed into another structure by adding empty output to the `EngineOutputFilter` filter rules.

Add empty output to engine output filter rules

---

lib/cc/analyzer.rb
lib/cc/analyzer/engines.rb
lib/cc/analyzer/engines_runner.rb
spec/cc/analyzer/engines_runner_spec.rb
spec/cc/analyzer/engines_spec.rb

This reduces the responsibility of Analyzer::EnginesRunner so it only
runs analyses on an array of pre-instantiated Engines. Choosing and
instantiating engines with the correct config is now the responsibility
of Analyzer::Engines.
This is motivated in part by desired changes in stream handling in
platform -- separating these responsibilities here will give us more
flexibility elsewhere. In addition, the hope is that this might lead to
phasing out EnginesRunner entirely.

Extract Analyzer::Engines from Analyzer::EnginesRunner.

---

config/engines.yml

The previous regular expression pattern would match if there was a file named Gemfile.lock in any directory of the project but bundler-audit crashes if a Gemfile.lock isn't present in the project's root directory.

Only enable bundler-audit if Gemfile.lock in root

---

circle.yml
lib/cc/analyzer/container.rb
spec/cc/analyzer/container_spec.rb

It's generally believed that sending kill -9 to the docker-run client process in
an attempt to kill the running container is unreliable and incorrect. Really,
how could it work? The client process must exit immediately and can do nothing
to handle such a signal (like, for example, tell the docker server to stop the
container).
That said, this approach *seems* to work reliably in the timeout case. The spec
added here around the timeout behavior, which I believe is an accurate
reproduction of what should not work, works 100% reliably with either version of
the code.
What did not work was Container#stop. When a spec was added around this
behavior, the following was seen:
- The Process.kill("TERM") was ignored, but
- The Process.kill("KILL") occurring on eventual timeout was also ignored
- …

Use docker kill, not Process.kill

---

DEVELOPERS.md
bin/prep-release
bin/release

Now that master is a protected branch, we can't script the entire release
process because we're required to open the version bump as a PR and merge in
the web UI.
This patch splits out a bin/pre-release for the tasks associated with opening
that PR. bin/release is then reduced to only the steps to perform after that PR
is merged to master.
These scripts were used to release v0.9.4

Split out bin/prep-release

---

codeclimate.gemspec

Since we've moved to using the `codeclimate-init` script within Builder
we need to ensure that the default configurations are available within
the gem package so the initialization process can properly seed
repositories.

Include default tool configuration files in gem

---

lib/cc/analyzer/engine.rb

Certain applications will want this to be a higher value than 512MB, so
allow that to be set in the environment.
@codeclimate/review ping @jpignata @noahd1

Allow optional memory limit to be set in ENV

---

config/engines.yml
spec/cc/cli/config_generator_spec.rb
spec/cc/cli/init_spec.rb
spec/cc/cli/upgrade_config_generator_spec.rb

The behavior added in this PR adds the fixme engine after matching against any file within the include paths.

Always enable fixme engine when generating engines config

---

bin/prep-release

I ran into this git warning when running the pre-release script:
```
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'.
```
This PR specifies the origin and branch for a more explicit push which silences
the warning.

Specify remote and branch name when pushing to avoid git warning

---

config/engines.yml
lib/cc/analyzer/config.rb
spec/cc/cli/engines/enable_spec.rb

Some engines require a default configuration before they can work
properly. One such engine is the duplication engine which requires
languages to be specified before analysis. This pulls in any default
configuration specified in the engines registry when enabling an engine
within a `.codeclimate.yml` configuration file.
Follows codeclimate/codeclimate-duplication#24

Include engine's default configuration when adding to `codeclimate.yml`

---

Gemfile
Gemfile.lock
lib/cc/analyzer/container.rb
spec/cc/analyzer/container_spec.rb

This mimics the functionality of
https://github.com/codeclimate/codeclimate/commit/5efbcef61d2587a8612b01f9e1047b9aefd0153b.
I also removed it from the arguments because nothing was using it, and
it was easier to do the defaulting where it is now.

Allow container timeout to be specified in ENV

---

config/engines.yml
spec/cc/cli/init_spec.rb

@codeclimate/review @BlakeWilliams @jpignata In anticipation of adding new engines to manifest, this change orders engines already present in `engines.yml` manifest so that it is easier to read and modify going forward.

Alphabetize engines for easier addition going forward

---

config/engines.yml

I added this key when adding the Brakeman engine, but realized we
probably don't want or need it for now:
Upgrade_languages key is one of several variables used by Code Climate
to generate a .codeclimate.yml when none exists.
Since community engines (of which Brakeman is one), don't get added to
the generated config, the presence of the `upgrade_languages` key on
brakeman is behavior neutral, but confusing.
Although Brakeman only analyzes ruby applications, not all ruby projects
are apps suitable for Brakeman's security analysis, so we shouldn't use
the language alone as a reason to add the engine.
cc @jpignata @pbrisbin

Remove upgrade_languages key from brakeman engine description

---

circle.yml

- Use dependency.override, not pre
- Use conventional PRIVATE_REGISTRY variable
- Build the CLI image as a dependency
- Run tests in a docker container
This is an attempt to address intermittent failures in the Container#stop specs
by running tests in a more consistent environment.

Fixes to circle.yml

---

spec/cc/analyzer/container_spec.rb

Locally, if I run the spec in a loop I did see the assertion at line 196 fail
occasionally. This assertion is unnecessary IMO, so I removed it. On Circle, I
have seen the one at line 128 fail, so I've replaced it (and one other) with
better assertions that should provide more information next time they fail.
See commit messages for more details.

Improve container spec

---

spec/cc/analyzer/container_spec.rb

This assertion is designed to ensure the command was stopped and did not run to
completion. It seems the mechanics of stopping the container can take right
around 5 seconds and so a 5 second assertion fails intermittently on CI.
Example: https://circleci.com/gh/codeclimate/codeclimate/545
Given that the command, if not stopped, will run for 10 seconds, using that as
the assertion should reduce false-positives without risk of false-negatives.

Increase upper limit in duration expectation

---

config/engines.yml

The radon engine is currently generated from a [CC fork of the
radon project](https://github.com/mrb/radon), with hopes to be
integrated natively into the orginal project quickly.
Although the radon tool provides many code metrics, including
raw metrics, maintainability, halstead metrics and cyclomatic
complexity, the present engine wrapper will only report on
complexity issues.
More information about radon can be found at:
https://github.com/rubik/radon
Users can configure the minimum level of complexity they'd like to have
reported in their .codeclimate.yml file (A-F):
```
engines:
radon:
enabled: true
config:
threshold: 'd'
```
following, radon's conventions.
For more information about how radon grade levels translate to
cyclomatic complexity, please see the [radon …

Add radon engine to manifest

---

config/engines.yml

^lift has merged two products and settled on this name. We'll support
both the old and new names for the time being for backwards
compatibility.

Rename requiresafe to nodesecurity

---

lib/cc/analyzer.rb
lib/cc/analyzer/engines_config_builder.rb
lib/cc/analyzer/engines_runner.rb
spec/cc/analyzer/engines_config_builder_spec.rb

Giving builder more flexibility in how Engine instances are instantiated will make it easier to make certain classes more cohesive. This refactor will be followed up by one on the builder side.
Note that this PR breaks backwards compatibility, so I'll follow it up soon with a small refactor in builder.

Replace EnginesBuilder with EnginesConfigBuilder.

---

config/coffeelint/coffeelint.json

Finding these defaults is non-obvious, so I generated the default
config. More info on that: http://www.coffeelint.org/#usage
Having this here will make it more transparent what checks we're running
and make it easier for people to configure their analysis.

Add default coffeelint.json file

---

bin/codeclimate
lib/cc/analyzer/engine.rb
lib/cc/cli.rb
lib/cc/cli/command.rb
lib/cc/cli/test.rb

This PR creates the ability to invoke `codeclimate test engine_name` and have the CLI run a suite of regression tests for the engine.
The engine declares it's regression suite via the `test_paths` key in the new `engine.json` file (which must be in the root of the engine's filesystem) like this:
```json
{
"name": "fixme",
"description": "Discover lurking FIXMEs, BUGs, TODOs, etc. in your code",
"maintainer": {
"name": "Michael R. Bernstein",
"email": "mrb@codeclimate.com"
},
"test_paths": [
"/usr/src/app/test/integration/"
]
}
```
The test paths are unpacked, and we run every file in the directory as a test. (By invoking `codeclimate analyze` with the `--engine` option and also a single file path.) Tests are implemented as comments and look like the following:
```ruby
if (foo = "foo") …
```

Test subcommand

---

lib/cc/analyzer/container.rb
lib/cc/analyzer/include_paths_builder.rb
spec/cc/analyzer/container_spec.rb

Currently engines can generate an unbounded amount of output on STDOUT
and STDERR while running. This is bad for a variety of reasons, but the
symptom most pressing is that Docker has a memory leak around dealing
with large STDOUT streams especially when there are "slow" readers
attached.
This implements a concept of maximum output bytes that when tripped will
stop the container. The maximum output bytes is defaulted to 150
megabytes.
* Consolidate Result and ContainerData into ContainerStatus struct
* Suppress STDERR on git ls-files calls
cc: @codeclimate/review

Enforce a maximum output byte count on containers

---

config/engines.yml
lib/cc/cli/config_generator.rb

This change makes the above engines become automatically turned on when a user runs `codeclimate init` or an analysis on .com without a `.codeclimate.yml` (using an inferred config).
@codeclimate/review @jpignata

Automatically enable brakeman, pep8 and radon

---

lib/cc/analyzer/engines_config_builder.rb
lib/cc/analyzer/engines_runner.rb
spec/cc/analyzer/engines_config_builder_spec.rb
spec/cc/analyzer/engines_runner_spec.rb

Currently `include_paths` is called in `EnginesConfigBuilder` which is
initialized once for each engine which means we may have to build
`include_paths` several times when analyzing a repo.
Since building `include_paths` can be slow this hoists `include_paths`
into `EnginesRunner` and passes `include_paths` to
`EnginesConfigBuilder`.

Build include_paths once

---

lib/cc/analyzer/issue_sorter.rb
spec/cc/analyzer/issue_sorter_spec.rb

The previous sorting function didn't work properly with a mixed set of
locations that had positions with columns and lines. This changes the
sorting mechanism to use an array so we could indicate a secondary sort
criterion.

Ensure proper sorting of commingled location types

---

config/eslint/.eslintrc

Right now it doesn't specify default environments which results in
variables like $ and jQuery being reported as issues. This adds
browser, node, jquery, amd, and commonjs as default environments as a
starting point for repos running with an inferred configuration.

Add default environments to default eslintrc

---

Gemfile.lock
codeclimate.gemspec
lib/cc/analyzer/engine_output_filter.rb
spec/cc/analyzer/engine_output_filter_spec.rb

Engines now have a config option named `ignored_issues` which takes a
sequence of fingerprint values to check against reported issues. If an
issue matches one of the values of `ignored_issues` we filter it out.

Filter ignored issues

---

Gemfile.lock
codeclimate.gemspec
lib/cc/analyzer/engine_output_filter.rb
spec/cc/analyzer/engine_output_filter_spec.rb

This renames `ignored_issues` to `excluded_fingerprints` to keep the
`exclude_*` convention.

Rename ignored_issues to excluded_fingerprints

---

lib/cc/analyzer/include_paths_builder.rb
lib/cc/analyzer/path_minimizer.rb
spec/cc/analyzer/engines_config_builder_spec.rb
spec/cc/analyzer/engines_runner_spec.rb
spec/cc/analyzer/include_paths_builder_spec.rb

This replaces the existing Directory class with a minimizer class which
takes the paths to check against and diffs it against all the files in
project to get directories where possible instead of a list of files.
This change is necessary to be able to use engine specific excludes
without having to build up the include_paths over and over for each
engine.

Replace recursive directory class with minimizer

---

lib/cc/cli/command.rb
lib/cc/cli/help.rb
lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

This PR has two changes to the `codeclimate init` command config generation:
*minor*
1) make successful output messaging green
*major*
2) generate default configs if possible, even if `.codeclimate.yml` already exists. Keep same error / exit code 1 behavior. 
Since it might still be useful for users with a `.codeclimate.yml` to get default configs by running
`codeclimate init`, this change generates applicable configs even when
.codeclimate.yml present, before finishing with the same warning message and
exit code 1:
```
$ codeclimate init
Config file .csslintrc successfully generated.
Skipping generating coffeelint.json file (already exists).
Config file .eslintrc successfully generated.
Skipping generating .rubocop.yml file (already exists).
Config file .codeclimate.yml already present. …
```

green output

---

lib/cc/analyzer.rb
lib/cc/analyzer/engines_config_builder.rb
lib/cc/analyzer/engines_runner.rb
lib/cc/analyzer/include_paths_builder.rb
lib/cc/analyzer/path_entries.rb
lib/cc/analyzer/path_filter.rb
lib/cc/analyzer/path_minimizer.rb
lib/cc/analyzer/path_patterns.rb
spec/cc/analyzer/engines_config_builder_spec.rb
spec/cc/analyzer/include_paths_builder_spec.rb
spec/cc/analyzer/path_entries_spec.rb
spec/cc/analyzer/path_minimizer_spec.rb

This re-introduces `requested_paths` to several files that gets passed
into `include_paths_builder`. This was removed in an earlier commit but
is necessary for specifying individual files or paths to analyze instead
of analyzing the entire directory.

Fix analyzation of individual paths

---

config/engines.yml

The value of `app/**` results in things like images in `assets` being rated as "A"s, which isn't appropriate, since nothing is really scanning those files.
This restricts the pattern more to files & extensions we know brakeman looks at.

Fix brakeman ratings_paths

---

lib/cc/analyzer/container.rb
spec/cc/analyzer/container_spec.rb

There's a race between the main thread getting to this point after the
process finishes, and the two threads that process output from stdout &
stderr. When main thread "wins" that race, the result can be an
incorrect status for the events data on the engine step down the line:
e.g. the engine emits invalid output, but by the time the background
thread has tried to parse it & emitted an error, the main thread has
already decided the container is finished, so the error is never
attached to the relevant step.
:eyeglasses: @codeclimate/review

Container: fix race with IO processing

---

lib/cc/analyzer/include_paths_builder.rb
lib/cc/analyzer/path_filter.rb
spec/cc/analyzer/include_paths_builder_spec.rb

This is to address a regression
(https://trello.com/c/yQr7T7nH/1211-unreadable-files-lead-to-u10-without-error-visible)
that made it into builder from some recent changes here: these raises
were not caught anywhere, and the result on .com was a U10 without any
informative error text (because of where the exception ocurred).
Based on a recent conversation including Bryan, we'll probably expect
handling unreadable files to be an engine concern (if we want to avoid
walking the entire tree, we effectively *must* make it an engine
concern). This backs out this specific bit of logic to intentionally
*not* raise instead.
In my testing, this didn't actually change CLI behavior for the affected
case at all. In .com, analysis ran successfully with this fix, with some
engines emitting warnings on …

Don't raise on unreadable files when building paths: ignore them.

---

lib/cc/analyzer/config.rb
spec/cc/cli/engines/enable_spec.rb

It is confusing to add a blank config key and results in errors
for certain engines, like coffeelint
https://github.com/codeclimate/codeclimate-coffeelint/pull/12
cc @codeclimate/review @fhwang

Only add default config if one exists for engine

---

bin/release

since release is now a 2-step process, it seems silly to have to pass
the version to the release script since it'll be the value currently in
the VERSION file. If anything, there was a typo risk of typing the wrong
version & ending up with a mismatched release.

bin-release: don't require version arg

---

bin/prep-release

since we like to tag release PRs with compare links, I figured we may as
well automate that process where feasible.
Somebody with better git/terminal-fu than me can probably suggest a more effective way of getting the correct SHA for the release branch.
Thoughts, @codeclimate/review ?

prep-release: generate a compare link

---

lib/cc/analyzer/container.rb
spec/cc/analyzer/container_spec.rb
spec/support/test_container_listener.rb

1. Yesterday's patch for IO wait worked, but this technique is more performant (and I'm deleting redundant code I missed yesterday, and adding a spec.)
2. Due to how the timeout thread was instantiated, it might not be scheduled soon, and so actual timeout could be well after what was desired. By running the thread immediately, this should improve this behavior.
This is working for me locally, and I have managed to make things timeout correctly locally. It should also be noted that timeout behavior was already specced as well, and those specs were running fine. So I think the missed timeout I saw in production this morning was something different, possibly an isolated problem, but almost certainly not a consequence of the other recent changes. This should tighten things up overall. I'll …

improve io waiting, ensure timeout thread runs immediately

---

config/rubocop/.rubocop.yml

Default may make sense but the description of the issue is
confusing if your app isn't a rails app: "Do not write to stdout.
Use Rails' logger if you want to log"
/c @jpignata changed my mind after seeing the description

Disable Rails/Output check in inferred config

---

lib/cc/analyzer/container.rb

This seems like a possible cause of hanging builders after timeouts: we
aren't manually closing these IO pipes, and so they may be left open
when the process they're connected to is killed on some platforms? The
`pspawn` docs even say you should be sure to close these.
I haven't been able to reproduce the hanging builders locally, so this
is a bit of a shot in the dark.

close io pipes when threads exit

---

bin/prep-release

It appears `hub` doesn't like escaped chars in strings with `-m`. This
switches around to writing the message to a file and using that instead.

fix constructing multi-line pull request description

---

lib/cc/analyzer/container.rb
spec/cc/analyzer/container_spec.rb
spec/cc/analyzer/include_paths_builder_spec.rb

Previous behavior:
- Engine would run and complete in minutes
- Process.waitpid would return a successful status
- The else branch of if @timed_out would be followed
- If the engine produced a significant amount of stdout, and we're slow to read
it, the output buffers in the docker process (bloating RAM) and we block in
the Thread#join calls
- The timeout thread eventually reaches 15 minutes and invokes
reap_running_container directly (not stop)
- The docker kill is a no-op because the container's already finished
- Because it didn't go via #stop, @on_output is left untouched and continues to
churn
In such cases, the builder runs for as long as it takes to get through the
output. Things eventually do finish, but it takes forever and the memory bloat
of the buffered stdout can cause …

Fix output reader behavior in the face of timeouts

---

bin/prep-release

- gh was a go rewrite of hub, that eventually took its name
- Using stdin means no mktemp, which didn't work as invoked on Linux

Centralize on hub, use stdin

---

config/csslint/.csslintrc

Excluding by extension is less robust but much easier to implement and more
performant than other options that involve inspecting file content.
The tradeoff is worth it because doing it via a default configuration like this
is both discoverable and easily correctable if it causes users trouble.

Exclude minified css via --exclude-ext options

---

config/csslint/.csslintrc

Details: https://github.com/CSSLint/csslint/wiki/Beware-of-box-model-size
Our reasoning is that if you understand the CSS box model, you would find this
rule annoying and we should optimize for experienced CSS authors.

Ignore box-model in default csslintrc

---

spec/cc/analyzer/container_spec.rb

Example: https://circleci.com/gh/codeclimate/codeclimate/799
I've attempted to reproduce locally (with the same seed) and after looping for
a half an hour it's never failed. The error message is confusing, it states
that finished() was an unexpected invocation even though finished() is expected
and not yet invoked.
The ContainerData argument is probably a Red Herring, as that argument should
be present all the time, not (intermittently) missing. Therefore, I suspect
it's the boolean assertion within the with-block returning false intermittently
and materializing as the failure with a poor message (yay minitest-mocha) --
yes, this may indicate a real bug.
I believe moving the stdout_lines assertion outside of the with does not weaken
it, and I'm hoping it'll be more stable or at least …

Attempt to address flaky CI

---

config/engines.yml

This may not be a preferred way, but it is how Brakeman determines
what is a valid Rails app to scan and what isn't. If we choose a
different hueristic, than you can get into a scenario where codeclimate
by default enables Brakeman (b/c a script/rails exists), and then
brakeman complains it's not a Rails app (No 'app' directory).
It's unlikely to be the case, but still worthwhile for them to match
and I see no downside.
I tested this to ensure it only triggers when there's an app directory at the top level.
/c @codeclimate/review

Match brakeman's rules for Rails' app detection

---

config/engines.yml
spec/cc/cli/config_generator_spec.rb
spec/cc/cli/init_spec.rb
spec/cc/cli/upgrade_config_generator_spec.rb

Duplicate of #259 
This PR updates our engines registry to enable the [duplication engine][] for any project with Ruby, Python, JavaScript, or PHP files.
[duplication engine]: https://circleci.com/gh/codeclimate/codeclimate-duplication

Enable duplication engine automatically for supported languages

---

config/engines.yml

These engines will only be ran for Python and PHP projects respectively
when explicitly enabled via a project's codeclimate.yml.
This change strips each of their `enable_regexps` values and their
`upgrade_languages` keys.
@codeclimate/review @brynary

Disable PEP-8 and PHP CodeSniffer by default

---

DEVELOPERS.md

- We have `make image` available now
- The `VERSION` argument is not required for `bin/release`

Fix minor inconsistencies in DEVELOPERS.md

---

config/engines.yml
spec/cc/cli/config_generator_spec.rb
spec/cc/cli/init_spec.rb
spec/cc/cli/upgrade_config_generator_spec.rb

By surfacing & no longer silently swallowing errors that could lead to non-deterministic results, we are now in a bit of a tough spot because this is surfacing errors that look like straight-up bugs in the babel parser, but which programmatically aren't very distinguishable from previously mentioned non-deterministic results bugs.
(The underlying errors are parsing timeouts: previously these were low at 20 seconds and being swallowed, which was bad because memory pressure/gc behavior could swing execution to one side or the other of that line. Now they are high at 5 minutes & fatal, but due to what look like babel issues reliably happen on some files. It might be reasonable to swallow these extreme timeouts, but it would only take 2 or 3 of them to timeout the whole engine, so it hardly …

Don't enable duplication by default

---

lib/cc/cli/config_generator.rb

Add "dist" directory to list of auto-excludes used for "init"

---

config/rubocop/.rubocop.yml

Move Style section to end.
Add `Included Cops` comment listing headers for easy navigation.
Alphabetically order metrics section.
First step of [this pull](https://github.com/codeclimate/codeclimate/pull/283) updating default `.rubocop.yml` generated during `init`. 
@codeclimate/review @jpignata

Order checks alphabetically

---

config/rubocop/.rubocop.yml

Increase Class and Module length Max from 100 to 250
Turn on method length check
Increase method length Max from 10 to 80
- In light of grade point tuning
- leaves ABCSize enabled, Cyclomatic Complexity and Perceived Complexity disabled

Increase rubocop defaults for complexity checks

---

config/engines.yml
spec/cc/cli/config_generator_spec.rb
spec/cc/cli/init_spec.rb
spec/cc/cli/upgrade_config_generator_spec.rb

This reverts commit 42b73547439936963e1367e1bb00224f9c8b1e06.
I think duplication has looked healthy enough to turn back on by default.
See https://metrics.librato.com/s/spaces/119114/explore/1292334?duration=1185843 and https://bugsnag.com/code-climate/builder/errors/5646488122e6214965e7da4d?filters%5Bevent.since%5D%5B%5D=30d

Enable duplication by default

---

bin/release

In addition to git tags, this will tag docker releases with the version tag, in addition to updating "latest"
Would be nice to adjust the homebrew formula to pull the correct tag at some point as well, but that's more complicated, so I probably won't do it yet.
:eyeglasses: @codeclimate/review

Tag docker images with version

---

config/eslint/.eslintrc

Trying to match up the defaults here to what we have for RuboCop so we
can have a bit more consistency across languages.
This changes the triggering complexity threshold to 6 (same as in our
default .rubocop.yml in this repo), and max-statements (which is subtly
different from max length, but similar enough I think we can use the
same val for now) to 30 (which is RuboCop's internal default: we don't
set it explicitly in our `.rubocop.yml`).

tweak eslint defaults: complexity, max-statements

---

lib/cc/analyzer/formatters.rb

Previously:
```
$ codeclimate analyze -f asdf
error: (NameError) uninitialized constant CC::Analyzer::Formatters::InvalidFormatterError
```
Now:
```
$ codeclimate analyze -f asdf
'asdf' is not a valid formatter. Valid options are: json, text
```

Properly namespace exception so that the constant can be found

---

config/engines.yml

:information_desk_person: Although the [kibit Code Climate engine](https://github.com/andrewhr/codeclimate-kibit) is referenced in the [online documentation](https://docs.codeclimate.com/docs/kibit), it is not enabled in the list of engines. :crying_cat_face: 
As a Docker image for the engine hasn't been published to Docker Hub yet, which may be why it isn't listed in the [list of community supported engines](https://docs.codeclimate.com/docs/list-of-engines).
This change prempts the publishing of this Docker image and general availability of the `codeclimate-kibit` engine. :smile_cat: 
:warning: Depends on:

Enable the codeclimate-kibit engine

---

lib/cc/workspace.rb
lib/cc/workspace/exclusions.rb
lib/cc/workspace/path_tree.rb
spec/cc/workspace/path_tree_spec.rb
spec/cc/workspace_spec.rb

I'm excited about the direction of #300, but I was concerned that completely removing glob support was overly extreme, and I'd had some thoughts while I was traveling about how it might be done performantly. This PR is my first draft at implementing those thoughts building on top of @pbrisbin's work.
The key differences with our old technique are as follows:
* Directory contents are never walked until they need to be due to explicit inclusions or exclusions. As a result:
* The algorithm is much simpler than before: instead of a several-step process of collecting several disparate collections of paths, operating on relations between them, and then minimizing the resulting set, all operations are on a single sparse tree which is naturally minimized at all times.
* Less overall file I/O & …

Restore Glob Functionality to Workspace Refactor

---

codeclimate-wrapper

Just happened to notice that this bit referenced boot2docker when it
should be using docker-machine

Fix docker-machine error handling in wrapper

---

lib/cc/cli/init.rb

On large repos, `init` can take long enough to scan for engines that it
can feel hung/unresponsive since it outputs nothing until after it's
calculated the full `.codeclimate.yml`.
This adds a brief message to let the user know that work is happening.
I also added a status message about generating the default config for
engines: we output messages if we don't generate a config for an
engine because the file already exists, or if we do generate the file,
but we never tell the user we *are* going to generate configuration for engines:
without that context, telling them we decided not to copy something  we never
mentioned we might copy in the first place is odd. Especially in the existing-yaml case,
when there's a decent chance *all* of the files we might copy already exist.
FWIW I tried to …

Init: add output for steps

---

lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

Because of the behavior where we create engine configs even if a
`.codeclimate.yml` exists, there was a case where
`#create_default_engine_configs` would do the wrong thing: that method
still called `#available_engines` on `ConfigGenerator` to decide which
engines to create configs for. However, in the case of a
`.codeclimate.yml` created or edited by the user, there could be engines
that `available_engines` considers available, but that are not enabled
in the yaml. In that case, this method would create config files
for engines the user isn't using.
This changes the behavior to read the engines from the
`.codeclimate.yml`, since it must exist by the time this method is
called. As a bonus, in cases where the `.codeclimate.yml` already
existed & we didn't generate it, reading this from the …

Init: don't create engine configs when inappropriate

---

lib/cc/analyzer/filesystem.rb
lib/cc/cli/config_generator.rb
spec/cc/analyzer/filesystem_spec.rb
spec/cc/cli/config_generator_spec.rb

`ConfigGenerator` now has a slightly improved algorithm for finding
files matching engine's `enable_regexps`. This fixes a bug & noticeably
improves performance in some cases as well.
The bug fix is that because we used to check the *entire* tree for files
matching an engine's patterns, you could enable an engine whose only
matching files were in auto-exclude paths. E.g. a project under
`vendor/` might have some JavaScript files used for local scripting or
something while your own code had no JS at all.
The performance benefit comes for similar reasons as the recent
refactor of workspace calculation with exclude paths: we touch
less data & less of the filesystem.
The new algorithm is similar to the old one: we still shell out to
`find` for available files, but `find` now only searches …

Init: respect excludes when enabling engines

---

.dockerignore
Makefile
circle.yml
lib/cc/analyzer/container.rb

I went with separate test and citest make targets (vs "test: image test_only")
because running on CI is also different in that it should pass the CI-related
enviroment variables too.
d845ec6 has details about the race condition but not the fix, d0ee4b3 actually
implements what I think is a real fix.

Run specs in docker, fix race condition

---

lib/cc/cli/config.rb
spec/cc/cli/config_spec.rb
spec/cc/cli/init_spec.rb

Previously we appended `**/*` to all auto-excluded directories: that's
no longer required by the new exclude behavior, so no reason to keep it.

Simplify exclude_paths generated by init

---

lib/cc/analyzer/container.rb

I went with two minutes here and reduced the timeout on docker wait to match.
The five minutes originally chosen was entirely arbitrary. Allowing up to ten
minutes of additional time in a timeout scenario didn't seem like a good idea
and my gut is that if it doesn't stop within two, it probably won't.

Add timeout on docker kill invocation

---

Rakefile

We run `rake release`, a Bundler gem helper task, as part of our `bin/release`
script. This PR explicitly requires `bundler/gem_helper` and installs its
tasks within `Rakefile`, as they're not available by default:
```
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
RELEASE 0.18.2
rake aborted!
Don't know how to build task 'release'
```

Install Bundler gem helper tasks

---

lib/cc/cli/config_generator.rb
spec/cc/cli/config_generator_spec.rb

Our usage of `find` to get files to enable engines against is too
naive: there are some unusual local configurations that lead to an
invalid find invocation. The old code was effectively ignoring this,
leading to more confusing failures further down the line.
This replaces the naive execution with usage of `POSIX::Spawn` that
should 1) be more tolerant of weird file names anyway and 2) if find
does fail, will properly catch & report so at least the user gets an
error message pointing them in a useful direction.
@codeclimate/review this is in direct response to some builder errors we saw on
.com. It's only affected 2 repos I've seen, but this should result in a more
informative view on the build page, and should result in more informative
errors for us on the backend to improve this …

ConfigGenerator: Catch & report `find` failure

---

lib/cc/analyzer/engine_output.rb
spec/cc/analyzer/engine_output_spec.rb

Reverts codeclimate/codeclimate#332
This seems to have caused more errored builds. Reverting while I investigate to unblock folks.
cc @codeclimate/review @wfleming

Revert "Remove characters added by docker logging daemon"

---

codeclimate-wrapper

some people have it installed, but do not use it
i could not use codeclimate wrapper with installed docker-machine
but also working local install

[wrapper] do not use docker-machine if there is no name

---

lib/cc/analyzer/container.rb
lib/cc/analyzer/engine.rb
spec/cc/analyzer/container_spec.rb
spec/cc/analyzer/engine_spec.rb

This PR moves the `--rm` docker run option up a level to allow callers of
`CC::Analyzer::Container` to specify whether docker should automatically
cleanup engine containers after they exit. The CLI will still pass the `--rm`
option during engine runs, so this will be a transparent change for CLI users.
This update benefits Code Climate debugging efforts, giving us the option to
inspect a docker container after it triggered an errored build.

Allow gem callers to disable container cleanup (docker run --rm)

---

config/engines.yml

Since there are many breaking configuration changes between 0.35.1 and
0.37.2, support the previous version of the engine also so that users
who hit blocking issues with the current engine can revert back if
they do not wish to update their RuboCop configuration file.
This change means we will have to tag b165 as
codeclimate/codeclimate-rubocop-old and push it to Docker Hub.

Add old RuboCop engine to manifest

---

lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

This better matches the behavior of `init` without the `--upgrade` flag.

Generate engine configuration even when there is a platform yml

---

config/rubocop/.rubocop.yml

This fixes a weird experience where users with an autogenerated
.rubocop.yml had fixme issues reported.
Note: an alternative I considered was changing the fixme examples to lower case (which our Fixme engine ignores). Didn't go that route because I thought the dashes were more intention revealing and better convey the original example words intended.

Remove fixme issues from default .rubocop.yml

---

benchmarks/path_tree_benchmark.rb
lib/cc/workspace.rb
lib/cc/workspace/path_tree.rb
lib/cc/workspace/path_tree/dir_node.rb
lib/cc/workspace/path_tree/file_node.rb
spec/cc/workspace/path_tree_spec.rb

There was a bug here where if a directory was populated (probably due to
being partially excluded), and then later completely excluded (such as for
an engine-specific exclude), it would not actually be fully removed.
@codeclimate/review I chose to do a refactor first to (I hope) clarify the
behavior of this code & make it easier to read & understand. It's pretty much
copy-paste & some renaming, so I don't think it will make review terribly
difficult. The actual bug here is quite small: reviewing the two commits
seperately might be easiest.  I'm also happy to split into different PRs.

Fix bug excluding a directory after partially excluding it

---

codeclimate-wrapper

For context, this mechanism is used to disable colors when piping output. Only
if the wrapper script determines that stdout (fd 1) is connected to a terminal
(-t), does it use the --tty option, which ensures that a similar test used in
the container ($stdout.tty?) returns accurately.
Regardless of all that, the --tty flag cannot be used unless stdin is a
terminal. Therefore, we need to account for that as well.
Unfortunately, this means an invocation like
yes | codeclimate analyze
won't color its output, even though it probably should.

Don't use --tty unless stdin is also a terminal

---

lib/cc/analyzer/raising_container_listener.rb
spec/cc/analyzer/raising_container_listener_spec.rb

alternatively:
```
message = "engine #{engine_name} ran for #{data.duration / 1000} seconds
```

Correct unit in engine timeout message

---

Dockerfile
README.md
bin/codeclimate
bin/codeclimate-init
codeclimate-wrapper
lib/cc/analyzer.rb
lib/cc/analyzer/engine.rb
lib/cc/analyzer/mounted_path.rb
lib/cc/cli/analyze.rb
lib/cc/cli/command.rb
lib/cc/cli/test.rb
spec/cc/analyzer/engine_spec.rb
spec/cc/analyzer/formatters/json_formatter_spec.rb
spec/cc/analyzer/formatters/plain_text_formatter_spec.rb
spec/spec_helper.rb

This was some work I did on a plane ride a few weeks ago and forgot to PR until
now. The main driver for this change is that is allows users to stop us from
creating a root-owned `/tmp/cc` on their systems. As part of doing so, I was
able to (I think) clean up the code a bit and solve an issue where our test
suite would also create (or be impaired by) the root-owned temp directory.
I've tested local analysis, changing the temp location, and even changing the
code location to analyze some other, non-current directory. I still need to
test that builder can use this interface as-is.
---
Adds a "MountedPath" abstraction that provides a single identity for the case
where we have an in-container path and need to know the on-host path it
represents for the purpose of …

Refactor handling of mounted code and tmp paths

---

lib/cc/cli/config_generator.rb
spec/cc/cli/config_generator_spec.rb

These cause problems for the `find` command we run, so it's best we just
exclude them.

Exclude files that begin with a dash

---

codeclimate-wrapper

I'm not sure what's changed but it seems these variables need to be exported
(not just set) for docker to find them when using the value-less --env form.

Export CODECLIMATE variables in wrapper script

---

codeclimate.gemspec

Executables should only be ruby scripts as per
http://guides.rubygems.org/specification-reference/#executables
Fixes #381

Remove check as gem executable

---

Makefile

This reverts commit e26b09eaa5e57445f63d8aba71dee95cb507a2b0.
This doesn't work on docker-machine because the host path is in the VM and we
need to install locally. We'll have to take the risk of getting the wrapper out
of sync.

Revert "Install codeclimate-wrapper from image"

---

bin/release

Instead of dying, print a noticable warning. The automated step fails on my
machine for a strange zsh+chruby issue, but I'm happy to run it manually.

Allow Marketing site updates to fail

---

lib/cc/analyzer.rb
lib/cc/analyzer/config.rb
lib/cc/cli.rb

YAML is not loaded by default and now that we're using `.safe_load` from Psych
instead of the `safe_yaml` gem, we have load it explicitly.
```console
$ codeclimate analyze
error: (NameError) uninitialized constant CC::Analyzer::EngineRegistry::YAML
```

Require YAML in Analyzer and CLI

---

lib/cc/workspace/path_tree/dir_node.rb
spec/cc/workspace_spec.rb

`Hash#dup` does not `dup` values: I don't know why I thought it did. As a
result, excluding files deeper than 1 level in the workspace would apply
to the global workspace copy, not only the engine-specific workspace copy.
The fix here manually deep-clones the `children` hash, and `freezes`
some keys for good measure.
cc @codeclimate/review. This is intended to fix #397.

Ensure Workspace#clone clones everything

---

lib/cc/analyzer/engine.rb
lib/cc/analyzer/formatters/spinner.rb
lib/cc/cli.rb

The TTY spinner doesn't play well with debug output, and can create some odd interspersing of text.
Skipping the spinner results in the "Running..." status line not being output at all, so
I added the engine name to the relevant debug lines for clarity.

Don't try to show spinner when debug is on

---

lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

Running `init` in an empty directory correctly set up an empty config
yml, but then crashed trying to look for engine configs.

Don't crash `init` in an empty directory.

---

lib/cc/analyzer/engine.rb
spec/cc/analyzer/engine_spec.rb
spec/support/test_container.rb

The stderr here is a straight feature addition that I think will be important for the usefulness of the debug output.
The changes to string-escaping are a bit trickier, and probably merit some discussion. When all the output was escaped using `#inspect`, I personally found it difficult to read directly in the terminal.
It also made it harder to copy-paste directly into a JSON file. I recognize that the probable intent was to make it very easy to copy into a REPL, but since Ruby allows using `%[]` instead of quotes for literal strings, I don't think making the output easier to read/use elsewhere blocks that use case. The current choice of manually-escaping newlines/tabs might not be quite right, though. Thoughts, @codeclimate/review?

Debug mode improvements

---

lib/cc/workspace/path_tree/dir_node.rb
spec/cc/workspace/path_tree_spec.rb

When trying to add multiple paths with common parent, somehow some of
the paths are not added correctly. This is because the parent node is
always initialized even if it has been initialized before.
Example:
I have these files:
````
.git/FETCH_HEAD
.git/refs/heads/master
code/a/bar.rb
code/a/baz.rb
code/foo.rb
foo.txt
lib/thing.rb
````
Then run:
````
codeclimate analyze code/foo.rb code/a/bar.rb
````
It only evaluates `code/a/bar.rb`

Fix analyzer path bug

---

lib/cc/analyzer.rb
lib/cc/analyzer/engine.rb
lib/cc/analyzer/engine_output.rb
lib/cc/analyzer/issue_category_validation.rb
lib/cc/analyzer/issue_check_name_presence_validation.rb
lib/cc/analyzer/issue_description_presence_validation.rb
lib/cc/analyzer/issue_path_existence_validation.rb
lib/cc/analyzer/issue_path_presence_validation.rb
lib/cc/analyzer/issue_relative_path_validation.rb
lib/cc/analyzer/issue_type_validation.rb
lib/cc/analyzer/issue_validator.rb
lib/cc/analyzer/validation.rb
spec/cc/analyzer/engine_spec.rb
spec/cc/analyzer/issue_category_validation_spec.rb
spec/cc/analyzer/issue_check_name_presence_validation_spec.rb
spec/cc/analyzer/issue_description_presence_validation_spec.rb
spec/cc/analyzer/issue_path_existence_validation_spec.rb
spec/cc/analyzer/issue_path_presence_validation_spec.rb
spec/cc/analyzer/issue_relative_path_validation_spec.rb
spec/cc/analyzer/issue_type_validation_spec.rb
spec/cc/analyzer/issue_validator_spec.rb

This ports over the issue validations we have in Builder, as well as adding 3 new ones:
- Making sure a reported file exists
- Making sure the categories reported are valid
- Making sure the description is present (required by the spec)

Issue Validations

---

lib/cc/analyzer/issue_validator.rb

This makes it so that you can call `error` without necessarily checking
`valid?` first.
Fixes #413 

Validate when creating an IssueValidator object

---

lib/cc/analyzer.rb
lib/cc/analyzer/issue.rb
lib/cc/analyzer/source_extractor.rb
lib/cc/analyzer/source_fingerprint.rb
spec/cc/analyzer/engine_output_filter_spec.rb
spec/cc/analyzer/engine_spec.rb
spec/cc/analyzer/issue_spec.rb
spec/cc/analyzer/source_extractor_spec.rb
spec/cc/analyzer/source_fingerprint_spec.rb
spec/fixtures/source.rb

Currently, the default fingerprint for an issue is computed by creating an MD5 digest based on the path of the file which introduced the issue and the check name for the issue emitted.
The result of this fingerprint for many engines is that issues emitted with the same check name for the same file are given the same fingerprint. On codeclimate.com, we only show issues with unique fingerprints, so even if 100 issues were emitted for a file, if all issues share the same check name and thus the same fingerprint, we only show one issue.
Additionally, a fixed or introduced issue is often ignored if there are current issues with the same fingerprint already on the default branch.
This PR introduces new fingerprinting behavior to address these issues, first added to a [couple][markdownlint] …

Add SourceFingerprint based on path, check_name, and source

---

lib/cc/analyzer/issue.rb
lib/cc/analyzer/issue_location_format_validation.rb
lib/cc/analyzer/source_fingerprint.rb
spec/cc/analyzer/issue_location_format_validation_spec.rb
spec/cc/analyzer/source_fingerprint_spec.rb

This PR introduces a few fixes based on testing the new default fingerprinting:
- Validate that issue line or position values are integers
- Lazily compute the default fingerprint
- Handle invalid UTF-8 bytes

Update default fingerprinting

---

lib/cc/analyzer/source_extractor.rb

This fixes a bug where the source extraction process would mutate the issue location data.

Don't mutate issue location data during source extraction

---

.gitignore
Gemfile
Makefile
Rakefile

💁  These changes add an extra output format for tests to enable CircleCI to consume them.
> CircleCI can collect test metadata from JUnit XML files and Cucumber JSON
> files. We’ll use the test metadata to give you better insight into your build.
> For our inferred steps that use parallelism, we’ll use the timing information
> to get you better test splits and finish your builds faster.
https://circleci.com/docs/test-metadata/

Output test results in JUnit XML for CircleCI

---

Gemfile.lock

This PR updates the `Gemfile.lock` file with changes missing from #427.

Update Gemfile.lock to include rspec_junit_formatter

---

lib/cc/analyzer/issue_relative_path_validation.rb
spec/cc/analyzer/issue_relative_path_validation_spec.rb
spec/cc/analyzer/issue_validator_spec.rb

This PR updates the `IssueRelativePathValidation` to ensure that issue paths
are relative to the code directory.
Both the issue path and code directory paths are expanded before the relative
check.

Update validation to ensure project relative issue paths

---

lib/cc/analyzer.rb
lib/cc/analyzer/issue_path_is_file_validation.rb
lib/cc/analyzer/issue_validator.rb
spec/cc/analyzer/issue_path_is_file_validation_spec.rb
spec/cc/analyzer/issue_validator_spec.rb

Emitting issues for directories is not something we currently support. Doing so
was not causing visible problems until we added source-based fingerprinting
which attempts to read the path and errors on directories:
https://bugsnag.com/code-climate/builder/errors/5736508dbe3f29e6a6c1cde8?event_id=573e507dba76e62611aa1445
Note: this still returns true for symlinks; discussion for how to handle those
cases is still open and this patch should not impact that behavior either way.

Validate that issue-path is a file

---

Gemfile.lock
codeclimate.gemspec
lib/cc/analyzer/formatters.rb
lib/cc/analyzer/formatters/html_formatter.rb
lib/cc/analyzer/formatters/templates/html.erb
spec/cc/analyzer/formatters/html_formatter_spec.rb
spec/support/factory.rb

This is going to be very helpful for engine developers, primarily because it gives them a chance to see HTML rendered output versions of their description and content body.

Add HTML formatter

---

Gemfile.lock
codeclimate.gemspec
config/engines.yml
lib/cc/analyzer/engine.rb
lib/cc/analyzer/engines_config_builder.rb
lib/cc/cli/analyze.rb
lib/cc/cli/engines/install.rb
lib/cc/cli/help.rb
lib/cc/cli/test.rb
spec/cc/analyzer/engine_registry_spec.rb
spec/cc/analyzer/engines_config_builder_spec.rb
spec/cc/analyzer/engines_runner_spec.rb
spec/cc/cli/engines/install_spec.rb

- Rewrite registry to replace image:x with channels[stable]:x
- Update engines-config-builder to look for channels.stable
- Improve error messaging for ImageRequired errors to indicate the cause may be
an invalid channel
- Support -e engine:channel on the command line
Individual commits have more details.
This is a fully backwards compatible change. Builder should pick up the new
logic in engines-config-builder, but it'll need to rewrite its own manifest to
support channels as well as add its own error handling for ImageRequired.
Here in CLI, we specify that tag-less images on Docker Hub are for the stable
channel. When we have non-stable channel images, those will likely be tagged as
the channel on Docker Hub. In Builder, the channel keys will always specify
"fully qualified" (i.e. …

Support engine image channels

---

lib/cc/analyzer/engines_config_builder.rb
spec/cc/analyzer/engines_config_builder_spec.rb

A channel read via CC::Yaml will be a Yaml::Nodes::Scalar, not a String, so
(even though printing things looks like it'd all work), looking up into the
registry Hash always fails: Scalar("stable") != "stable".
When there's no channel in the config, CC::Yaml defaults to the String "stable"
(not a Scalar representing "stable"), so the behavior for a defaulted channel
was tested and worked, and the behavior for an invalid channel was tested and
worked. However, the behavior for a non-defaulted, and valid channel doesn't
work without this fix.

Fix type error in channel lookup

---

config/engines.yml

I locally built and pushed an image from codeclimate/codeclimate-eslint#79 so
it's now available to try. Consider this a quiet release for wider testing,
it's entirely opt-in.

Add eslint-2 channel for eslint engine

---

lib/cc/analyzer/engine_registry.rb
spec/cc/analyzer/engine_registry_spec.rb

`--dev` mode broke following our introduction of engine channels. This PR updates the registry to produce a structure compatible with the new `RegistryAdapter` when in dev mode.

Support engine channels in dev mode

---

lib/cc/analyzer/source_fingerprint.rb
spec/cc/analyzer/source_fingerprint_spec.rb

This is sometimes run before issue validations, so it should correctly
handle a missing file

Don't error creating the fingerprint when the file doesn't exist

---

codeclimate-wrapper

These can be useful for debugging / authoring, so pass them through

Pass engine parameter ENV vars through wrapper

---

lib/cc/analyzer/issue_validations.rb
lib/cc/analyzer/issue_validations/content_validation.rb
spec/cc/analyzer/issue_validations/content_validation_spec.rb
spec/cc/analyzer/issue_validations_spec.rb

We occassionally see invalid contents emited that will blow things up
further down the line (like a `null` body, for example). This adds a
validation to catch these things earlier.

Validate Issue Content key

---

codeclimate.gemspec

Before this, codeclimate was requiring activesupport ~>4.2. This was
leading to conflicts with Rails 5, which requires activesupport 5.0.0.1.
5.0.x has passed the unit tests and seems to work locally with the
current codeclimate's code.
This was discussed on issue #477.
Signed-off-by: Rafael Reggiani Manzo <rr.manzo@protonmail.com>

Loose activesupport dependency requirement

---

bin/release

New pricing page doesn't show this data. We don't need this anymore.

Don't update marketing site data on deploy

---

config/engines.yml

This commit configures an eslint-3 channel for the codeclimate-eslint
engine, wrapping [ESLint 3][]:
[ESLint 3]: http://eslint.org/blog/2016/07/eslint-v3.0.0-released
```yaml
engines:
eslint:
enabled: true
channel: "eslint-3"
```

Add eslint-3 channel to engines manifest

---

config/engines.yml

This commit adds the Code Climate [credo engine][cc-credo] to the engines manifest.
[cc-credo]: https://github.com/fazibear/codeclimate-credo

Add Credo engine with beta channel

---

config/engines.yml

For parity with builder & using the CLI with projects configured to use this channel.

Add the rubocop  cache-support channel

---

config/engines.yml

Too many cache & channel branches in my head recently, I used the wrong word.
cc @codeclimate/review, I intend to merge on green.

Fix rubocop channel name

---

README.md

The standard readme proposes the environment variable to define where is the code to analyse (for the docker machine) as $PWD. In reality the code, internal to the docker, is into the */code* folder which is mounted on $PWD.
I think leaving it in that way can bring to confusion...

Update Readme fixing code Path

---

lib/cc/analyzer/formatters/html_formatter.rb

This commit fixes undesired formatting of code within markdown content
when emitting issues with the HTML formatter.
Addresses https://github.com/codeclimate/codeclimate/issues/499

Do not parse emphasis inside of words when rendering markdown

---

config/rubocop/.rubocop.yml

This one was renamed, so it emits a deprecation warning now.
We should do a more thorough audit at some point -- There are some new
cops that have been introduced which are disabled and not listed, so
people don't easily know how to enable them.

Update default inferred rubocop config

---

Gemfile.lock

Brings in a bugfix for less-common config styles using non-scalar values
as values in arrays/hashes

Update to cc-yaml 0.10.2

---

README.md
lib/cc/cli/help.rb

The docs as written-here were confusing. For one thing, they were incorrectly
implying that `path` is a required argument: it's not, and providing a path like
`.` has suprising behavior for a lot of users.
This updates the short-help to make `path` more obviously optional, and adds a
paragraph to the fuller description below explaining the behavior of `analyze`
more fully both when `path` is provided & when it is not.
cc @codeclimate/review this has come up in a few GH issues, and I realized our docs were misleading.

Fix README help for `analyze` command

---

README.md

The example value given for `CODECLIMATE_CODE` in the explicit `docker run` example is wrong & won't work (unless you actually happen to be editing a project located at `/code` on your computer.) This ENV var needs to be the code path *on the host*, because it's used to construct the mount paths for sub-containers like engines.

Fix explicit docker example in README

---

config/engines.yml

This PR adds a stable channel for the stylelint engine: https://github.com/gilbarbara/codeclimate-stylelint

Add stable channel for stylelint engine

---

lib/cc/cli.rb
lib/cc/cli/analyze.rb
lib/cc/cli/command.rb
lib/cc/cli/console.rb
lib/cc/cli/engines.rb
lib/cc/cli/engines/disable.rb
lib/cc/cli/engines/enable.rb
lib/cc/cli/engines/engine_command.rb
lib/cc/cli/engines/install.rb
lib/cc/cli/engines/list.rb
lib/cc/cli/engines/remove.rb
lib/cc/cli/help.rb
lib/cc/cli/init.rb
lib/cc/cli/prepare.rb
lib/cc/cli/runner.rb
lib/cc/cli/test.rb
lib/cc/cli/validate_config.rb
lib/cc/cli/version.rb
spec/cc/cli/command_spec.rb
spec/cc/cli/runner_spec.rb

Adds `codeclimate help command` which displays extended help for a command. It's possible to pass multiple arguments to `help` subcommand.
Help summary also shows short help for each of available commands.

Extend help command

---

config/engines.yml
lib/cc/analyzer/engines_config_builder.rb
lib/cc/cli/config.rb
lib/cc/cli/config_generator.rb
lib/cc/cli/init.rb
spec/cc/analyzer/engines_config_builder_spec.rb
spec/cc/cli/config_generator_spec.rb
spec/cc/cli/config_spec.rb
spec/cc/cli/init_spec.rb

(assume the feature is enabled)
With no existing `.codeclimate.yml` file:
- Running `codeclimate init` will generate a config file complete with _codeclimate checks_
With an existing `.codeclimate.yml` file
- Running `codeclimate init --upgrade` will add any missing _codeclimate checks_ to yer yahmal.
This an idempotent operation, so multiple upgrades will behave as expected (re: no dupes)
---
Holy smokes. It was suuuuuuuuper hard to figure out where the best place to make this change was. In the end I'm pretty happy with how it came out. Hi-fives to @pbrisbin for letting me torture him about this for several days.

Add Code Climate Checks

---

Gemfile.lock
Makefile
bin/prep-release

- This means a local ruby installation is not required to release.
- Also update Gemfile.lock for codeclimate-yaml update

Update release scripts to use docker

---

config/engines.yml
lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

CC CLI has default configs for a few engines it makes sure to not overwrite them but some engines accept a few files for configs (e.g. ESLint). In those cases CC CLI would generate a config even if there's a config for engine with a different name.
Here a new option is introduced in engine registry: `config_names`. It's a hash with keys being names of files in config template directory and values being arrays of possible alternative names.
See [example](https://github.com/pointlessone/codeclimate/blob/1b1580fc48cec93ae3ca310c1bd705bfd22d1526/config/engines.yml#L164-L169).
Template file name is included into a list of collision detection and doesn't need to be included into alternative names list. When the section is missing template file names used for collision detection anyway.
---
⚠️ …

Check for all possible config names before generation

---

lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

This can error when in dev mode or when using engines not available in
the CLI

Don't error if an unknown engine is encountered in `init`.

---

.dockerignore

I noticed in our latest CLI release, we accidentally included a file
config/eslint/.eslintrc.yml.swp, and so this gets included when people
run `codeclimate init --upgrade` in their javascript repos.

Dockerignore some common swap files

---

config/engines.yml

We've shipped flog as a stable engine, so we should unpin the stable
channel locally.

Allow running flog stable

---

Gemfile.lock
codeclimate-wrapper
codeclimate.gemspec
lib/cc/cli/file_store.rb
lib/cc/cli/global_cache.rb
lib/cc/cli/global_config.rb
lib/cc/cli/runner.rb
lib/cc/cli/version_checker.rb
spec/cc/cli/file_store_spec.rb
spec/cc/cli/global_cache_spec.rb
spec/cc/cli/global_config_spec.rb
spec/cc/cli/runner_spec.rb
spec/cc/cli/version_checker_spec.rb

If using codeclimate-wrapper, manage config.yml and cache.yml files in the
user's home directory (following the XDG spec). These files are currently used
to manage the recently introduced version check feature.
Just re-opening #587 against master.

Support config and cache file

---

Makefile
lib/cc/analyzer/issue.rb
spec/cc/analyzer/engine_spec.rb
spec/cc/analyzer/issue_spec.rb

According to the Code Climate
[SPEC](https://github.com/codeclimate/spec/blob/master/SPEC.md#issues)
today, issue severities are optional.
The SPEC was recently updated to include a list of five severity types:
info, minor, major, critical, blocker.
When an engine emits no severity, by default we'll report a severity of "minor".

Assign minor severity by default

---

lib/cc/analyzer/issue_validations.rb
lib/cc/analyzer/issue_validations/severity_validation.rb
spec/cc/analyzer/issue_validations/severity_validation_spec.rb
spec/cc/analyzer/issue_validations_spec.rb

Although severity continues to be an optional attribute for an engine to
emit, we now default to MINOR severity, and only permit 6 options: info,
minor, major, critical, blocker and normal (deprecated).
This validation enforces that restriction to ensure compliance with the
[CC
SPEC](https://github.com/codeclimate/spec/blob/master/SPEC.md#issues).

Validate severity on issues

---

lib/cc/cli/version_checker.rb
spec/cc/cli/version_checker_spec.rb

Prevents interference when piping `stdout` output to another process.
Partially addresses #609.

Emit version checker warning on stderr

---

lib/cc/cli/init.rb
spec/cc/cli/init_spec.rb

We currently set .eslintrc.yml as the desired inferred configuration
filename for ESLint but fail to skip when a file with the same filename
is already present within the workspace.

Scan for inferred config target filename alongside alternates

---

lib/cc/cli/runner.rb
spec/cc/cli/runner_spec.rb

We exit 0 in `Runner` when handling exceptions. That's pretty surprising, and is
very problematic for any attempt to use the CLI within a script or an editor
plugin or anything of that kind: it can lead to accidentally thinking everything
went fine & found no issues when in fact analysis just didn't run. I'm shocked
we've made it this long without this being a problem, actually.

Exit 1 when due to an unexpected error

---

lib/cc/cli/version_checker.rb
spec/cc/cli/version_checker_spec.rb

Issue #619
Rather than using the cached version when we're not hitting the API, we
should skip the outdated check entirely.

Don't use the cached version if we are not checking for a new version

---

lib/cc/config/default.rb
lib/cc/config/yaml.rb
spec/cc/config/yaml_spec.rb

The primary use-case is the prepare.files step and eventual auto-enable
plugins feature. If we load and validate a config, pull in a .rubocop.yml
through prepare.files, we want Config#engines to auto-enable rubocop
because that file is now present. To do this we'll Config#reload after
prepare.
Note: the reload does not re-read the yaml from disk. This is to avoid the
caller forgetting to re-validate a reloaded config, and risking confusing
downstream errors. That means we don't support prepare.files pulling down a
change to codeclimate.yml itself.

Support a #reload operation on Config objects

---

lib/cc/analyzer/bridge.rb
lib/cc/cli/analyze.rb
lib/cc/config/default.rb
lib/cc/config/engine.rb
lib/cc/config/yaml.rb
lib/cc/engine_registry.rb
spec/cc/config/yaml_spec.rb
spec/cc/engine_registry_spec.rb

- Config#engines should be a Set
This prevents any configuration or CLI arguments from causing the same engine
to be run twice -- a bug that's particularly hard to avoid with our QM-related
changes.
- Config#engines should include disabled engines
They should be filtered only as part of running them. This allows us to
manipulate the list for enabled-ness after the fact.
- -e,--engine should work again
Given the above two, this was trivial to re-add.
- Handle EngineDetailsNotFoundError correctly
Need to rescue in the loop, not outside. This means that listener.finished may
be called with nil engine_details. No listeners in this codebase rely on it,
but Builder will need tweaking to handle it.

Fix bugs related to running engines

---

lib/cc/cli/validate_config.rb
lib/cc/config.rb
lib/cc/config/yaml/validator.rb
spec/cc/cli/validate_config_spec.rb
spec/support/factory.rb

UX/UI:
- Exit non-zero if ERRORs are found, so this works as a fail-able Build step
- Don't color whole lines, makes them harder to read
- Don't color success messages, it was also hard to read
- Don't color WARNINGs red, I think this was a bug
- Filter validation issues that are expected in QM-land
Functionality:
- Allow injecting registry (undocumented) so we can run this "normally" via
Builder instead of having to require and invoke classes ourselves (and fake
our usual container logging, snapshot-events, etc, etc).
Implementation:
- Encapsulate through a class under CC::Config, so we have only a single place
to change as we move from CC::Yaml to the new CC::Config-based logic to
support Quality Model.

Fixes to validate-config

---

lib/cc/analyzer/bridge.rb
lib/cc/config/default.rb
lib/cc/config/engine.rb
lib/cc/config/yaml.rb
spec/cc/config/engine_spec.rb
spec/cc/config/yaml_spec.rb

Working with config.config was confusing, but there is good reason: we always
want to read and store config.checks, config.exclude_fingerprints, etc. Putting
the whole Hash as-is into the Config::Engine object is overall simpler.
Note: this is safe because of our existing assumption that this code works on
pre-validated configuration.

Config::Engine#config is the entire config

---

lib/cc/config.rb
lib/cc/config/default.rb
lib/cc/config/yaml.rb
spec/cc/config/yaml_spec.rb

- Remove #reload methods on Config objects
Thought this would be needed, it was not. Classic YAGNI.
- Don't memoize in CC::Config#load
This isn't useful and can sometimes leak state across tests.

Minor QM fixes

---

config/engines.yml
lib/cc/analyzer.rb
lib/cc/analyzer/bridge.rb
lib/cc/analyzer/plugins.rb
lib/cc/config/default.rb
lib/cc/engine_registry.rb
spec/cc/analyzer/plugins_spec.rb

For engines which have auto_enable_paths in the manifest, check if any of the
paths exists. If one is found, (auto-)enable the corresponding engine and set
its config.file to the found path.

Auto-enable plugins

---

README.md
codeclimate-wrapper

The invocation is simple:
```shell
echo "randome code" | codeclimate analyze lib/useful.rb
```
Key parts:
* This works only with `analyze` subcommand
* A filename must be specified. This is to properly chose engines, apply inclusion/exclusion rules, and let engines pick up the right configs. Only one filename must be specified.
* Pipe source to the commands STDIN.

Add an option to analyze a file from STDIN

---

README.md

Since Docker for Mac stabilized, we've switched over internally, and
it's worked well. Let's recommend that externally as well.

Update macOS recommendation

---

codeclimate-wrapper

A number of issues has been fixed:
* Validate file list only when there's something on STDIN
* Fixed recursive file linking
* Removed debug output
* Removed `exec` so that clean up trap could be executed

STDIN analysis fix

---

lib/cc/cli/version_checker.rb

The previous way results in "bad request" responses. I'm not actually
sure why. But I confirmed that with this change, the user agent shows up
in our logs when the version checker runs.

Fix how we set user agent

---

lib/cc/cli.rb

I accidentally updated activesupport in my last CLI release:
https://github.com/codeclimate/codeclimate/pull/657
And this version has a bug. Context:
https://github.com/rails/rails/issues/28918#issuecomment-298084204
This change patches over the bug. I could also downgrade activesupport,
but I think it's likely to happen again via our `bin/prep-release`
script, so this feels more stable to me.

Ensure Module#remove_method is defined

---

spec/cc/workspace/path_tree_spec.rb

`PathTree` is complicated, and questions often arise about "expected
behavior". This is just a quick spec exercising a current piece of
behavior so that it's documented.

Add spec exercising exclude-children behavior

---

config/engines.yml

Like any other engine, the CLI just runs :latest. I'm not sure why this
would've been pinned to a build.

Run codeclimate-structure:latest

---

bin/release

I recently installed ruby 2.4.1 and hadn't yet installed everything I
need to run this, and it led to a kind of awkward LoadError. This should
make it automatically bundle install when necessary.

Bundle if necessary in bin/release

---

lib/cc/analyzer/engine.rb

If an engine respects a top-level `debug` key in `/config.json`, it will
receive it's value from `CODECLIMATE_DEBUG`. The boolean-ness is the same as
how it's used in this codebase: any value is considered true, even `0` or
`"false"`.

Pass DEBUG onto engines

---

lib/cc/analyzer/bridge.rb
lib/cc/cli/analyze.rb
lib/cc/config.rb
lib/cc/config/default.rb
lib/cc/config/engine.rb
spec/cc/config/engine_spec.rb
spec/cc/config_spec.rb

To backfill repositories with historical analysis, we need to run builds on
commits many years old. Such commits might have code and configuration that
expects the then-latest version of engine tooling (e.g. rubocop). This causes
the builds to fail.
Our own engines should be stable to this (or we will make it so), but we can't
in any way ensure recent plugins would run on older codebases. Therefore, we'll
not run any plugins in such builds.
This will knowingly create builds that are missing any issues or analysis data
provided by plugins. Because of this, they can't be used to render results on
site or as merge-base analyses in comparisons. We're comfortable with this
limitation.

Support disabling plugins when analyzing

---

Gemfile.lock
codeclimate.gemspec
lib/cc/analyzer.rb
lib/cc/analyzer/engine.rb
lib/cc/analyzer/engine_output_overrider.rb
spec/cc/analyzer/engine_output_overrider_spec.rb
spec/cc/analyzer/engine_spec.rb

Issue override is a way to modify engine output. At the moment there's only one override: severity. It can be any of the values specified in [the spec](https://github.com/codeclimate/spec/blob/master/SPEC.md#issues).
Depends on codeclimate/codeclimate-yaml#41

Add issue overrides

---

lib/cc/config/json.rb
spec/cc/config/json_spec.rb

This is the new key for specifying plugin engines.
Since we'll shortly be ignoring legacy yaml entirely when JSON is
present, we also have a practical need to be able to configure
structure/duplication in this file (e.g. to set channel), so this will
respect configuration for those engines under the "plugins" key, even
though they are not semantically plugins.

Support "plugins" in JSON config

---

lib/cc/config.rb
spec/cc/config_spec.rb

With plugins, we now support all core config fields in the new schema
(excpect prepare, which I'll address soon). To simplify the
understanding of the system, we're moving towards only loading one of
these files: right now, the newer-schema JSON is the pre-eminent one, so
we won't load YAML if the JSON exists.

Either YAML or JSON, never both

---

lib/cc/analyzer/plugins.rb
spec/cc/analyzer/plugins_spec.rb

This is an older style of config that engines should not rely on
anymore: though some still handle it, others will crash.
When auto-enabling an engine based on the config file existing, the
explicit config should not be needed anyway: since it's the auto-enable
path, it should be one of the paths the engine will look for by default
anyway.

When auto-enabling, don't write `config: FILENAME`

---

lib/cc/cli/analyze.rb
lib/cc/cli/analyze/engine_failure.rb

We pass two args to these exceptions now, but the CLI's internal
exception class wasn't updated to take one.

EngineFailure: take engine_name argument

---

config/engines.yml
lib/cc/config/default.rb
spec/cc/cli/engines/enable_spec.rb
spec/cc/config_spec.rb

We are already analyzing complexity for java by default on QM.

Enable java duplication analysis by default for QM

---

Gemfile.lock
codeclimate.gemspec
lib/cc/engine_registry.rb

We've been mixing-and-matching these two approaches for a while. This
removes the final usage of `SafeYaml` and removes the gem.
`SafeYaml` is a 3rd party gem unassociated with the core Ruby team, and
it hasn't been touched in years. `YAML.safe_load` is a core part of
`Psych` distributed with Ruby, so it's naturally going to get more
modern updates & attention that `SafeYaml` will not. I ran many of
`SafeYaml`'s own examples through `YAML.safe_load` and `YAML`'s behavior
is equally correct.

Prefer YAML.safe_load to SafeYaml

---

lib/cc/cli/command.rb
lib/cc/cli/engines/engine_command.rb
lib/cc/cli/engines/install.rb
lib/cc/cli/engines/list.rb
lib/cc/engine_registry.rb
spec/cc/cli/command_spec.rb
spec/cc/cli/engines/install_spec.rb

Trying to move away from the legacy `Analyzer::Config` and
`Analyzer::EngineRegistry` to get more things using the newer
equivalents.
This happens to improve some behavior of `engines:install` as well: previously
it would install every available channel for an enabled
engine, which is pretty excessive. This now only installs the image for
whatever channel the user has enabled.

Use new Config & EngineRegistry for remaining engines commands

---

lib/cc/config/validation/json.rb
lib/cc/config/validation/yaml.rb
spec/cc/cli/validate_config_spec.rb
spec/cc/config/validation/json_spec.rb
spec/cc/config/validation/yaml_spec.rb

This should always exist in JSON configs, but we still support v1 YAML,
so in YAML it only warns if it sees one of the v2 keys.

Config validation: warn about missing version key

---

config/engines.yml

These are no longer used, since `init` is gone.

Remove auto_enable_paths

---

lib/cc/analyzer/bridge.rb
lib/cc/analyzer/container/result.rb
lib/cc/analyzer/formatters/plain_text_formatter.rb
lib/cc/analyzer/logging_container_listener.rb
lib/cc/engine_registry.rb
spec/cc/analyzer/bridge_spec.rb
spec/cc/analyzer/formatters/plain_text_formatter_spec.rb
spec/cc/analyzer/logging_container_listener_spec.rb
spec/cc/engine_registry_spec.rb

In .com we "skip" invalid engines, and don't crash on them. Treating a
missing engine as an exit code `99` will make maintaining that behavior
in .com difficult due to some other details of error handling.
This seems preferable: we'll treat skipped results as exit code `0`
(since they're not "errors"), and mark them as `skipped`, similar to
other meta-states like timed out.
I've also made the CLI's handling of this state more similar to what
.com's behavior used to be, and will be again: we don't crash, we just
warn.

Skip engines that are missing, warn about them being skipped

---

config/engines.yml
lib/cc/analyzer/bridge.rb
lib/cc/analyzer/engine.rb
lib/cc/engine_registry.rb
spec/cc/analyzer/bridge_spec.rb
spec/cc/analyzer/engine_spec.rb
spec/cc/engine_registry_spec.rb

Set SonarJava memory to 2G
Related to https://github.com/codeclimate/app/issues/6291

Allow engines to tell a minimum required memory to run

---

lib/cc/config/default_adapter.rb

Exclude TypeScript declaration files (`d.ts`) from analysis by default.
These files are not source code: they are are artifacts of TypeScript compilation and are intended to be packaged with the resulting JavaScript to provide a TypeScript interface. For more information, please see:
https://en.wikipedia.org/wiki/TypeScript#Declaration_files
Ticket: codeclimate/app#6343.

Exclude TypeScript `d.ts` files from analysis

---

Makefile

This dramatically increases test suite speed locally: we have one very
slow test that's valuable but fine to only run on CI or when you're
directly interested in it.

Exclude slow tests by default in `make test`

---

lib/cc/analyzer/engine_output.rb
spec/cc/analyzer/engine_output_spec.rb

Bad engine output should be treated as an engine error.

EngineOutput: catch invalid JSON

---

README.md

We updated this a while back but neglected the README

Fix default memory reference in README

---

.gitignore

We used to check this in, now that it's being pulled via `prepare` we
should ignore it.

Git ignore `base_rubocop.yml`

---

lib/cc/analyzer/formatters/json_formatter.rb
spec/cc/analyzer/formatters/json_formatter_spec.rb

Include `measurement` documents in JSON-formatted output.
After some consideration (prompted by discovering that the short-circuit
caused bug #782), this is now the intended behavior of the JSON
formatter.

Include `measurement` documents in JSON-formatted output

---

lib/cc/analyzer/statsd_container_listener.rb
spec/cc/analyzer/statsd_container_listener_spec.rb

We've had this on master for a long time, and I've found the lack of it
frustrating while monitoring QM. It's good to be able to distinguish
engine metrics by channel.
Shipping this will require adjusting a few charts/alerts, I'll do that
after shipping.

Include engine channels in metrics

---

lib/cc/analyzer/statsd_container_listener.rb
spec/cc/analyzer/statsd_container_listener_spec.rb

This reverts commit 68a912004984f678cc10666b3fb8504d22a7cab4.
Upstream in builder we fake other container steps as "engines" for
metrics tracking: I don't want to have to redo that many graphs & alerts
for changed metric names, and also don't think this is an appropriate
long term way to model the code. Reverting for now.

Revert "Include engine channels in metrics"

---

lib/cc/config/default_adapter.rb

Adding the common Go test pattern to our list of default exclude patterns.

Update EXCLUDE_PATTERNS to include **/*_test.go

---

spec/cc/analyzer/bridge_spec.rb

Added ```match_array()``` to ```include_path``` in this spec. Previously failing due to an ordering issue in these arrays.

Update bridge spec

---

lib/cc/analyzer/issue_validations.rb
lib/cc/analyzer/issue_validations/remediation_points_validation.rb
spec/cc/analyzer/issue_validations/remediation_points_validation_spec.rb
spec/cc/analyzer/issue_validations_spec.rb

We introduced a bug in duplication that incorrectly emitted negative
remediation points in some instances. We're fixing that bug, but we
should also validate issues more thoroughly to catch issues like this
earlier & prevent downstream issues.

Validate issue remediation points

---

config/engines.yml
lib/cc/config/default_adapter.rb
spec/cc/analyzer/bridge_spec.rb
spec/cc/cli/analyze_spec.rb
spec/cc/cli/engines/install_spec.rb
spec/cc/config/default_adapter_spec.rb

Now that QM fully rolled out, we no longer need the distinction between
QM duplication & non-QM duplication.

Use the stable branch of duplication by default again

---

lib/cc/cli/prepare.rb
lib/cc/cli/version_checker.rb
spec/cc/cli/prepare_spec.rb
spec/cc/cli/runner_spec.rb
spec/cc/cli/version_checker_spec.rb
spec/support/resolv_helpers.rb

This is one piece of support for HTTP proxies with the `fetch` directive in `.codeclimate.yml`.
`Net::HTTP` supports an `http_proxy` environment variable. It's convenient in some respects, but requires that `Net::HTTP` be directly instantiated with `#new`, as opposed to one of the alternate constructors like `.start` or `.get_response`.
For more, please see: https://www.jethrocarr.com/2014/08/14/ruby-nethttp-proxies/

Rewrite `Net::HTTP` calls to support `http_proxy`

---

Dockerfile
Makefile
spec/spec_helper.rb

We are currently on a 2015 release of Docker, and a relatively-old Ruby 2.2.x, based on [this Dockerfile][1]. 
This change switches to the official/library Ruby image, pinned to the latest/final release of 2.2, 2.2.10.
Something in that change no longer auto-loads the `tempfile` library, so I also added it explicitly to the spec_helper.
The `DOCKER_API_VERSION` environment variable is used to match the spec suite's requests against the CI server's version of the Docker daemon.
[1]: https://github.com/codeclimate/docker-alpine-ruby/blob/master/Dockerfile

Switch upstream Docker image to ruby:alpine

---

lib/cc/analyzer/engine.rb

This matters on newer versions of Docker, which no longer accept:
`docker run --memory "" foo`

Only pass `--memory` option to Docker if a memory limit is set.

---

Dockerfile

This also updates the image to Ruby v2.4.4, from v2.2.10.
```
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
codeclimate/codeclimate                         alpine              e22835391cc0        5 minutes ago       108MB
codeclimate/codeclimate                         latest              670535193ffc        20 hours ago        187MB
codeclimate/codeclimate                         0.73.0              7e8f7e46e8fc        13 days ago         98.3MB
```

Use `alpine` instead of `ruby` base image; 100MB vs. 180MB.

---

config/engines.yml

`codeclimate-rubocop` now supports up to version 0.57.2.

Add channels for Rubocop 0.55, 0.56, and 0.57.

---

Makefile

This is to ensure images will be built against an updated alpine that's
addressed the security issue discussed at
https://justi.cz/security/2018/09/13/alpine-apk-rce.html.

Always pull base image before building

---

.rubocop.yml
lib/cc/analyzer/container.rb
lib/cc/analyzer/formatters/plain_text_formatter.rb
lib/cc/analyzer/issue_validations/type_validation.rb
lib/cc/analyzer/measurement_validations/name_validation.rb
lib/cc/analyzer/measurement_validations/type_validation.rb
lib/cc/analyzer/measurement_validations/value_validation.rb
spec/cc/analyzer/container_spec.rb

I changed the rubocop target ruby version and made some changes to make `rubocop` happy.
I also disabled the `Style/FrozenStringLiteralComment` cop since there's ~300 offenses and adding the comment to the files isn't as straightforward since it either results in runtime errors or incorrect behavior (like fingerprint mismatches).
This should be merged together with https://github.com/codeclimate/codeclimate/pull/903

Bump rubocop ruby target

---

codeclimate.gemspec

`.ruby-version.yml` uses ruby 2.3. I assume this means the whole repository uses ruby 2.3 so I added it as a requirement to the gemspec.
This should be merged together with https://github.com/codeclimate/codeclimate/pull/902

Add required ruby version to gemspec

---

lib/cc/cli.rb

This changes the CODECLIMATE_DEBUG check to check if the environment
variable has a non whitespace character in it instead of just checking
if its set or not.
Just checking if it's set or not prevents doing things like `--env "CODECLIMATE_DEBUG=${CODECLIMATE_DEBUG:-$DEBUG}"` (since this results in `CODECLIMATE_DEBUG being set to an empty string).
Context: https://gitlab.com/gitlab-org/security-products/codequality/merge_requests/22
https://github.com/codeclimate/codeclimate/pull/902 and https://github.com/codeclimate/codeclimate/pull/903 should both be merged before this.

Check if CODECLIMATE_DEBUG is not blank

---

README.md

Most people aren't manually installing or running docker images, so that
section of install probably shouldn't go first: reading through the
README for the first time I'd expect new users to get more benefit
from first seeing the section their likely to need.
I also added a new "Setup" section about getting started using the tool
wtih a new project.

README updates - clarifying installation and setup

---

config/engines.yml

We previously removed it in error. Promoting it to stable while I'm at it.

Re-add Pylint to the CLI and promote to stable

---

.circleci/config.yml

Removing `Quality` context as it doesn't seem to be actually needed here and its presence prevents PRs from forked repos to be built.

Remove "Quality" context from circle config

---

README.md

Adds description to include that `install:engines` also checks for (and downloads) any new images for engines.

update description for install:engines

---

config/engines.yml

Created a new RuboCop channel to support the rubocop-airbnb plugin.  Because the plugin has strict dependencies that don't align with any existing channels I made an independent channel based on the latest version of rubocop-airbnb (3.0.2).
Branch: https://github.com/codeclimate/codeclimate-rubocop/tree/channel/rubocop-0-76-airbnb
Original request issue:https://github.com/codeclimate/codeclimate-rubocop/issues/131

add rubocop-0-76-airbnb channel

---

lib/cc/cli/prepare.rb
spec/cc/cli/prepare_spec.rb

When fetching an inaccessible file, we're printing the full response body, which in most of the situations will contain unnecessary data.
```
codeclimate prepare
Failed fetching http://169.254.169.254/latest/meta-data/local-hostnamex: code=404 body=&lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;lang=&quot;en&quot;&gt;
&lt;head&gt;
&lt;title&gt;404 - Not Found&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h1&gt;404 - Not Found&lt;/h1&gt;
&lt;/body&gt;
&lt;/html&gt;
```
https://codeclimate.atlassian.net/browse/QUA-543
- Removed the response body …

QUA-543: Don't include the response body when raising FetchError

---

config/engines.yml

This PR add `eslint-8` channel for [codeclimate-eslint](https://github.com/codeclimate/codeclimate-eslint) plugin
```yaml
plugins: 
eslint:
enabled: true
channel: "eslint-8"
```
Related PR: https://github.com/codeclimate/codeclimate-eslint/pull/569

Add eslint-8 channel for eslint plugin

---

lib/cc/cli/prepare.rb
lib/cc/config.rb
lib/cc/config/prepare.rb
spec/cc/config_spec.rb

This PR tells the Analyzer to ignore all files fetched in the `prepare` step of the build.
It does so by going through the prepare config in the `.codeclimate.yml` file and adding the paths to the `exclude_patterns` setting programmatically. This is done so no analysis is run on these files, and they don't appear in the `Code` tab in the user's dashboard.
Example:
In a project with this configuration:
The fetched files are saved in the codebase:
And they don't appear in the Code tab:
https://codeclimate.atlassian.net/browse/QUA-580

QUA-580: Don't analyze files fetched in the prepare step

---

config/engines.yml

Adds channels for RuboCop 1.30.0 and 1.31.0 to the engines configuration file.

Include RuboCop 1.30.0 and 1.31.0 in `config/engines.yml` (closes #1054)

---

lib/cc/analyzer/statsd_container_listener.rb

There are some clients of this gem, that don't use ruby 3.1 version, therefore they fail to interpret the hash syntax.

QUA-832: Do not use Ruby 3.1 hash syntax

---

lib/cc/engine_registry.rb

We need to add `plugin` to engine_registry.rb file in order to continue working on [this PR](https://github.com/codeclimate/codeclimate-ee/pull/776).

922: Add plugin to engine_registry.rb

---

config/engines.yml

@fede-moya since we are in the process of fixing the publish step to use a different flow and are doing releases manually, should I disable that in the CircleCI config just so the builds appear green?

add new channel for brakeman 5.4.1

---

config/engines.yml

When you try to use the new channel it will say it cannot find the image, forgot that we needed to add the prefix for the org in the image.

forgot to add the org to the image reference for brakeman-5-4-1

---

qlty-cli/src/commands/init.rs
qlty-cli/src/initializer/scanner.rs
qlty-cli/src/initializer/settings.rs
qlty-cli/tests/cmd/init/prefix.toml

Removes the `--with-prefixes` flag from `qlty init` and makes the behaviour for prefix during init default.

Make with prefixes default behaviour

---

qlty-cli/src/commands/coverage/publish.rs

Use default config options if qlty.toml is not present.

Do not require qlty.toml for coverage command

---

qlty-cli/src/commands/telemetry.rs
qlty-cli/src/logging.rs
qlty-cli/src/telemetry.rs
qlty-cli/src/telemetry/analytics.rs
qlty-cli/src/telemetry/segment.rs

- Prefer QLTY_LOG env var over `--debug` flag
- Rename references to Segment to analytics, since the protocol is used by other backends
- Remove superfluous separate telemetry log (we log in main log now)
- Simplify some telemetry code that got unnecessarily confusing due to foregrounds vs. background distinction

Prefer QLTY_LOG env var over `--debug` flag

---

qlty-check/src/cache.rs
qlty-check/src/planner/config_files.rs
qlty-config/src/config/plugin.rs

I noticed locally that in some cases that config files were being added to the cache key in a different order, which produces different cache results. I audited the cache key generation code for iteration and added explicit sorting to try to increase determinism.

Sort elements going into cache keys

---

qlty-check/src/planner/target_batcher.rs

If there is a driver that is batched by config with the config file in `.qlty/configs` directory the cache hit was being missed because the path for the config file was changed during batch computations and not reverted back to the original path of the file.

Fix cache hits for config batches

---

qlty-cli/src/upgrade.rs

Since wget is supported in the install script, do not rely on curl to download the script. Instead download via ureq.

 Support in-place upgrades and support non-curl systems

---

qlty-cli/src/commands/check.rs
qlty-cli/src/commands/coverage/publish.rs
qlty-cli/src/commands/coverage/transform.rs
qlty-cli/src/commands/metrics.rs
qlty-cli/src/commands/smells.rs

The JSON format is unstable and intended for internal use, so we don't want users to get impacted by depending on a format that changes out from under them.
We are tracking a feature proposal to add an output format for the SARIF standard [here](https://github.com/orgs/qltysh/discussions/1205), which will enable a stable machine-readable output format.

Hide JSON output flag

---

plugins/linters/hadolint/plugin.toml

The latest release of Hadolint is ~2 years old and it segfaults on MacOS Sequoia. To avoid auto-enabling a plugin that will produce an error, this moved Hadolint to only be auto-enabled if a Hadolint configuration file is already in the repository.
#1201

Don't automatically enable hadolint

---

qlty-cli/src/arguments.rs

These are not yet ready for prime time. h/t@ robbyrussell

Hide `auth` subcommand family from help output

---

.github/workflows/cli.yml
.github/workflows/cli_integration.yml
.github/workflows/plugins.yml
Cargo.lock
qlty-cli/src/telemetry.rs

There are a handful of unrelated changes in here, we'll see if this gets through CLI:
- Update Cargo.lock (was dirty locally)
- Replace abandoned actions-rs/toolchain with actions-rust-lang/setup-rust-toolchain
- Remove login to GHCR which was attempting to workaround a Trivy issue
- Bump Rust to 1.82.0 and fix warning related to deprecated `PanicInfo`

Authenticate Plugins GHA workflow with GITHUB_TOKEN

---

qlty-cli/src/commands/plugins.rs
qlty-cli/src/commands/plugins/disable.rs

Add plugins disable subcommand

Add plugins disable

---

qlty-cli/tests/cmd/init/network/basic.stdout

Seems like we missed a test somehow in https://github.com/qltysh/qlty/pull/1236, even though tests passed there.

Fix init test

---

qlty-config/src/config/plugin.rs
qlty-types/src/protos/qlty.analysis.v1.rs
qlty-types/src/protos/qlty.analysis.v1.serde.rs

Part 1.
These need to merged in sequence to prevent tests breakage or worse user issues.

Add secret and dependency alert categories

---

qlty-check/src/executor/invocation_result.rs
qlty-cli/tests/cmd/check/missing_output_as_error.in/.gitignore
qlty-cli/tests/cmd/check/missing_output_as_error.in/.qlty/qlty.toml
qlty-cli/tests/cmd/check/missing_output_as_error.in/sample.sh
qlty-cli/tests/cmd/check/missing_output_as_error.stderr
qlty-cli/tests/cmd/check/missing_output_as_error.stdout
qlty-cli/tests/cmd/check/missing_output_as_error.toml
qlty-config/src/config/plugin.rs

Related to https://github.com/qltysh/qlty/issues/1223

Add missing_output_as_error to DriverDef

---

qlty-check/src/planner/config.rs

This is an initial quick fix to get Windows compatibility when qlty.toml specifies semgrep. Platform support should ideally be configurable in the plugin spec.

Disable semgrep lints on Windows

---

qlty-check/src/parser/eslint.rs
qlty-check/src/patch_builder.rs
qlty-check/src/patcher.rs
qlty-check/src/processor.rs
qlty-cli/src/commands/patch.rs

Seed with some rules we do not "trust" to work reliably. Respects `--unsafe` flag.
Also fixes an eslint issue in converting char ranges to bytes for replacements.

Ignore unsafe rules from check --fix

---

plugins/linters/rubocop/plugin.toml

When initializing Qlty, if the `standard` Gem is found in the `Gemfile`, install it when installing Rubocop.

Support initializing running StandardRB run via Rubocop

---

qlty-check/src/parser/eslint.rs

Looks like the `start_byte` and `end_byte` can sometimes be beyond the end of the char indexes, so we need to hedge against that.

Avoid ESLint parser panic

---

qlty-analysis/src/workspace_entries/workspace_entry_finder_builder.rs
qlty-config/default.toml
qlty-config/src/config/language.rs
qlty-plugins/plugins/linters/biome/plugin.toml
qlty-plugins/plugins/linters/eslint/plugin.toml
qlty-plugins/plugins/linters/knip/plugin.toml
qlty-plugins/plugins/linters/oxc/plugin.toml

- Split `jsx` file type from `javascript`
- Add some missing extensions for CommonJS and ESM variants
- Behavior neutral: Maintain glob and interpreters for maintainability analysis independent of the file_types data.
I explored a few alternatives to the duplication and they all introduced subtle, confusing semantics so I just went with giving us full control for targeting maintainability independent from the file_types. This gives us the ability to tweak our targets without inadvertently affecting plugins and vice versa.

Fix up JavaScript file types

---

qlty-cli/src/commands/plugins/disable.rs
qlty-config/src/config/plugin.rs

- Changes behavior of the `qlty plugins disable PLUGIN` to set the plugin mode to `disabled` (instead of removing it from the qlty.toml)
- Adds a couple error checks: errors if no plugins in qlty.toml or if the plugin referenced in the command is not found in their qlty.toml (used `upgrade` command as reference)
Couple notes:
1. The conversion of `IssueMode` to a string duplicates the serialization macro strings (`#[serde(rename = "block")]` e.g.) defined in the struct itself. From what I could tell, if we want to avoid this duplication, we could either a) use `serde_json` to translate the IssueMode value to JSON, and then extract the string out of the JSON (yuck). Or, instead, remove these macros and define our own serialization, using the new `to_string` method defined. I'm less sure …

Set plugin `mode=disabled`(instead of removing whole plugin) when running `qlty plugins disable PLUGIN`

---

qlty-cli/src/commands/plugins/disable.rs
qlty-cli/src/commands/plugins/enable.rs
qlty-config/src/config/plugin.rs

Previously `qlty plugins disable PLUGIN` disabled a plugin by entirely removing the plugin definition from the `qlty.toml` file. In this world `qlty plugins enable PLUGIN` worked regardless of whether the plugin was never configured to begin with or was configured but removed with `qlty plugins disable PLUGIN`. 
This changed in #1315 when we changed the behavior of `qlty plugins disable PLUGIN` to instead mark the plugin as disabled (`mode = "disabled"`). Now, a `disabled` plugin differs from one never configured to begin with.  Because the `enable` subcommand was not "mode-aware" -- it assumed if the plugin was defined in the `qlty.toml`, regardless of its "mode", that it was enabled. This had the unfortunate user experience of informing a user that their plugin was already enabled when …

enhance `qlty plugins enable PLUGIN` to support enabling disabled plugins

---

qlty-check/src/executor/invocation_result.rs
qlty-cli/tests/cmd/check/missing_output_as_error.stdout
qlty-cli/tests/cmd/check/skip_errored_plugins.stdout
qlty-cli/tests/cmd/check/skip_errored_plugins_reports_other_failures.stdout

Shortens up paths we need to print to the terminal, creating more space

Move invocation files directly into out/ dir

---

qlty-check/src/parser/markdownlint.rs
qlty-plugins/plugins/linters/markdownlint/fixtures/__snapshots__/basic_v0.41.0.shot

- Cleanup rule keys
- Cleanup messages
- Emit at `medium` level not `fmt` -- Medium should be the default unless we have a reason to go up to high or down to low. Fmt should be for auto-formatter issues only

Adjust markdownlint output

---

qlty-plugins/src/lib.rs

Embedded sources was picking up toml files from node_modules directory when present.

Ignore node_modules from plugin source embedding

---

qlty-check/src/executor/driver.rs
qlty-cli/src/logging.rs

Before:
```
2024-12-19T17:20:19Z INFO [ThreadId(1)]::qlty_check::processor (6.7 MB): Processed results from 1 invocations in 0.17s
```
Now:
```
2024-12-19T17:20:19Z INFO [T1] qlty_check::processor (6.7 MB): Processed results from 1 invocations in 0.17s
```
Also remove some super verbose printing to debug level.

Shorten printing of ThreadId into log

---

qlty-cli/src/ui/format/text.rs

This is an intentionally boring refactor which is the first of a series of refactors to cleanup TextFormatter before we add more logic to it

Move TextFormatter outputs into struct

---

qlty-cli/src/commands/check.rs
qlty-cli/src/ui/format/errors.rs
qlty-cli/src/ui/format/text.rs

The Formatter trait is most useful for programatic output like JSON, NDJSON, Gzip, and Protos.
The usage for TextFormatter and ErrorsFormatter was buying us very little, and binding those concepts to confusing semantics now that the text "formatter" is interactive.
Now that we have disconnected TextFormatter and ErrorsFormatter from `trait Formatter`, I will look at renaming and re-organizing them.

Don't use Formatter trait for TextFormatter

---

qlty-config/src/config.rs
qlty-config/src/config/builder.rs

We have been supporting 2 different ways of defining sources in the `qlty.toml` configuration file:
```toml
[[source]]
name = "default"
default = true
```
```toml
[sources.default]
default = true
```
The HashMap version is considered legacy, and as we look to reference sources more, it will make our lives easier if we only support a single way of defining sources.
NB: The `default_source` method was unused and removed
By removing the hashmap sources definition, we may find a small number of customers who will no longer have a correctly defined source in their qlty.tom. In these scenarios, this is the error I see:
```
❌ Plugin definition not found for name: actionlint
```
Would be preferable, probably, to either:
1. Print an error saying that a source is not defined in the qlty.toml file …

Remove support for HashMap version of 'sources' key in qlty.toml

---

qlty-check/src/planner/driver.rs

In the case where one or more files was a cache hit, and one or more files were a cache miss, the Planner would plan an invocation for all files not just the uncached file. The result was duplicate issues for the cache hit files.

Fix duplicate issues bug on partial cache hit

---

qlty-cli/tests/cmd/check/missing_output_as_error.stdout

On Windows, the output string is quoted. On Mac and Linux, it is not. This snapshot hopefully works for both.

Attempt to fix Windows snapshot test

---

qlty-analysis/src/lang/ruby.rs
qlty-smells/src/metrics/metrics/cognitive.rs

In https://github.com/orgs/qltysh/discussions/1313 @nk-ty noted that `qlty` and `codeclimate` CLIs calculate the cognitive complexity of a method with trailing unless statements differently. After some investigation, I determined that both were incorrectly calculating cognitive complexity. This PR is concerned with the cognitive complexity calculation in qlty.
The following are equivalent ways of expressing an `if` conditional in Ruby:
```ruby
if !foo
puts "hi"
end
```
```ruby
unless foo
puts "foo"
end
```
```ruby
puts "hi" if !foo
```
```ruby
puts "hi" unless foo
```
The first was correctly being calculated. The second was an obvious oversight. And the 3rd and 4th ones were less obvious oversights (the parser calls them `if_modifier` / `unless_modifier` nodes not `if` / `unless` nodes. …

Categorize various flavors of `if` in Ruby as `if` nodes

---

.github/workflows/cli.yml
.github/workflows/plugins.yml
Cargo.lock

Run times for CLI/plugin tests on macOS and Ubuntu (Windows not changed-- failures are unrelated):
CLI (cli.yml):
* [ubuntu-latest-16-cores](https://github.com/qltysh/qlty/actions/runs/12588323414/job/35085973505#logs): 1m44s
* [ubuntu-latest](https://github.com/qltysh/qlty/actions/runs/12588501607/job/35086497825#logs): 1m42s
* [macos-15-xlarge](https://github.com/qltysh/qlty/actions/runs/12588323414/job/35085973271#logs): 3m42s
* [macos-15](https://github.com/qltysh/qlty/actions/runs/12588501607/job/35086497585#logs): 1m41s
Plugins (plugins.yml):
* [ubuntu-latest-16-cores](https://github.com/qltysh/qlty/actions/runs/12588323409/job/35085973461#logs): 5m45s
* [ubuntu-latest](https://github.com/qltysh/qlty/actions/runs/12588501606/job/35087704835#logs): 6m45s
* …

Update CLI runners

---

Cargo.toml

Related to #1386
Not sure if we explicitly need an arm64 host to build an arm64 linux  builds since Rust should be able to cross-compile across architectures (we explicitly already do this on macOS). I think it's worth validating this via a release with standard runners and have high confidence it would work.

Update CI runners for release builds

---

qlty-cli/src/commands/auth/login.rs
qlty-cloud/src/auth/mod.rs
qlty-cloud/src/lib.rs

If "" or "-" are provided, token is read from STDIN

Set token via `qlty auth login --token <TOKEN>`

---

.qlty/.gitignore
qlty-check/src/tool.rs
qlty-cli/src/commands/cache.rs
qlty-cli/src/commands/cache/prune.rs
qlty-cli/src/initializer/templates/gitignore.txt
qlty-config/src/library.rs

Uses the file MAC times to prune the results cache, logs, and outfiles. This is a fast-and-dumb approach rather than trying to analyze everything and figure out which results cache files are truly no longer needed.
Some filesystems may not track access times (`atime`) which provides visibility into cache reads, in which case it will fallback to modified time (`mtime`).
Also, adds a `plugin_cachedir` to the Library, to keep data cached by the plugins isolated from data that we cache. (In our cache, the Clippy plugin ends up with ~2 GB of "cache" which is really compilation artifacts.) Since we can't be sure of the impact of deleting some-but-not-all of a plugin's cached data, we delete it all.
- Enhance `cache prune` to have an argument for whether to clear the plugin caches or not, since …

Add `cache prune` subcommand

---

Makefile.toml

Don't need the extra `cli` directory in symlink source path.

Update Makefile symlink paths

---

.qlty/.gitignore
qlty-check/src/tool.rs
qlty-cli/src/initializer/templates/gitignore.txt

Use `plugin_cachedir` instead.
Fixes a configuration issue from #1408

Fix incorrect reference to `plugin_cache` directory

---

qlty-analysis/src/workspace_entries/args_source.rs

The walker attempts to strip the "root qlty directory" off of each path when iterating over args, but if the prefix does not match, the offending line unwraps a None option and panics.
This fixes the panic, although in general, the behavior for this situation is undefined (qlty does not support calling `check <path>` on paths that are not in the root qlty directory).
Ideally all path arguments should be validated and an error should be printed when an invalid path is found, but let's start by removing panics.

Fix panic when path for `qlty check <path>` is outside qlty directory

---

qlty-cloud/src/export/coverage.rs

Right now if someone has two coverage files with same name in different directories it throws the error: `invalid Zip archive: Duplicate filename`
Adding dir path to zip should prevent that while maintaining uniqueness in identifying files.
Reference: https://discord.com/channels/1256822430505373696/1308114848403685406/1328180907554766910

Allow raw coverage files with same name

---

qlty-check/src/parser/ripgrep.rs
qlty-plugins/plugins/linters/ripgrep/fixtures/__snapshots__/basic_v14.1.0.shot
qlty-plugins/plugins/linters/ripgrep/fixtures/__snapshots__/basic_v14.1.1.shot
qlty-plugins/plugins/scripts/updateLinterVersions.ts
qlty-plugins/plugins/tests/driver.ts
qlty-plugins/plugins/tests/runLinterTest.ts
qlty-plugins/plugins/tests/utils.ts

Ripgrep uses 0-indexed column values which is not used by other linter output

Fix off-by-1 offset in ripgrep column info

---

qlty-plugins/plugins/linters/kube-linter/plugin.toml

- Lint the entire directory all at once
- If kube-linter exits with a "success" exit code but no stdout, treat it as a Lint Error rather than invoking the parser (which would crash due to trying to parse a blank string)

Improvements to kube-linter plugin

---

qlty-cli/src/commands/coverage/publish.rs

Also support `--project-name` when it cannot be inferred by env/repo.
Lookup for project name is:
1. GITHUB_REPOSITORY
2. The last path component of the origin remote url in the active git repository
Note that workspace tokens can currently be specified by providing `--token qltcw_SOME_TOKEN/project_name` manually and this will continue to work, we just add `--project-name` for a more discoverable approach since the token format might be obfuscated (and not well documented).

Support workspace tokens by inferring and appending project name to token

---

.github/workflows/cli_integration.yml
.github/workflows/plugins.yml
qlty-check/src/tool/ruby/sys/macos.rs
qlty-check/src/tool/tool_builder.rs

Currently the `reek` plugin is failing for customers. The stack trace for these customers looks like this:
```
2025-01-22T18:03:07Z INFO [T13] qlty_check::tool (47.8 MB): Setting up tool reek@Some("6.3.0"). Logging to /home/runner/.qlty/cache/tools/reek/6.3.0-fb49277b68e3-install.log
2025-01-22T18:03:20Z ERROR [T13] qlty_check::tool (47.8 MB): Failed to get version for package "reek": Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "<internal:/home/runner/.qlty/cache/tools/ruby/3.3.0-bbe397d161fc/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': \n/home/runner/.qlty/cache/tools/reek/6.3.0-fb49277b68e3/gems/dry-types-1.8.1/lib/dry/types/sum.rb:33: anonymous block parameter is also used within block (SyntaxError)\n\tfrom …
```

Upgrade version of ruby from 3.3.0 => 3.3.7 (Do not merge)

---

Cargo.lock
Cargo.toml
qlty-config/Cargo.toml
qlty-config/src/bin/generate_schema.rs
qlty-config/src/config.rs
qlty-config/src/config/coverage.rs
qlty-config/src/config/download.rs
qlty-config/src/config/file_type.rs
qlty-config/src/config/ignore.rs
qlty-config/src/config/language.rs
qlty-config/src/config/overrides.rs
qlty-config/src/config/plugin.rs
qlty-config/src/config/release.rs
qlty-config/src/config/smells.rs
qlty-config/src/config/source.rs

This sounds counter-intuitive, but extensions and tools like [Taplo](https://taplo.tamasfe.dev/) ([Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml)) support validating TOML files with JSON schemas. This PR aims to provide the infrastructure to generate a JSON schema for use in these tools.
A schema file can be generated with
```sh
cargo run --bin qlty-config-generate-schema > schema.json
```
This PR does not generate the schema or use it anywhere yet.

Binary to generate qlty.toml validation schema using Taplo

---

qlty-coverage/src/parser/lcov.rs

If lcov is missing coverage data for a file, we are currently unwraping a None value, which causes a crash.
Example: https://discord.com/channels/1256822430505373696/1308114848403685406/1333383446483177603

Avoid unwrap error on empty lcov file data

---

qlty-cloud/src/export/analysis.rs
qlty-cloud/src/format.rs
qlty-cloud/src/format/json_each_truncated.rs

Sometimes invocations can have extremely large outputs (> 100 MB) which can lead to issues during build data ingestion.
This PR formats build invocations so that we omit any data going into stdout, stderr and tmpfile_contents if they are deemed above limit.

Omit large strings when formating invocations

---

Cargo.lock
qlty-cli/src/commands/init.rs

Right now we also run formatters during `qlty init` if user approves of sampling issues, which then prompts user to format files which can happen in a loop and often be confusing during initialization for a user.
I think the only way to avoid that is to skip running formatters at this stage.

Skip formatters when sampling issues during init

---

qlty-coverage/src/parser/jacoco.rs
qlty-coverage/tests/fixtures/jacoco/sample.xml

Some times the output from Jacoco parser can have missing line data, right now we error when that happens. This PR handles that scenario.

Fix Jacoco parser to not throw error when no lines for source file

---

qlty-coverage/src/parser/simplecov.rs
qlty-coverage/tests/fixtures/simplecov/sample-json.json

Some customers are reported to be using simeplcov-json gem to generate coverage report, which generates it differently from the current and legacy simplecov format that we current support, this PR adds support for simplecov-json format.
https://github.com/vicentllongo/simplecov-json

Add support for simplecov-json in simplecov parser

---

qlty-check/src/executor/invocation_result.rs
qlty-cli/tests/cmd/check/missing_output_as_error.in/.qlty/qlty.toml
qlty-config/src/config.rs
qlty-config/src/config/plugin.rs
qlty-plugins/plugins/linters/eslint/plugin.toml
qlty-plugins/plugins/linters/kube-linter/plugin.toml
qlty-plugins/plugins/linters/radarlint/plugin.toml

Prior to this PR, if a linter exited with a success exit code but did not produce any output, we would hand an empty string to the parser. In substantially all situations, this will result in a confusing EOF error from the parser, because it will try to e.g. parse an empty string as JSON.
This PR changes the default -- If a linter exits with a success exit code, but does not produce output, we will treat that as a Lint Error and skip the parser phase entirely.
This behavior can be overridden by two alternative behaviors: `parse` or `no_issues`. `parse` will invoke the parser with an empty string, and `no_issues` will treat the empty output as if it produced output along the lines of `issues = []`
(Previously, we had a `missing_output_as_error` boolean. The new `output_missing` enum …

Change default behavior for missing output

---

qlty-check/src/executor/driver.rs
qlty-cli/tests/cmd/check/prepare_script_fail.stderr

- Always log prepare_script stdout to info level, and stderr to warn level

Always log prepare script stdout and stderr

---

qlty-coverage/src/ci.rs
qlty-coverage/src/ci/semaphore.rs

Adds recognition of Semaphore environment variables so that when running `qlty coverage publish` from within a Semaphore environment, users do not have to specify `--override-*` command line arguments (instead those values are taken from the detected environment variables).

Support SemaphoreCI environment variables for auto-detection of coverage upload metadata

---

qlty-analysis/src/workspace_entries/workspace_entry_finder_builder.rs
qlty-check/src/planner/plugin_workspace_entry_finder_builder.rs

Right now if you apply a formatting change bubbled up from `qlty check` command while in a sub directory, the application fails with an `Result::unwrap() on an Err value`.
The root of that issue lies in the fact that when you apply the format this way, formatter is run with only selected file paths (which are project root relative and not relative to cwd) and TargetMode is set to Path when that happens. Instead of normalizing relative paths based on cwd I think just using absoluete paths is a better approach and less likely to cause any issues.

Fix path target mode when used in subdirectory 

---

qlty-check/src/executor/invocation_script.rs
qlty-config/src/config/plugin.rs
qlty-plugins/plugins/linters/phpstan/plugin.toml

Similar to eslint, phpstan config files also load dependencies relative to config file path, so we should copy the phpstan configs into tool directory where we install the packages.

Copy phpstan config into tool dir

---

qlty-cli/src/initializer/scanner/package_json.rs

This [sentry error](https://qltyai.sentry.io/issues/6252580916/?alert_rule_id=15048087&alert_type=issue&notification_uuid=068db895-9027-40d0-b651-d11059852fb2&project=4506888928493568&referrer=slack) has been popping up recent related to unwrap in extract_version_from_yarn_lock function so just replacing all of them.

Fix extract_version_from_yarn_lock unwrap errors

---

qlty-check/src/tool/ruby.rs
qlty-check/src/tool/ruby/sys/macos.rs

Small fix to ensure that arch is correctly extracted when version number path is parsed differently from version string (#1497)

tool(ruby): fix macos identification of arch with non-standard version numbering

---

qlty-cli/src/logging.rs

This PR is designed to clean up globset logging which is very noisy.
Notes:
1. This does not disable logs in `trace` mode, however these libraries will still log at their original level (not necessarily trace).
2. You can disable ext lib logging in trace mode by using setting `QLTY_LOG` to `qlty=trace` which will focus trace messages on qlty only.

Disable logging from log crate as it only applies to external libs

---

qlty-analysis/src/workspace_entries/diff_source.rs

Implementation was grabbing fs::metadata of the root directory instead of the actual file, returning the same metadata for every file causing cache issues.

Fix bug in DiffSource::build() file metadata calculation

---

qlty-plugins/plugins/linters/phpstan/plugin.toml

PHPStan configs often requiring tuning, so it is not a great candidate to be enabled by default

Auto-enable PHPStan only when config is found

---

Cargo.lock
qlty-check/Cargo.toml
qlty-check/src/cache.rs

Change heuristics to use mtime only when file is "dirty" in the git tree. If not dirty, use the git tree SHA instead, not mtime.

Update issue cache semantics for detecthing file changes

---

.github/workflows/plugins.yml
qlty-check/src/tool/php.rs
qlty-plugins/plugins/linters/gitleaks/plugin.toml
qlty-plugins/plugins/linters/php-codesniffer/plugin.toml
qlty-plugins/plugins/linters/phpstan/plugin.toml

Instead of using phar files like we have done so far, using composer to install php plugins seems to help remove certain compatibility issues when using extra packages.
Attempts to resolve compatibility issues with php-codesniffer and its extra optional standards.

Use composer to install php plugins

---

Cargo.lock
qlty-cli/src/initializer/scanner.rs

Right now if there 3 or more options for a prefix there is a chance an empty "" will be inserted as a prefix, which is undesirable, this PR fixes that.

Fix plugin prefix during init

---

Cargo.lock
qlty-cloud/Cargo.toml
qlty-cloud/src/export/coverage.rs
qlty-coverage/src/publish/upload.rs

Instead of uploading 4 separate files for coverage uploads, this uploads a single zip file containing the 4 files.
This cannot be merged until a server side component which knows how to read the single zip file is merged.

Compress files into a single coverage.zip and update upload logic accordingly

---

qlty-check/src/executor.rs
qlty-check/src/executor/invocation_result.rs
qlty-cli/tests/cmd/network/check/prefix.in/.gitignore
qlty-cli/tests/cmd/network/check/prefix.in/.qlty/qlty.toml
qlty-cli/tests/cmd/network/check/prefix.in/also_nested/needs_formatting.js
qlty-cli/tests/cmd/network/check/prefix.in/nested/needs_formatting.js
qlty-cli/tests/cmd/network/check/prefix.stderr
qlty-cli/tests/cmd/network/check/prefix.stdout
qlty-cli/tests/cmd/network/check/prefix.toml
qlty-cli/tests/cmd/network/fmt/prefix.in/.gitignore
qlty-cli/tests/cmd/network/fmt/prefix.in/.qlty/qlty.toml
qlty-cli/tests/cmd/network/fmt/prefix.in/also_nested/needs_formatting.js
qlty-cli/tests/cmd/network/fmt/prefix.in/nested/needs_formatting.js
qlty-cli/tests/cmd/network/fmt/prefix.stdout
qlty-cli/tests/cmd/network/fmt/prefix.toml

Right now path for formatters when using prefixes were not matching correctly causing issues during both check and fmt. 
This PR fixes that.

Fix fmt path issues with prefixes

---

qlty-check/src/tool.rs
qlty-check/src/tool/download.rs
qlty-check/src/tool/github.rs
qlty-check/src/tool/installations.rs
qlty-check/src/tool/php.rs
qlty-check/src/tool/php/composer.rs
qlty-check/src/tool/ruby/gemfile.rs
qlty-check/src/tool/ruby/sys/linux.rs
qlty-check/src/tool/ruby/sys/macos.rs
qlty-check/src/tool/ruby/sys/windows.rs

Found a few places where we were not writing out installation debug files.

Add missing installations

---

qlty-plugins/plugins/linters/stylelint/plugin.toml

Since the stylelint output always contains a valid json output we can update the output_missing to error so it doesn't give a parser error when output is missing.

Update output_missing to error for stylelint

---

qlty-check/src/tool/php.rs
qlty-check/src/tool/php/composer.rs

Thanks to visibility from debug files it seems previously we were retrying php installation process at least once for every php installation that had extra packages, this PR makes sure the composer.json file in php tool directory is correctly updated on first try and packages are correctly installed without needing a second try.

Update composer tool to install packages on first attempt

---

.qlty/qlty.toml
Cargo.lock
qlty-config/src/config/ignore.rs

Despite docs and qlty.toml's existing which would suggest otherwise, this syntax never worked:
```toml
[[ignore]]
rules = ["markdownlint/MD024"]
```
That would have needed to be written as:
```toml
[[ignore]]
tools = ["markdownlint"]
rules = ["MD024"]
```
This PR unlocks a clearer syntax:
```toml
[[ignore]]
rules = ["markdownlint:MD024"]
```

Fix handling of ignores with tools and rule keys

---

qlty-check/src/tool/ruby.rs
qlty-check/src/tool/ruby/gemfile.rs

Install a script that resets the `$LOAD_PATH` (`$:`) to move `RUBYLIB` paths out of the prepended values. Ruby has magical internal behavior that forces `RUBYLIB` to the front of `$LOAD_PATH` until it is modified (but not with `unshift` as discussed below). This is necessary because without this reset, the contents of `RUBYLIB` will always precede any load path adjustments by RubyGems, which forces builtin libraries to take precedence over the gemified counterparts. In other words, `require 'json'` will use the Ruby builtin version instead of the gem version.
A side benefit of this method is that we can remove the compiled in values (`/opt/hostedtoolcache/...`) that may cause red-herring load issues in the future.
This script is used in conjunction with `RUBYOPT=-rqlty_load_path` to …

ruby: fix loading of RUBYLIB in a gem-compatible way

---

qlty-plugins/plugins/linters/php-cs-fixer/fixtures/__snapshots__/multiple_files_v3.73.1.shot
qlty-plugins/plugins/linters/php-cs-fixer/fixtures/multiple_files.in/basic.php
qlty-plugins/plugins/linters/php-cs-fixer/fixtures/multiple_files.in/basic_too.php
qlty-plugins/plugins/linters/php-cs-fixer/plugin.toml

Batching with php-cs-fixer requires a config file to be present, we can either change suggested to "config" or disable batching.
Disabling batching will make it slower, but will give more value

Disable batching for php-cs-fixer

---

README.md

This patch updates the README to link directly to the `CONTRIBUTING.md` file on GitHub, making it easier to access.

docs: link `CONTRIBUTING.md` in README

---

Cargo.lock
Cargo.toml

Older versions of the config crate used rust-yaml which is no longer maintained. We are trying to get rid of all dependencies on rust-yaml in favor of rust-yaml2.
To finish off rust-yaml we need to deal with syntect, our syntax highlighter, which still uses it
https://github.com/trishume/syntect/pulls?q=is%3Apr+rust-yaml

Bump config

---

qlty-check/src/executor/driver.rs
qlty-check/src/executor/invocation_result.rs
qlty-check/src/tool.rs
qlty-check/src/tool/download.rs
qlty-check/src/tool/github.rs
qlty-check/src/tool/go.rs
qlty-check/src/tool/installations.rs
qlty-check/src/tool/java.rs
qlty-check/src/tool/node.rs
qlty-check/src/tool/php.rs
qlty-check/src/tool/php/composer.rs
qlty-check/src/tool/python.rs
qlty-check/src/tool/ruby.rs
qlty-check/src/tool/ruby/gemfile.rs
qlty-check/src/tool/ruby/sys/linux.rs
qlty-check/src/tool/ruby/sys/macos.rs
qlty-check/src/tool/ruby/sys/windows.rs
qlty-check/src/tool/ruby_source.rs
qlty-check/src/tool/rust.rs

This PR improves error handling throughout the codebase by replacing unwraps with proper error handling using the Result type.
1. ✅ Updated InvocationResult to handle env() errors by properly propagating them with context
2. ✅ Updated initialize_installation to return Result<Installation> and use the ? operator to return Err if tool.env() is an Err
3. ✅ Updated fn extra_env_vars to return Result<HashMap<String, String>>
4. ✅ Modified fn extra_env_vars in ruby.rs to treat errors from self.package_file_envs as fatal using the ? operator
The PR makes error handling more consistent throughout the codebase, ensuring that errors are properly propagated and displayed to the user with appropriate context.

Fix PHP tool unwrap calls

---

.qlty/qlty.toml
qlty-check/src/planner.rs
qlty-check/src/planner/driver.rs
qlty-check/src/planner/plugin.rs
qlty-check/src/planner/plugin_workspace_entry_finder_builder.rs
qlty-cli/tests/cmd/check/subdir_from_subdir.in/.gitignore
qlty-cli/tests/cmd/check/subdir_from_subdir.in/.qlty/qlty.toml
qlty-cli/tests/cmd/check/subdir_from_subdir.stdout
qlty-cli/tests/cmd/check/subdir_from_subdir.toml

This patch fixes `qlty check foo/` when in a subdirectory.
As part of this fix, I simplified the concurrency controls of the `workspace_entry_finder_builder`. Previously, it was an `Arc<Mutex<PluginWorkspaceEntryFinderBuilder>>` which I reduced to a simple `PluginWorkspaceEntryFinderBuilder` that is cloned.

Fix running `qlty check PATH` in a subdir

---

qlty-cli/src/initializer/templates/gitignore.txt

From my testing, the negated rule `!configs` does _not_ negate files within configs. I added `!configs/**` which seems to work

Change the default generate .gitignore

---

qlty-plugins/plugins/package-lock.json
qlty-plugins/plugins/package.json
qlty-plugins/plugins/scripts/updateLinterVersions.ts
qlty-plugins/plugins/tests/driver.ts
qlty-plugins/plugins/tests/runLinterTest.ts
qlty-plugins/plugins/tests/utils.ts

Now that we may not have a known good version snapshot we should test with the highest version snapshot available for linter version updates

Test against lastest snapshot

---

qlty-plugins/plugins/linters/bandit/fixtures/__snapshots__/basic_v1.7.8.shot
qlty-plugins/plugins/linters/bandit/fixtures/__snapshots__/basic_v1.7.9.shot
qlty-plugins/plugins/linters/golangci-lint/fixtures/__snapshots__/basic_new_v2.0.2.shot
qlty-plugins/plugins/linters/golangci-lint/fixtures/basic_new.in/.golangci.yml
qlty-plugins/plugins/linters/golangci-lint/fixtures/basic_new.in/basic.go
qlty-plugins/plugins/linters/golangci-lint/fixtures/basic_new.in/go.mod
qlty-plugins/plugins/linters/golangci-lint/plugin.toml
qlty-plugins/plugins/linters/pmd/fixtures/__snapshots__/apex_v7.0.0.shot
qlty-plugins/plugins/linters/pmd/fixtures/__snapshots__/batch_v7.0.0.shot
qlty-plugins/plugins/linters/pmd/fixtures/__snapshots__/hello_v7.0.0.shot
qlty-plugins/plugins/linters/reek/fixtures/__snapshots__/basic_v6.3.0.shot
qlty-plugins/plugins/linters/tflint/fixtures/__snapshots__/aws_nested_v0.51.1.shot
qlty-plugins/plugins/linters/tflint/fixtures/__snapshots__/aws_nested_v0.52.0.shot
qlty-plugins/plugins/linters/tflint/fixtures/__snapshots__/aws_v0.51.1.shot
qlty-plugins/plugins/linters/tflint/fixtures/__snapshots__/aws_v0.52.0.shot
qlty-plugins/plugins/scripts/updateLinterVersions.ts
qlty-plugins/plugins/tests/index.ts

1. Skip tsc since it doesn't have a test.
2. Add support for golangci-lint v2.
3. Normalize version numbers in documentation urls in test snapshots, simplifies upgrades for plugins such as tflint and bandit which have different version numbers in urls.

Fixes for issues created by update linter version workflow.

---

qlty-check/src/tool/node/package_json.rs
qlty-check/src/tool/php.rs
qlty-check/src/tool/php/composer.rs
qlty-check/src/tool/ruby/gemfile.rs

A common issue I have noticed in testing this is that if the version of the linter in the lockfile is specified to be different than in qlty.toml (often the default known_good_version) we get the version mismatch error during version check post tool install. 
Maybe we should skip version check in this case?

Copy lockfiles when no package_filters

---

qlty-check/src/tool/github.rs

osv-scanner 2.0.1 started to use a different content_type from the previous version:
* 1.9.0: `content_type: "application/octet-stream",`
* 2.0.1: `content_type: "application/x-msdownload",`
The GitHubRelease impl does not check for this content type, thus ignoring all Windows candidates.
The fix updates to no longer exclude these candidates. There is also a small refactor to perform a more reliable content type check for Windows install candidates.
Fixes #1934
Signed-off-by: Loren Segal <lsegal@soen.ca>

Fix detection of GitHub releases on Windows

---

qlty-check/src/executor/invocation_result.rs

This will keep them in the summary comment but avoid failing the `qlty check` status for them by default

Move inferred "fmt issues" to mode = comment

---

qlty-check/src/llm/fixer.rs

The stack trace is only partially helpful, potentially due to concurrency in this part of the code.
The panic error is `byte index 80 is not a char boundary` and my strong suspicion is that it comes from this line:
```rust
format!("{}...", &issue.message[..80])
```
The input `80` to the slice operator works is bytes not characters. If that byte location is not a character boundary, it panics.
Therefore, any unprotected string slice where the string is arbitrary content that may include multi-byte characters is a panic bug.

Fix panic: byte index 80 is not a char boundary

---

qlty-cli/src/commands/coverage/publish.rs
qlty-cli/tests/cmd/coverage/basic.toml
qlty-cli/tests/cmd/coverage/files_exist.stdout
qlty-cli/tests/cmd/coverage/files_exist.toml
qlty-cli/tests/cmd/coverage/ignore_patterns.toml
qlty-cli/tests/cmd/coverage/json.stdout
qlty-cli/tests/cmd/coverage/json.toml
qlty-cli/tests/cmd/coverage/overrides.stdout
qlty-cli/tests/cmd/coverage/overrides.toml

Prior to this PR, the coverage summary was hidden behind a `--summary` flag. This PR removes the argument and makes `--summary` a standard behavior.

Enable summary in coverage publish

---

qlty-cli/src/initializer/templates/qlty.toml
qlty-cli/tests/cmd/init/basic.stdout
qlty-cli/tests/cmd/init/config_based_multiple_versions.stdout
qlty-cli/tests/cmd/init/config_based_version_new.stdout
qlty-cli/tests/cmd/init/config_based_version_old.stdout
qlty-cli/tests/cmd/init/custom_source.stdout
qlty-cli/tests/cmd/init/package_file.stdout
qlty-cli/tests/cmd/init/package_file_gemfile.stdout
qlty-cli/tests/cmd/init/package_file_gemfile_lock.stdout
qlty-cli/tests/cmd/init/package_file_gemfile_with_gemspec.stdout
qlty-cli/tests/cmd/init/package_file_package_json.stdout
qlty-cli/tests/cmd/init/package_file_yarn_lock.stdout
qlty-cli/tests/cmd/init/prefix.stdout
qlty-cli/tests/cmd/init/skip_default_source.stdout

Often template files _look_ like files of type X but contain syntax that is invalid making them prone to parse errors

Add `**/templates/**` to default exclude patterns

---

qlty-check/src/tool/github.rs

Fixes #1926 (golangci-lint test failure)

windows: Ignore 32bit install binaries in GitHub releases

---

.qlty/.gitignore
qlty-cli/src/initializer/templates/gitignore.txt

Add `!.gitignore` to .gitignore template so it gets tracked and prevent vcs issues.

Prevent .qlty/.gitignore from ignoring itself

---

Cargo.toml
qlty-config/Cargo.toml
qlty-coverage/Cargo.toml

- Upgrade cargo-dist to 0.28.0
- Block qlty-config from being packaged into releases (it got pulled in because it has a `qlty-config-generate-schema` binary)
- Disable shell and powershell installer generation (we use our own)
- Also, fix `cargo machete` false positive

Upgrade cargo-dist to dist

---

Cargo.toml
qlty-config/Cargo.toml
qlty-coverage/Cargo.toml

Reverts qltysh/qlty#1974
Releases failing due to: `Error: The template is not valid. .github/workflows/cli_release.yml (Line: 201, Col: 14): A mapping was not expected` on "Install cargo-dist" step
https://github.com/qltysh/cloud/actions/runs/14743273682/job/41385731518

Revert "Upgrade cargo-dist to dist"

---

Cargo.toml
qlty-config/Cargo.toml
qlty-coverage/Cargo.toml

- Block qlty-config from being packaged into releases (it got pulled in because it has a qlty-config-generate-schema binary)
- Disable shell and powershell installer generation (we use our own)
- Also, fix cargo machete false positive

Release tweaks

---

qlty-cli/src/initializer/scanner.rs

Right now we would copy config file from plugin sources even if a different config file candidate already exists in repo (for plugins with multiple config file names). 
This PR changes that to check if any valid config files exist in repo, if so it skips copying config file from plugin source.

Fix: Don't install config files if any config file for the plugin is found

---

qlty-types/src/protos/qlty.tests.v1.rs
qlty-types/src/protos/qlty.tests.v1.serde.rs

Adds support for a new field `incomplete` to be serialized and sent over the wire for a new use case.

Add incomplete field for coverage metadata

---

qlty-plugins/plugins/linters/flake8/fixtures/__snapshots__/basic_v6.0.0.shot
qlty-plugins/plugins/linters/flake8/fixtures/__snapshots__/basic_v6.1.0.shot
qlty-plugins/plugins/linters/flake8/fixtures/__snapshots__/basic_v7.1.1.shot

These snapshots became out-of-date once we fixed the bug to copy linter configs, because the `.flake8` config file suddenly started to be copied (before, it was ignored).
I confirmed that flake8 passes the tests in main if the `.flake8` file is removed, so it's working fine.
This is a blind update of the snapshots to get CI working

Fix CI: Update flake8 snapshots

---

qlty-cli/tests/cmd/coverage/json.stdout

https://github.com/qltysh/qlty/pull/1999 introduced a change which broke this snapshot test, updating the snapshot.

Fix coverage test snapshot

---

qlty-check/src/tool.rs
qlty-check/src/tool/php.rs
qlty-check/src/tool/php/composer.rs
qlty-check/src/tool/ruby/gemfile.rs
qlty-check/src/tool/ruby/sys/macos.rs
qlty-check/src/tool/ruby/sys/windows.rs

Running duct::cmd::run() by default bails on non-zero exit codes, avoiding capture of any stderr. This change updates to run with `unchecked()` so that stderr can be captured into log files.
Due to this change, the specifics of Tool.run_command had to be updated to extract the original command for error display to maintain the original (somewhat helpful errors), as the Err object containing the command must now be synthesized manually (duct returned the err in the form `["program", "arg1", ...]` but this list of program/args is not available on the Expression object except via before_spawn).

Fix bubbling of stderr to tool install log files

---

Cargo.lock
qlty-cli/src/commands/coverage.rs
qlty-cli/src/commands/coverage/complete.rs
qlty-cli/src/commands/coverage/publish.rs
qlty-cli/src/commands/coverage/transform.rs
qlty-cli/src/commands/coverage/utils.rs
qlty-cloud/Cargo.toml
qlty-cloud/src/lib.rs
qlty-coverage/Cargo.toml
qlty-coverage/src/lib.rs
qlty-coverage/src/publish/settings.rs
qlty-coverage/src/publish/upload.rs
qlty-coverage/src/token.rs

Intended to help support a new server-side aggregation model where client sends partial reports (with --incomplete) and then sends, at the end of the build, a `qlty coverage complete` to inform qlty.sh that the build has finished sending parts.
Some notes:
It takes a subset of the arguments that `qlty coverage publish` takes. Here's the current arguments:
Some arguments `qlty coverage publish` takes that `qlty coverage complete` does not:
--dry-run (only relevant when uploading coverage)
--format <FORMAT> (only relevant when uploading coverage)
--override-build-id <OVERRIDE_BUILD_ID> (this one I'm on the fence about ... `qlty coverage publish` actually _requires_ this argument, but I don't think it's necessary for this server side aggregation algorithm
--add-prefix (only relevant when …

Add a `qlty coverage complete` sub-command

---

qlty-coverage/src/formats.rs
qlty-coverage/src/utils.rs

Right now for absoluete paths on windows i-e `D:/a/qlty-action/qlty-action/coverage/coverage/clover.xml` We run into error because it assume `D` must be a format

Fix coverage format specification for absolute paths on Windows

---

.github/workflows/cli_integration.yml
qlty-check/src/tool/ruby/sys/linux.rs

This avoids the need for a preflight check and allows a hands-off sandboxed approach to Ruby installs.
Obviates #2007

ruby(linux): Install libyaml as dependency in binary install

---

qlty-check/src/tool.rs
qlty-check/src/tool/php.rs
qlty-check/src/tool/php/composer.rs
qlty-check/src/tool/ruby.rs
qlty-check/src/tool/ruby/gemfile.rs
qlty-check/src/tool/ruby/sys/linux.rs
qlty-check/src/tool/ruby/sys/macos.rs
qlty-check/src/tool/ruby/sys/windows.rs

We don't currently support binary builds on musl platforms (alpine, etc). Force ruby-build for these platforms.
Note that the system will need the following dependencies for a successful build (packages list for apk):
```sh
apk add -U bash perl gcc make openssl-dev musl-dev zlib-dev yaml-dev
```
For this reason, it might actually be easier to eventually support some kind of `QLTY_FEATURE_RUBY_USE_SYSTEM` opt-in for these types of setups, as it would be much simpler to `apk add -U ruby` than all of the above, and once we're depending on system deps, we've already broken the sandbox.

ruby(linux): disable binary builds on musl platforms

---

qlty-check/Cargo.toml
qlty-check/src/tool.rs
qlty-check/src/tool/ruby.rs
qlty-check/src/tool/ruby/sys/macos.rs

We need gmp, libyaml, and openssl in order to install Ruby on any macOS system. This pre-flight check (ported from #2007) validates that the libraries are installed via Homebrew.
This PR also adds this check for x86_64 architectures, as well as disables retries for the Ruby tool installer. If we don't disable retries, this (slow) check will be run 3+ times (9 total brew checks).
Note that an improvement of this approach would be to simply request permission from the user to install these libraries instead of exiting. This could be implemented as a follow-up.

ruby(macos): add preflight dependency checks to Ruby binary install

---

qlty-check/src/tool.rs

Version command output was being hidden from error making it unnecessarily difficult to understand a failure. This PR shows the output on failure providing much faster determination of an error. Example for Ruby (before applying #2028):
Before:
```
> Error installing ruby@3.4.2.
>
>     See more: /Users/loren/.qlty/cache/tools/ruby/3.4.2-6e382f1c8049-install.log
>
> Caused by:
>     Failed to get version for package "ruby": (command sh -c "ruby --version" exited with code 0)
```
After:
```
> Error installing ruby@3.4.2.
>
>     See more: /Users/loren/.qlty/cache/tools/ruby/3.4.2-6e382f1c8049-install.log
>
> Caused by:
>     Failed to get version for package "ruby": (command sh -c "ruby --version" exited with code 6)
>
>     dyld[96492]: Library not loaded: …
```

Display version command on failure for user debuggability

---

qlty-cli/src/commands/coverage/complete.rs
qlty-cloud/src/lib.rs
qlty-coverage/src/publish/upload.rs

Necessary / helpful for local development when you want to point the QLTY API to localhost.

Centralize API URL retrieval and allow overriding with env var

---

qlty-cli/src/commands/coverage/complete.rs

I also added a section header before printing the response information. Note the below is slightly inaccurate -- it says "MARKING COMPLETE ... " now.

Print the report URL after the complete command runs

---

.qlty/qlty.toml
qlty-check/src/tool/rust.rs

The version will not reliably match a specific numeric when using channels (since versions can change arbitrarily).
There's an open question about how cache keys should be handled in this situation (how do we detect that "nightly" is out of date?), but I think the existing behavior will also keep cache around and only fail once the tool cache is cleared, so technically this does not change existing caching behavior.

rust: skip version check when using a version channel

---

qlty-plugins/plugins/linters/radarlint-php/plugin.toml
qlty-plugins/plugins/linters/radarlint-python/plugin.toml
qlty-plugins/plugins/linters/radarlint-ruby/plugin.toml
qlty-plugins/plugins/linters/radarlint-scala/plugin.toml

- Only enable RadarLint for Ruby when a RadarLint config is found
- Fix bug where we did not correctly set `suggested_mode = "comment"` for RadarLint

Only enable RadarLint for Ruby when a RadarLint config is found

---

qlty-check/src/executor.rs
qlty-check/src/executor/staging_area.rs
qlty-cli/tests/cmd/check/exported_config_files.in/.gitignore
qlty-cli/tests/cmd/check/exported_config_files.in/.qlty/qlty.toml
qlty-cli/tests/cmd/check/exported_config_files.in/config-exporter/config.yml
qlty-cli/tests/cmd/check/exported_config_files.in/config-exporter/results.txt
qlty-cli/tests/cmd/check/exported_config_files.in/config-exporter/source.toml
qlty-cli/tests/cmd/check/exported_config_files.in/config-exporter/subdir/config.alternate.yml
qlty-cli/tests/cmd/check/exported_config_files.in/results.txt
qlty-cli/tests/cmd/check/exported_config_files.in/sample.sh
qlty-cli/tests/cmd/check/exported_config_files.stderr
qlty-cli/tests/cmd/check/exported_config_files.stdout
qlty-cli/tests/cmd/check/exported_config_files.toml
qlty-config/src/config/plugin.rs
qlty-config/src/sources/source.rs

This change allows plugins to package and declare exported configuration files using the syntax below:
```toml
[plugins.definitions.some-plugin]
exported_config_paths = ["relative/path/to/config.yml", "other/config.alternate.yml"]
```
Declaring an exported configuration allows a configuration file to be automatically included at runtime as a fallback default if no other configuration files are present or detected by the workspace (including `.qlty/configs` directory). The configuration file will be symlinked just like any other configuration. 
Users who want to opt out of automatic importing of configuration files can either:
1. Define a default configuration file in their workspace source tree (or `.qlty/configs`), or,
2. Override the `plugins.definitions.<plugin>.exported_config_paths` …

Package and export configuration files from plugins

---

Cargo.lock

GHA builds are failing due to a linker issue, this was resolved by https://github.com/rust-lang/jobserver-rs/pull/110

windows: fix build by updating jobserver dependency.

---

Cargo.toml

- enable `proxy-from-env` feature for ureq so HTTP(S)_PROXY settings are honored
- `cargo check --locked --all --offline`

Enable proxy support in ureq downloads

---

qlty-check/src/tool/download.rs

This pull request refactors the `Download` implementation in `qlty-check/src/tool/download.rs` to improve error handling by using the `anyhow::Context` trait. The changes enhance the clarity and specificity of error messages throughout the file download, decompression, and extraction processes.
* Replaced generic error handling with `anyhow::Context` to provide detailed error messages for failures in operations such as downloading files, creating files, copying data, and setting permissions. [[1]](diffhunk://#diff-c0681f617e1bcbddc5e9a53b56fc70b035cdf67e0fe73b69089ab65d749191e8L127-R158) [[2]](diffhunk://#diff-c0681f617e1bcbddc5e9a53b56fc70b035cdf67e0fe73b69089ab65d749191e8L155-R238) [[3]](diffhunk://#diff-c0681f617e1bcbddc5e9a53b56fc70b035cdf67e0fe73b69089ab65d749191e8L247-L257)
* …

Better error messages for downloads

---

qlty-check/src/planner.rs
qlty-cli/src/commands/install.rs
qlty-types/src/protos/qlty.analysis.v1.rs
qlty-types/src/protos/qlty.analysis.v1.serde.rs

There were more than a few things different between the tool installation process in qlty install (which was more barebones) and qlty check which was more comprehensive. 
One of which was managing package_files and filters properly causing qlty install to not work as intended in many instances.
This PR aims to make them behave similar as possible while minimizing avoidable duplication.

Make qlty install more context aware and inline with check

---

Cargo.lock
Cargo.toml
qlty-config/Cargo.toml
qlty-config/src/sources/git_source.rs

This allows `qlty install` to respect the global (or repo specific) credential manager / redirect rules that may be needed when fetching.
Fixes the following bug:
```
▶ qlty install
ERROR   
> Failed to fetch base refspecs from remote origin https://github.com/some/private_repo
> 
> Caused by:
>     remote authentication required but no callback set; class=Http (34); code=Auth (-16)
```
When using a source:
```toml
[[source]]
name = "custom"
repository = "https://github.com/some/private_repo"
branch = "main"
```

GitSource: use auth-git2 during fetch to use credential configuration from gitconfig

---

qlty-check/src/planner/driver.rs
qlty-check/src/planner/invocation_directory.rs
qlty-check/src/planner/target_batcher.rs

Since the computation for invocation directory is done in planning phase before files are staged (in the executor phase). 
Advanced directive like runs_from target_directory was not functioning as intended.

Fix formatter invocation directory when runs from target_directory

---

qlty-cli/src/commands/coverage/publish.rs
qlty-cli/tests/cmd/coverage/files_exist.stderr
qlty-cli/tests/cmd/coverage/files_exist.stdout
qlty-cli/tests/cmd/coverage/json.stdout
qlty-cli/tests/cmd/coverage/overrides.stdout
qlty-coverage/src/publish/processor.rs
qlty-coverage/src/publish/report.rs
qlty-coverage/src/validate.rs

Currently if any file coverages are ignored there is no way to communicate that leading to confusion among customers and support alike. 
This PR adds log line when coverage files are ignored.

Add log for ignored coverage paths

---

qlty-check/src/patch_builder.rs
qlty-check/src/planner.rs
qlty-check/src/planner/plugin_tab_column_width_transformer.rs
qlty-check/tests/fixtures/planner/patch_builder/parse.05.input.sh
qlty-check/tests/fixtures/planner/patch_builder/parse.05.output.txt
qlty-check/tests/fixtures/planner/plugin_tab_column_width_transformer/parse.01.input.sh
qlty-check/tests/fixtures/planner/plugin_tab_column_width_transformer/parse.01.output.txt
qlty-config/src/config/plugin.rs

https://github.com/qltysh/qlty/issues/2073
So it seems Shellcheck adds 8 to the column for every tab (\t) char which we need to adjust for. 
Unfortunately can't be done in parser since we don't have access to file contents at that point, so instead had to do this hackaround in the patch builder.
Fixes #2100

fix: shellcheck considers tabs as 8 columns in location ranges

---

Cargo.lock
qlty-cli/tests/cmd/config/migrate/no_match.stderr
qlty-cli/tests/cmd/config/migrate/no_match.stdout
qlty-cli/tests/cmd/config/migrate/no_match.toml
qlty-config/src/migration/prepare.rs

fix: Warn instead of error in `config migrate` if we can't find a plugin for a fetch item

---

qlty-analysis/src/workspace_entries/workspace_entry_finder_builder.rs

Fixes the issue when git in detached mode (happens when gitlab initialise project):
```
... [some gitlab runner initialisation phase]
Getting source from Git repository
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/some-reponame-tests/.git/
Created fresh repository.
Checking out 3bd76a7f as spike-test-qlty-component...
...
$ git status
HEAD detached at 3bd76a7
$ echo "Initializing project with Qlty..."
Initializing project with Qlty...
$ qlty init --no || echo "Already initialized"
› Initializing qlty in the current directory...
✔ Created .qlty/ directory
Plugin        Version     Targets   Config
checkov       known_good  6 files   
yamllint      known_good  1 files   .yamllint.yaml
markdownlint  known_good  1 files   
trufflehog    known_good …
```

fix: support head diff mode for `qlty smells`

---

Dockerfile

This resolves the connection error when reaching out to the API endpoint:
```
Transport Error: https://qlty.sh/api: Transport { kind: ConnectionFailed, message: Some("tls connection init failed"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("qlty.sh")), port: None, path: "/api/coverage", query: None, fragment: None }), source: Some(Custom { kind: InvalidData, error: General("No CA certificates were loaded from the system") }) }
```

fix: Add ca-certificates to Docker image

---

qlty-plugins/plugins/linters/eslint/plugin.toml

ESLint fails when TypeScript config is used with: 
```
Value for 'config' of type 'path::String' required.  You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.eslint  Error  Exited with code 2 in 0.20s  .qlty/out/invoke-sEJm5a.yaml
```
Because it generates wrong command: 
```
script: sh -c "eslint --config  --output-file /tmp/invocation-out-sEJm5a.txt --format json src/'"
```
The config parameter is missing. 
Ideally If config is not found it should not include --config parameter at all. The current fix adds support for TypeScrtipt ESLint
Issue: https://github.com/qltysh/qlty/issues/1542

fix: ESLint plugin is missing support for TypeScript eslint configuration (eslint.config.ts)

---

qlty-cli/src/commands/githooks/install.rs

Previously the lack of output for `qlty githooks install` was a bit disconcerting. I like seeing some form of output, if reasonable, to provide confidence that the command succeeded. And it seems reasonable to print out what it actually did.

Add output after installing githooks

---

installer/install.sh

fixes #2241
- Updates the zsh configuration path in install.sh to respect the `$ZDOTDIR` environment variable
- Uses the pattern `"${ZDOTDIR%/:-$HOME}"/.zshrc` instead of hardcoded `$HOME/.zshrc`
- Maintains backward compatibility by falling back to `$HOME` when `$ZDOTDIR` is not set
The installer script hardcoded the zsh configuration file path to `$HOME/.zshrc`, which doesn't work for users who have customized their zsh configuration directory using the `$ZDOTDIR` environment variable.
Updated the zsh configuration path to use `"${ZDOTDIR%/:-$HOME}"/.zshrc` which:
- Uses `$ZDOTDIR/.zshrc` when the variable is set (removing any trailing slash)
- Falls back to `$HOME/.zshrc` when `$ZDOTDIR` is not set or empty
- Follows standard shell practices for handling directory environment variables

fix: honor ZDOTDIR environment variable in install.sh

---

qlty-cli/src/commands/coverage/publish.rs

Accepts (but for now does nothing) with a `--no-validate` option (current behavior is to not validate by default)

chore: Introduce no-validate option for safe deploy of GitHub Action

---

qlty-coverage/src/ci.rs
qlty-coverage/src/ci/github.rs
qlty-coverage/src/publish/planner.rs

Currently, when coverage publish is run as part of a merge_group build, the reference_type is being reported as `branch` instead of `merge_group`. This fixes it by checking the type of the event if the CI provider is GitHub.

chore: specify reference_type as merge group when run as part of a merge_group build

---

qlty-coverage/src/ci/buildkite.rs

BuildKite returns the string "false" for the environment variable `BUILDKITE_PULL_REQUEST` if a build is not pull request related. We need to specifically detect this string to ensure we don't interpret it as a PR number.

fix: Ensure 'false' is not interpreted as a pull request number from BuildKite's environment

---

qlty-check/src/planner/config_files.rs
qlty-cli/tests/cmd/check/driver_script_config_file_interpolation.in/.qlty/qlty.toml

Fix regression from https://github.com/qltysh/qlty/pull/2416
Affects cache should not be part of plugin_configs as those are used for driver script interpolation. 
Serendipitously the release action failed and it did not affect any users, noticed it when my local fmt did not show issues. https://github.com/qltysh/qlty/actions/runs/18167950643

fix: plugin configs not to include affects cache
