Gemfile.lock, lib/cc/cli/runner.rb
=> Default to safe loading everywhere within the CLI

config/engines.yml
=> Add PHP code sniffer engine

.codeclimate.yml
@codeclimate/review This PR adds engines to .codeclimate.yml in this repository.
=> update .codeclimate.yml to use rubocop

DEVELOPERS.md
Added as a separate file to keep the README targeted at end-users.
=> Add DEVELOPERS.md

lib/cc/analyzer/engine.rb
/cc @codeclimate/review ping @noahd1
=> Add statsd probes for engine timeouts

lib/cc/analyzer/engine.rb
This runs engines as `app` instead of `root`.
**NOTE: Do not merge this until all the engines are updated:**
- bundler-audit: https://github.com/codeclimate/codeclimate-bundler-audit/pull/2
- coffeelint: https://github.com/codeclimate/codeclimate-coffeelint/pull/1
- csslint: https://github.com/codeclimate/codeclimate-csslint/pull/3
- eslint: https://github.com/codeclimate/codeclimate-eslint/pull/11
- gofmt: https://github.com/codeclimate-community/codeclimate-gofmt/pull/1
- golint: https://github.com/codeclimate-community/codeclimate-golint/pull/1
- govet: https://github.com/codeclimate-community/codeclimate-govet/pull/1
- phpcodesniffer: https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/6
- rubocop: …
=> Run engine as app user

DEVELOPERS.md, Makefile
Expand the individual commit messages for more details.
=> Remove unused make task, expand deployment docs

lib/cc/analyzer/engine.rb
/cc @codeclimate/review @pbrisbin
=> Kill threads on timeout

lib/cc/cli/analyze.rb, spec/cc/cli/analyze_spec.rb
This is an attempt to fix: https://github.com/codeclimate/codeclimate/issues/60
=> Apply all arguments to analyze command.

Gemfile.lock, codeclimate.gemspec, spec/cc/analyzer/engine_output_filter_spec.rb
=> Update cc-yaml to get new checks node support

.rubocop.yml, lib/cc/analyzer.rb, lib/cc/analyzer/config.rb, lib/cc/analyzer/engine.rb, lib/cc/analyzer/engine_registry.rb, lib/cc/analyzer/engines_runner.rb, lib/cc/analyzer/formatters/formatter.rb, lib/cc/analyzer/path_patterns.rb, lib/cc/cli.rb, lib/cc/cli/analyze.rb, spec/cc/analyzer/engine_registry_spec.rb, spec/cc/analyzer/engine_spec.rb, spec/cc/analyzer/engines_runner_spec.rb, spec/cc/analyzer/path_patterns_spec.rb, spec/cc/cli/analyze_spec.rb
- Extract EnginesRunner
- Remove unused EngineProcess autoload
- Engine accepts non-string json configuration
- Sharable PathPatterns class
- Support dev_mode directly in EngineRegistry
=> Extract shareable classes, improve interfaces

lib/cc/analyzer/path_patterns.rb, spec/cc/analyzer/path_patterns_spec.rb, spec/spec_helper.rb
See in-line comment (added there for greater visibility) for details.
Opening for visibility, will merge on green.
=> Call Glob#value if pattern is that class

Gemfile.lock, codeclimate.gemspec
Gives us the config key
Diff: https://github.com/codeclimate/codeclimate-yaml/compare/v0.2.0...v0.2.3
=> Update codeclimate-yaml to 0.2.3

lib/cc/cli/analyze.rb
=> Change into the filesystem dir before running engines

Gemfile, Gemfile.lock, lib/cc/analyzer/engines_runner.rb, spec/cc/analyzer/engines_runner_spec.rb, spec/cc/analyzer/path_patterns_spec.rb, spec/spec_helper.rb, spec/support/file_system_helpers.rb
Ended up with free time in a pairing interview and decided to work on this.
/cc @codeclimate/review @brynary
=> Read exclude paths from .gitignore if present

bin/check
- Docker recently changed the output of the `docker version` command
=> Add support for new docker version output

DEVELOPERS.md, bin/release
Automates steps originally outlined in DEVELOPERS.md
Relies on https://github.com/codeclimate/homebrew-formulae/pull/16, used to
release v0.2.11.
=> Add bin/release

config/engines.yml
@brynary, I'm not sure what needs to be done to publish the docker image for codeclimate-phpmd.  But once that is done I think this will work.
=> Add phpmd engine

lib/cc/analyzer/include_paths_builder.rb, spec/cc/analyzer/include_paths_builder_spec.rb
=> Don't follow symlinks while building include_paths.

config/engines.yml
=> Add foodcritic and scss-lint engines

codeclimate.gemspec
These are needed in the gemspec by Bundler for binstubs.
=> Add executables to gemspec.

config/engines.yml
=> Add requiresafe

lib/cc/analyzer/container.rb, spec/cc/analyzer/container_spec.rb
One more step in trying to make our stack easier to develop and debug.
=> Container raises BlankImage exception if passed a blank string.

config/engines.yml
This adds support for the duplication engine.
=> Add duplication engine to engines.yml

config/eslint/.eslintrc
=> Enable ESLint complexity check by default

.codeclimate.yml, .rubocop.yml, Rakefile, codeclimate.gemspec, lib/cc/analyzer/config.rb, lib/cc/analyzer/container.rb, lib/cc/analyzer/engine.rb, lib/cc/analyzer/engine_registry.rb, lib/cc/analyzer/engines.rb, lib/cc/analyzer/engines_runner.rb, lib/cc/analyzer/filesystem.rb, lib/cc/analyzer/formatters.rb, lib/cc/analyzer/formatters/formatter.rb, lib/cc/analyzer/formatters/json_formatter.rb, lib/cc/analyzer/formatters/plain_text_formatter.rb, lib/cc/analyzer/source_buffer.rb, lib/cc/cli/analyze.rb, lib/cc/cli/command.rb, lib/cc/cli/config.rb, lib/cc/cli/engines/install.rb, lib/cc/cli/engines/list.rb, lib/cc/cli/help.rb, lib/cc/cli/init.rb, lib/cc/cli/runner.rb, lib/cc/cli/version.rb, lib/file_utils_ext.rb, spec/spec_helper.rb
This PR updates the rubocop configuration to the CC default and updates most of the low-hanging fruit to conform to the enforced rules.
=> Update rubocop configuration with CC default

config/engines.yml
@codeclimate/review @jpignata @mrb
=> add brakeman to manifest

Gemfile.lock, codeclimate.gemspec, lib/cc/analyzer/engines_builder.rb, lib/cc/cli/config_generator.rb, lib/cc/cli/init.rb, lib/cc/cli/upgrade_config_generator.rb, spec/cc/cli/config_generator_spec.rb, spec/cc/cli/init_spec.rb, spec/cc/cli/upgrade_config_generator_spec.rb, spec/cc/cli/validate_config_spec.rb, spec/support/proc_helpers.rb
* include newer cc/yaml for better error messages
* validate existing config before upgrading
* if config is not valid, emit errors & exit with status 1
Next step is `builder`.
Thoughts, @codeclimate/review?
=> better config upgrade behavior

config/engines.yml
* always end with a period
* some descriptions were just the engine name: I've tried to write
better descriptions for these.
=> consistent & improved engine descriptions

bin/prep-release
gh is deprecated: prefer hub if installed, but still support gh for
those who have it
=> pre-release: use hub, not gh

Gemfile.lock, codeclimate.gemspec
Diff:
https://github.com/codeclimate/codeclimate-yaml/compare/v0.4.0...v0.5.0
Will merge on green
=> Bump codeclimate-yaml

lib/cc/cli/test.rb
There was a :bug:, it is no more.
=> Say something

.gitignore, Gemfile, Gemfile.lock, circle.yml, spec/spec_helper.rb
=> Add test coverage reporting

lib/cc/cli/test.rb
Certain engines in the Code Climate Platform require analysis in take place within the context of a directory. One good example is the brakeman engine which expects the context of a Ruby on Rails application.
This commit updates the CLI test command to iterate over the engine specification's `test_paths`, extract all assertion markers within the directory, and pass the entire test directory to the engine.
Another side effect of this change is fewer shell outs to `codeclimate analyze` which should speed things up overall.
=> Pass test directories instead of test files to engines

bin/prep-release
=> Fix compare link in release PR description

Makefile
Handy for local dev.
Small tweak, @codeclimate/review
=> add `make image` task

lib/cc/analyzer/engine.rb
A possible fix for #245 e #246.
=> Delete temporary file after the engine has ran.

lib/cc/cli/init.rb, spec/cc/cli/init_spec.rb
We use "config" all over the place here, but don't clarify if we're
talking about our own config or the config files for engines or what.
Just trying to neaten up a bit.
cc @pbrisbin
=> Refactor some names in Init

.codeclimate.yml, .rubocop.yml
* Disable the Rails/Output rule -- this isn't a Rails app
* Turn on the FIXME engine
=> Tweak CodeClimate Analysis Config

lib/cc/analyzer/engine_output.rb, spec/cc/analyzer/engine_output_spec.rb
=> Remove characters added by docker logging daemon

config/engines.yml
The images are released for this now.
=> Add vint engine

config/rubocop/.rubocop.yml
Update RuboCop configuration for changes between 0.35.1 and
0.37.2.
=> RuboCop configuration updates

config/engines.yml
This engine is ready to be added as available.
=> Add Reek engine

config/engines.yml
https://github.com/pbrisbin/codeclimate-gnu-complexity
=> Add GNU Complexity engine

config/engines.yml
https://github.com/jpignata/codeclimate-markdownlint
=> Add markdownlint engine

codeclimate-wrapper, lib/cc/analyzer/container.rb, lib/cc/analyzer/engine.rb
=> Persist some ad-hoc debugging that proved useful

config/engines.yml
=> Add ShellCheck engine definition

bin/release
Update the marketing site & deploy it when we deploy CLI.
This is step 2.
=> Update CLI on site when releasing

Makefile
=> Some Makefile improvements

Gemfile.lock, codeclimate.gemspec, lib/cc/analyzer/engine_registry.rb, lib/cc/cli/runner.rb, spec/cc/cli/engines/list_spec.rb, spec/spec_helper.rb
This closes https://github.com/codeclimate/codeclimate/issues/375
=> Remove safe yaml

Makefile
=> Rm non-existent task from Makefile PHONY

lib/cc/analyzer.rb, lib/cc/analyzer/issue_location_format_validation.rb, lib/cc/analyzer/issue_other_locations_format_validation.rb, lib/cc/analyzer/issue_validator.rb, spec/cc/analyzer/engine_spec.rb, spec/cc/analyzer/issue_location_format_validation_spec.rb, spec/cc/analyzer/issue_other_locations_format_validation_spec.rb, spec/cc/analyzer/issue_validator_spec.rb
Make sure that they match the formats outlined in the spec:
https://github.com/codeclimate/spec/blob/master/SPEC.md#locations
=> Add validations for location and other_locations

ISSUE_TEMPLATE.md
Not really a template, but a convenient place to show about-to-report users:
- Some common reasons for not reporting Issues
- Guidelines for reporting Issues
/cc @codeclimate/review @codeclimate/copy
=> Add Issue template

lib/cc/analyzer/engine.rb
This allows us to monitor and track engine channels separately.
=> Use engine name + channel in logs, container name, and metrics

lib/cc/workspace.rb, lib/cc/workspace/exclusion.rb, spec/cc/workspace/exclusion_spec.rb, spec/cc/workspace_spec.rb
This allows negated exclude patterns, [similar to git's behavior](https://git-scm.com/docs/gitignore#_pattern_format).
=> Allow negated exclude patterns

ISSUE_TEMPLATE.md
=> Add a note to update before reporting an issue

lib/cc/analyzer/container.rb, spec/cc/analyzer/container_spec.rb
When we kill containers due to resource limitations (usually time), we give the
docker-kill and docker-wait commands two minutes to complete. If they don't
complete in time, this exception occurs, halts the general shutdown process,
and ultimately bubbles up as an opaque exception (or U10 error) to the user.
It's better to rescue this experience and let the shutdown process continue as
it was, which will result in a more meaningful exception (or E-class error) to
the user.
A "zombie" container will still be left running, but by recording and viewing
the added metrics, we can identify a repeat offender (e.g. a particularly
un-killable engine) and address that problem at its root.
=> Rescue POSIX::Spawn::Timeout when killing containers

lib/cc/analyzer/container.rb
If an engine container runs away and our docker-kill/wait does not succeed,
this waitpid2 can block forever. To address this we put it in an
immediately-joined thread. We kill this thread as part of #stop. If the child
had exited, the kill will be a no-op. Otherwise, it will allow builder to move
on without waiting forever.
=> Put waitpid2 in a thread, so we can kill it on #stop

ISSUE_TEMPLATE.md
=> Add information about using as a gem

.codeclimate.yml, lib/cc/analyzer/formatters/formatter.rb, lib/cc/analyzer/formatters/html_formatter.rb, lib/cc/analyzer/formatters/plain_text_formatter.rb, lib/cc/analyzer/issue_validations/content_validation.rb, lib/cc/analyzer/issue_validations/path_existence_validation.rb, lib/cc/analyzer/issue_validations/path_is_file_validation.rb, lib/cc/analyzer/issue_validations/path_presence_validation.rb, lib/cc/analyzer/issue_validations/relative_path_validation.rb, lib/cc/analyzer/issue_validations/type_validation.rb, lib/cc/analyzer/issue_validations/validation.rb
- Support maintainability of code base and dog-food engine.
- Fix duplication issues
=> Enable duplication

Gemfile, Gemfile.lock, Makefile, circle.yml, spec/spec_helper.rb
Testing changes to https://github.com/codeclimate/ruby-test-reporter/ /c @pbrisbin
=> Update to use new style ruby test reporter

circle.yml
This needs to be available to people who are not contributors to the repo
@codeclimate/review @mrb
=> Add test coverage token to the circle.yml

config/engines.yml
Longer term, I wonder if it makes sense to keep this registry up to date with available channels, or to attempt to install and analyze with them as a docker tag indiscriminately.
=> Add beta channel for duplication engine

Gemfile.lock, codeclimate.gemspec
Includedes dependencies config
=> Update codeclimate-yaml to 0.10.0

config/engines.yml
repo: https://github.com/gilbarbara/codeclimate-stylelint
author: https://github.com/gilbarbara
=> Add beta channel for stylelint engine

Gemfile.lock
includes a bugfix for bubbling errors
=> bump codeclimate-yaml to 0.10.1

Gemfile.lock
bugfix for invalid URIs in dependency config.
=> update to cc-yaml 0.10.3

lib/cc/cli.rb, lib/cc/cli/dependencies.rb, lib/cc/cli/help.rb, lib/cc/resolv.rb, spec/cc/cli/dependencies_spec.rb, spec/cc/resolv_spec.rb, spec/support/resolv_helpers.rb
This adds a new command called `dependencies`, which will process entries in the `dependencies.files` key & download files.
cc @codeclimate/review this is mostly the same code, just tweaked a bit, but review would be appreciated!
=> Add dependencies command

lib/cc/cli/prepare.rb
=> Fix the dir that prepare command runs in

config/engines.yml
CodeScan: Code Climate Engine for Salesforce.com Apex, Visual Force, Aura and Lightning.
https://bitbucket.org/villagechief/codeclimate-codescan
=> Add CodeScan engine with beta channel

Gemfile, Gemfile.lock, solano.yml, spec/cc/analyzer/container_spec.rb, spec/spec_helper.rb
Reverting merge made by mistake 
Reverts codeclimate/codeclimate#542
=> Revert "Test branch"

config/engines.yml
=> Add Flog as beta engine

lib/cc/analyzer/formatters/html_formatter.rb, lib/cc/analyzer/formatters/templates/html.erb, spec/cc/analyzer/formatters/html_formatter_spec.rb
* Design matching web reports
* Code syntax highlighting
* Offending lines highlighting
* Code block expansion
* Filtering
* Duplication instances
* Extended descriptions (when available)
Reports can get pretty big. This iteration is tested with over 400 issues in the report. It loads to a usable state in under a second in Firefox, Chrome and Safari.
Code highlighting is done when code block first time enters view. Layout is also optimized for minimum reflows during loading. Filtering is also snappy (under 300ms in Firefox).
---
Related issue: #541
=> Update HTML formatter to better match Web version

config/engines.yml
Just happened to notice this while catching up on my emails
=> Fix typo in flog config

config/engines.yml
Add beta channel for [TSLint engine][].
[TSLint engine]: https://github.com/tkqubo/codeclimate-tslint
=> Add TSLint beta channel

lib/cc/cli/help.rb, spec/cc/cli/help_spec.rb
I hit a NoMethodError while running what turns out to be a nonsense
command: `codeclimate help --no-check-version`
=> Add nil check

config/engines.yml
haml-lint: https://github.com/michaelherold/codeclimate-haml-lint
proselint: https://github.com/dblandin/codeclimate-proselint
=> Add haml-lint and proselint beta engines to manifest

lib/cc/analyzer/engines_runner.rb, lib/cc/cli/analyze.rb
This is never raised: it got replaced by `ImageRequired`.
=> Remove unused exception

lib/cc/analyzer/engine.rb, lib/cc/cli/analyze.rb, lib/cc/config.rb, lib/cc/config/engine.rb, lib/cc/config/yaml.rb, spec/cc/config/yaml_spec.rb
- Log the written /config.json (DEBUG)
- Don't write an empty configuration to /config.json
- Load configuration in /code working directory
For https://github.com/codeclimate/app/issues/4447
=> Add CC::Config::YAML

README.md, lib/cc/cli/version_checker.rb
I think more people are going to upgrade if we tell them how.
=> Direct users to README for upgrade instructions

lib/cc/cli/version_checker.rb
We want to be able to keep track of requests from the CLI
=> Set custom user agent for version check requests

config/engines.yml
Addresses https://github.com/tkqubo/codeclimate-tslint/issues/24
=> Pull beta-tagged tslint image

lib/cc/analyzer/engine_output_filter.rb, lib/cc/analyzer/issue_validations/location_format_validation.rb, lib/cc/analyzer/source_extractor.rb, spec/cc/analyzer/engine_output_filter_spec.rb, spec/cc/analyzer/issue_spec.rb, spec/cc/analyzer/issue_validations/location_format_validation_spec.rb, spec/cc/analyzer/issue_validator_spec.rb, spec/cc/analyzer/source_extractor_spec.rb
See the commit messages for more context.
=> More-thoroughly validate location, avoid error when inferring fingerprint

lib/cc/cli/analyze.rb, spec/cc/cli/analyze_spec.rb
It was documented but wasn't implemented.
=> Add long form --format support

lib/cc/config/json.rb, spec/cc/config/json_spec.rb, spec/cc/config_spec.rb
... and update spec behavior to reflect config changes from
https://github.com/codeclimate/app/pull/5053.
=> Send QM config to duplication

config/engines.yml
- bump `stable` to latest `master`
- create a `beta` channel using the newest parse-server work.
=> Bump structure engine tags

lib/cc/analyzer/issue.rb, spec/cc/analyzer/issue_spec.rb
In conformity with Code Climate
[SPEC](https://github.com/codeclimate/spec/blob/master/SPEC.md#issues)
=> Map deprecated severity normal to minor

config/engines.yml
https://github.com/kmewhort/git.legal-codeclimate
https://docs.codeclimate.com/v1.0/docs/git-legal
=> Add git-legal engine to engines manifest

config/engines.yml
=> Add punctuation to the git-legal engine description

.codeclimate.yml, bin/check, bin/prep-release, bin/release, bin/validate-release
- Enable shellcheck engine
- Use `id --user` for posix shell compatibility
- Wrap variables in quotes
- Use printf
- Extract pre-release checks
- Use git fetch / reset instead of pull
=> Update release scripts

config/engines.yml
Related PR codeclimate/codeclimate-eslint#308
=> Add eslint-4 channel

Gemfile.lock, codeclimate.gemspec, lib/cc/cli.rb
I noticed that active support released this fix in 5.1.3
(https://github.com/rails/rails/commit/62c2aa9ce193e6c83f96c30d93c21c7abc5100b8),
so I think it's worth upgrading
=> Remove a temporary patch

lib/cc/analyzer/bridge.rb, lib/cc/config/engine.rb, lib/cc/config/engine_set.rb, lib/cc/config/validation/engine_validator.rb, lib/cc/config/yaml_adapter.rb, spec/cc/analyzer/bridge_spec.rb, spec/cc/config/engine_set_spec.rb, spec/cc/config/engine_spec.rb, spec/cc/config/validation/yaml_spec.rb, spec/cc/config/yaml_adapter_spec.rb
Added a small spec for `Bridge` as well since we didn't have one.
=> Respect engine specific excludes when running the engine

config/engines.yml
codeclimate/codeclimate-rubocop#109
=> Add Rubocop 0.51 Cahannel

lib/cc/config/validation/engine_validator.rb, lib/cc/config/validation/file_validator.rb, lib/cc/config/validation/yaml.rb, lib/cc/config/yaml_adapter.rb, spec/cc/config/validation/yaml_spec.rb, spec/cc/config/yaml_adapter_spec.rb
We saw these edge cases pop up on a few repos recently.
Best reviewed as individual commits, I think.
=> Some config fixes, focused on legacy exclude_paths

lib/cc/analyzer.rb, lib/cc/analyzer/engine_output.rb, lib/cc/analyzer/formatters/formatter.rb, lib/cc/analyzer/formatters/html_formatter.rb, lib/cc/analyzer/formatters/json_formatter.rb, lib/cc/analyzer/formatters/plain_text_formatter.rb, lib/cc/analyzer/measurement.rb, lib/cc/analyzer/measurement_validations.rb, lib/cc/analyzer/measurement_validations/name_validation.rb, lib/cc/analyzer/measurement_validations/type_validation.rb, lib/cc/analyzer/measurement_validations/validation.rb, lib/cc/analyzer/measurement_validations/value_validation.rb, lib/cc/analyzer/measurement_validator.rb, lib/cc/analyzer/validator.rb, spec/cc/analyzer/engine_output_spec.rb, spec/cc/analyzer/formatters/json_formatter_spec.rb, spec/cc/analyzer/issue_validator_spec.rb, spec/cc/analyzer/measurement_spec.rb, spec/cc/analyzer/measurement_validations/name_validation_spec.rb, spec/cc/analyzer/measurement_validations/type_validation_spec.rb, spec/cc/analyzer/measurement_validations/value_validation_spec.rb, spec/cc/analyzer/measurement_validations_spec.rb, spec/cc/analyzer/measurement_validator_spec.rb
See spec changes at https://github.com/codeclimate/spec/pull/59, first engine usage at https://github.com/codeclimate/codeclimate-structure/pull/289
=> Measurement document support

config/engines.yml
Promoting TSlint plugin to stable.
=> Promote TSlint to stable

config/engines.yml
- Update some description copy to match app counterpart
- Ensure all plugin descriptions end with a period
=> Cleanup plugin descriptions

lib/cc/config/validation/engine_validator.rb, lib/cc/config/validation/json.rb, lib/cc/config/validation/yaml.rb, spec/cc/config/validation/json_spec.rb, spec/cc/config/validation/yaml_spec.rb
=> Validation tweaks

Gemfile, Gemfile.lock, Makefile, circle.yml
change Gemfile, Makefile, and circle.yml to use new test reporter
=> setup-cc-test-reporter

config/engines.yml
https://github.com/codeclimate/codeclimate-rubocop/pull/112
=> Add Rubocop 0.52 channel

config/engines.yml
The engine is not used by anyone.
=> Drop Rubocop 0.35 engine

lib/cc/config/default_adapter.rb
This is a common pattern for Swift repos.
=> Adds Tests/ to default excludes

config/engines.yml
=> Add SwiftLint to Code Climate CLI

lib/cc/analyzer/statsd_container_listener.rb, spec/cc/analyzer/statsd_container_listener_spec.rb
In re: https://github.com/codeclimate/codeclimate/issues/838 and https://github.com/codeclimate/codeclimate/pull/766
=> Report per-channel metrics for engines that support channels.

bin/prep-release, bin/release
See https://github.com/codeclimate/codeclimate/pull/848 for previous discussion.
=> Use `/bin/bash` shebang for non-POSIX shell scripts.

Gemfile
See https://github.com/codeclimate/codeclimate/pull/848 for previous discussion.
=> Alphabetize gem dependency list.

.codeclimate.yml
See https://github.com/codeclimate/codeclimate/pull/848 for previous discussion.
=> Switch to Rubocop 0.57.x, fix fixme's exclusion config.

codeclimate-wrapper
See https://github.com/codeclimate/codeclimate/pull/848 for previous discussion.
=> Correct `shellcheck` issues in the bin wrapper script.

README.md
Codeclimate prepare
```
$ codeclimate help
prepare
```
=> Codeclimate prepare

config/engines.yml
- codenarc: https://docs.codeclimate.com/docs/codenarc
- sass-lint: https://docs.codeclimate.com/docs/sass-lint
- scalastyle https://docs.codeclimate.com/docs/scalastyle
=> Add codenarc, sass-lint, and scalastyle plugins

config/engines.yml
- Remove beta channels
- Add missing stable plugins
=> Update plugins manifest

config/engines.yml
codeclimate-bandit is a new plugin: https://github.com/noqcks/codeclimate-bandit/
=> Add bandit plugin

config/engines.yml
Re: https://github.com/codeclimate/codeclimate-rubocop/issues/137
=> Add v0.59.0 channel to Rubocop engine

config/engines.yml
re: https://github.com/codeclimate-support/escalations/issues/631#issuecomment-498848027
=> Add channel/rubocop-0-71

Gemfile.lock
Resolve [CVE-2020-8165](https://github.com/advisories/GHSA-jppv-gw3r-w3q8)
=> Patch rake to 12.3.3

.circleci/config.yml, .circleci/shared.bash, README.md
Add pipeline on _circleci_ to publish new versions when `VERSION` has been modified on `master`.
=> Set deploy pipeline

Gemfile.lock, codeclimate.gemspec, spec/cc/analyzer/engine_spec.rb
Address [CVE-2020-8165](https://groups.google.com/g/rubyonrails-security/c/bv6fW4S0Y1c)
=> Minor update on activesupport

config/engines.yml
=> Add missing codeclimate-rubocop engine channels

lib/cc/engine_registry.rb
Related Jira Tickets:
https://codeclimate.atlassian.net/browse/QUA-921
https://codeclimate.atlassian.net/browse/QUA-920
=> add release_info and channel_versions to CC::EngineRegistry::EngineDetails

.github/workflows/cli.yml, .github/workflows/cli_integration.yml, .github/workflows/plugins.yml
The emojis were fun but have become a pain, simplify this for utility.
=> Simplify GHA workflow names

qlty-check/src/parser/golangci_lint.rs
Fix for missing case in https://github.com/qltysh/qlty/pull/1145
=> Update Golangci parser to handle delete only suggestions

qlty-cli/src/commands/plugins/enable.rs
Slight cleanup and added some tests.
Also I was thinking of addressing the warning on enable [docs](https://docs.qlty.sh/cli/commands/plugins-enable) 
> Currently, the command does not consider whether the plugin may already be enabled.
But not sure if we should ignore plugins that are already activated
=> Update enable plugins and add tests

qlty-cli/src/commands/plugins.rs, qlty-cli/src/commands/plugins/upgrade.rs
https://github.com/qltysh/qlty/issues/1221
=> Add plugins upgrade

qlty-check/src/parser/clippy.rs
https://github.com/qltysh/qlty/issues/1225
=> Handle clippy build failure

qlty-cli/src/commands/completions.rs, qlty-cli/src/errors.rs, qlty-cli/src/shell.rs
Downgrade this from a panic to a command error which will cause the CLI to exit non-zero.
=> Avoid panic for unknown shell

plugins/linters/eslint/plugin.toml
This should fix https://github.com/qltysh/qlty/issues/1223
=> Add missing_output_as_error to eslint

qlty-analysis/src/lang.rs, qlty-cli/tests/lang/go/basic.in/boolean_logic.go, qlty-cli/tests/lang/go/basic.in/parameters.go, qlty-cli/tests/lang/go/basic.stdout, qlty-smells/src/structure/checks/parameters.rs
https://github.com/qltysh/cloud/issues/2823
=> Fix Go parameters count

qlty-check/src/parser/ruff.rs
There is a chance in case of i-e syntax error, that Ruff issue will not have a code or url.
=> Allow Ruff missing rule code

qlty-cli/src/telemetry.rs
We are getting some confusing values of `true`, so this should help clear that up
=> Adjust logic for Environment property

qlty-analysis/src/code/visitor.rs
Suggested fix for https://github.com/qltysh/qlty/issues/1277
=> fix(cli): Prevent stack overflow on deeply nested expressions

qlty-plugins/plugins/linters/biome/plugin.toml
Biome supports more file types than the current plugin define.
https://biomejs.dev/internals/language-support/
=> feat(plugin/biome): add more file types to biome plugin

qlty-plugins/plugins/plugin_guide.md
=> Plugin development guide expansion

qlty-check/src/executor.rs
Tested locally and works as expected
=> Stop running invocations when total MAX_ISSUES is exceeded

qlty-check/src/parser/hadolint.rs, qlty-check/src/parser/markdownlint.rs, qlty-plugins/plugins/linters/markdownlint/fixtures/__snapshots__/basic_v0.41.0.shot
Fmt is reserved for issues we _infer_ based on formatter changes.
=> Move plugin issues from level fmt to low

qlty-check/src/report.rs, qlty-cli/src/commands/check.rs, qlty-cli/src/lib.rs, qlty-cli/src/success.rs, qlty-cli/tests/cmd/check/multiple_drivers.stderr, qlty-cli/tests/cmd/check/override.stderr, qlty-cli/tests/cmd/check/pass_fail.stderr, qlty-cli/tests/cmd/check/regex_category_level.stderr, qlty-cli/tests/cmd/check/root_or_parent_with_config.stderr, qlty-cli/tests/cmd/check/skip_errored_plugins_reports_other_failures.stderr, qlty-cli/tests/cmd/check/timeout.stderr
=> Add unformatted files count to `qlty check` output

plugins
Not used for any functionality (I _think_!)
=> Remove plugins/ symlink from root

plugins
=> Revert "Remove plugins/ symlink from root"

qlty-check/src/planner/driver.rs, qlty-cli/src/commands/build.rs, qlty-cli/src/commands/check.rs, qlty-cli/src/commands/check/autofix.rs, qlty-cli/src/commands/fmt.rs, qlty-cli/src/ui/format.rs, qlty-cli/src/ui/format/text.rs
This PR is a bit of a grab bag of CLI improvements I made when running down the duplicate issue bug. The main addition is `--no-fix`. It also includes some improvements to output.
=> Add `--no-fix` option to `qlty check`

qlty-check/src/tool.rs
https://github.com/qltysh/qlty/issues/1334
=> Add log path to error if it exists

qlty-config/default.toml, qlty-config/src/config.rs, qlty-smells/src/duplication/planner.rs
https://github.com/qltysh/qlty/issues/1298
=> Fix language duplication filter patterns

qlty-cli/src/commands/check.rs
https://github.com/qltysh/qlty/issues/1335
=> Fallback to upstream when remote commit not present locally

Cargo.lock, Cargo.toml, qlty-cloud/Cargo.toml, qlty-cloud/src/auth/auth_flow.rs, qlty-cloud/src/auth/mod.rs
Experiment using tiny-http instead of actix-web to implement #1368
=> Re-implement auth login flow (#1368) with tiny-http

qlty-check/src/executor.rs, qlty-check/src/planner.rs, qlty-check/src/planner/config.rs, qlty-check/src/planner/plan.rs, qlty-cli/src/commands/install.rs
Had to do a bit of refactoring and introduce some input only functions to prevent code duplication.
=> Update qlty install to install all enabled plugins

.github/workflows/plugins.yml, Cargo.lock
- Changes to the plugins
- Changes to the qlty-config crate which contains the config schema
- Changes to the `tool` module in qlty-check which contains the runtimes and package manager code
=> Selective test execution for plugin tests

qlty-check/src/llm/fixer.rs
@lsegal I _think_ this patch is behavior equivalent. Since we are specifying the JSON input for the API literally in the code, and using the `json!` macro already, I took it all the way and it allowed slimming down the code by eliminating these serialization structs.
Note: I do think the serialization structs are useful for typing, but only if they are generated from the API specification. So I would be inclined to revisit this down the road once we iterate our approach for client SDK generation.
=> Use json! macro to avoid value structs

qlty-cloud/src/export/coverage.rs
Fixes path for raw_files https://github.com/qltysh/example-go/actions/runs/12729229047/job/35480765331
Need to push out a release after merging this.
=> Fix coverage raw_files path

.qlty/.gitignore, qlty-cli/src/initializer/templates/gitignore.txt
See https://github.com/qltysh/qlty/pull/1417#issuecomment-2587943374 for motivation
=> Gitignore .qlty/* by default and use exclusions for better future proofing

qlty-cli/tests/cmd/coverage/basic.in/.qlty/qlty.toml, qlty-cli/tests/cmd/coverage/basic.toml, qlty-cli/tests/cmd/coverage/ignore_patterns.in/.qlty/qlty.toml, qlty-cli/tests/cmd/coverage/ignore_patterns.toml, qlty-cli/tests/cmd/coverage/json.in/.qlty/qlty.toml, qlty-cli/tests/cmd/coverage/json.toml, qlty-cli/tests/cmd/coverage/overrides.in/.qlty/qlty.toml, qlty-cli/tests/cmd/coverage/overrides.toml
Update tests to cover change in https://github.com/qltysh/qlty/pull/1194
=> Update coverage tests to run without qlty config

qlty-check/src/issue_muter.rs
Add support for Dockerfiles, markdown, json, and other non-code linters
Also enable detection for commented lines (necessary for some linters that generate an issue on the comment line)
=> Fix qlty-ignore directive on unknown source files

qlty-analysis/Cargo.toml, qlty-check/Cargo.toml, qlty-cloud/Cargo.toml, qlty-config/Cargo.toml, qlty-coverage/Cargo.toml, qlty-plugins/Cargo.toml, qlty-smells/Cargo.toml, qlty-test-utilities/Cargo.toml, qlty-types/Cargo.toml
https://qltysh.slack.com/archives/C074X3BSVMJ/p1738002393623199?thread_ts=1738001741.951139&cid=C074X3BSVMJ
=> Remove license-file.workspace = true from cargo.toml

qlty-coverage/src/publish/upload.rs
https://github.com/qltysh/cloud/issues/5353
=> Improve coverage token error handling

qlty-check/src/executor/invocation_result.rs, qlty-cli/tests/cmd/check/missing_output_as_error.in/.qlty/qlty.toml, qlty-config/src/config.rs, qlty-config/src/config/plugin.rs, qlty-plugins/plugins/linters/eslint/plugin.toml, qlty-plugins/plugins/linters/kube-linter/plugin.toml, qlty-plugins/plugins/linters/radarlint/plugin.toml
=> Revert "Change default behavior for missing output"

qlty-cli/src/ui/fixes.rs, qlty-cli/src/ui/text.rs, qlty-cli/src/ui/unformatted.rs
Update print_unformatted() to only prompt if apply_mode == Ask
=> Fix qlty check always asking to format

qlty-cli/src/commands/check.rs, qlty-cli/src/commands/fmt.rs, qlty-cli/src/ui/fixes.rs, qlty-cli/src/ui/text.rs, qlty-cli/src/ui/unformatted.rs
This retains important settings like `--no-progress` and other relevant values.
=> Pass settings through to unformatted fix loop to retain settings

qlty-coverage/src/parser/qlty.rs
Right now if a qlty coverage file is uploaded with files with no hits, we error, this PR handles that.
Example, if someone transforms a coverage file which includes coverage for files without any line hits and tries to upload the qlty format file generated they will get an error right now.
=> Handle missing hits on qlty coverage parser

qlty-check/Cargo.toml, qlty-check/src/executor.rs, qlty-check/src/llm/fixer.rs
Also fix mutex unwrap() in executor.
Addresses #1519
=> Use a ThreadPool to clean up API throttling in Fixer

qlty-plugins/plugins/linters/stylelint/fixtures/__snapshots__/basic_v16.15.0.shot, qlty-plugins/plugins/linters/stylelint/plugin.toml
Credit goes to fonji
https://discord.com/channels/1256822430505373696/1349319727406649374/1349706080954875926
=> Add stylelint 16 support

Cargo.lock, qlty-check/src/executor.rs, qlty-check/src/llm/fixer.rs, qlty-config/Cargo.toml, qlty-config/src/config/issue_transformer.rs
* Updates IssueTransformer to support batched transform
* Batch up to 15 issues per file (per tool) at a time
=> Use /fixes/batch API to batch AI fixes

qlty-config/src/config/plugin.rs
Right now we panic on invalid extra package format, this PR improves the error message.
=> Improve error handling for reading extra package

qlty-config/src/config/ignore.rs, qlty-config/src/config/overrides.rs
Aligns the supported behavior for `[[override]]` with `[[ignore]]`
=> Support tool:ruleKey matching in [[override]] blocks

qlty-check/src/parser/radarlint.rs
=> Change radarlint rulekey separator

qlty-check/src/tool/ruby/gemfile.rs
Fixes a small regression from #1583 on Windows machines.
=> ruby: ignore loading of qlty_load_path script on Windows

Cargo.lock, Cargo.toml
Fixes https://github.com/advisories/GHSA-94vh-gphv-8pm8
=> Upgrade zip

Cargo.lock, Cargo.toml, qlty-check/src/planner/level_filter.rs
More depenedncy updates in preparation for pentest
=> Run `cargo update`

qlty-cli/src/initializer/initializer.rs, qlty-cli/src/initializer/renderer.rs, qlty-cli/src/initializer/scanner.rs, qlty-cli/src/initializer/scanner/gemfile.rs, qlty-cli/src/initializer/scanner/package_file.rs, qlty-cli/src/initializer/scanner/package_json.rs, qlty-cli/tests/cmd/init/config_based_multiple_versions.stdout, qlty-cli/tests/cmd/init/config_based_version_new.stdout, qlty-cli/tests/cmd/init/config_based_version_old.stdout, qlty-cli/tests/cmd/init/custom_source.stdout, qlty-cli/tests/cmd/init/plugins/linters/multi-driver/plugin.toml, qlty-cli/tests/cmd/init/plugins/linters/single-driver/plugin.toml, qlty-config/src/config/plugin.rs
https://github.com/qltysh/cloud/issues/5775
=> Add suggestion mode to plugin definition

qlty-plugins/plugins/tests/runLinterTest.ts
Skip dockerfmt tests on windows as it does not support windows
=> Skip dockerfmt tests on windows

Cargo.lock, qlty-cli/tests/cmd/config/migrate/exclude_patterns.in/.codeclimate.yml, qlty-cli/tests/cmd/config/migrate/exclude_patterns.in/.qlty/qlty.toml, qlty-cli/tests/cmd/config/migrate/exclude_patterns.stdout, qlty-cli/tests/cmd/config/migrate/exclude_patterns.toml, qlty-config/src/migration.rs, qlty-config/src/migration/checks.rs, qlty-config/src/migration/classic.rs
https://github.com/qltysh/cloud/issues/5705
=> Add support for exclude_patterns to qlty config migrate

qlty-cli/src/commands/coverage/publish.rs, qlty-cli/src/lib.rs, qlty-cli/tests/cmd/check/prepare_script_fail.stderr, qlty-cli/tests/cmd/check/using_deprecated_default_source.stderr, qlty-cli/tests/cmd/config/migrate/missing_codeclimate_yml.stderr, qlty-cli/tests/cmd/config/migrate/missing_qlty_toml.stderr, qlty-cli/tests/cmd/config/migrate/no_match.stderr
=> Add validation of coverage upload plan and fatal errors

qlty-cli/src/commands/coverage/publish.rs, qlty-cli/tests/cmd/coverage/json.stderr, qlty-cli/tests/cmd/coverage/json.stdout, qlty-cli/tests/cmd/coverage/json.toml, qlty-cli/tests/cmd/coverage/overrides.stderr
https://github.com/qltysh/cloud/issues/5932
=> Update coverage publish args

qlty-plugins/src/lib.rs
https://github.com/qltysh/cloud/issues/6019
=> Fix: Include plugin configs into built-in compiled source

qlty-config/src/toml_merge.rs
https://github.com/qltysh/cloud/issues/6026
=> Fix toml merging for array of tables

qlty-cli/src/commands/plugins/enable.rs
Right now if .qlty/configs directory is not present and a plugin is enabled that has a config it errors out. This fixes it by ensuring the .qlty/configs directory.
=> Fix configs directory path creation during plugins enable

qlty-check/src/tool.rs
This affects golangci-lint: env vars from go runtime are not being imported because the golangci-lint plugin is a GithubReleaseTool and not a GoPackageTool.
=> tool: default extra_env_vars() impl should look at runtime().extra_env_vars() if available

qlty-cli/src/telemetry.rs
=> feat: Eliminate panic from telemetry

qlty-coverage/src/ci.rs, qlty-coverage/src/ci/travisci.rs
We had an empty file here instead of an implementation. I added the implementation instead of removing it since it was relatively easy.
closes #2109
=> feat: Implement support for auto-detection of coverage variables for Travis CI users

qlty-coverage/src/parser/simplecov.rs
https://github.com/qltysh/support/issues/98
=> fix: add more support for simplecov parser

qlty-check/src/executor/driver.rs, qlty-check/src/parser.rs, qlty-check/src/parser/haml_lint.rs, qlty-config/default.toml, qlty-config/src/config/plugin.rs, qlty-plugins/plugins/linters/haml-lint/fixtures/__snapshots__/basic_v0.62.0.shot, qlty-plugins/plugins/linters/haml-lint/fixtures/__snapshots__/empty_v0.62.0.shot, qlty-plugins/plugins/linters/haml-lint/fixtures/basic.in.haml, qlty-plugins/plugins/linters/haml-lint/haml-lint.test.ts, qlty-plugins/plugins/linters/haml-lint/plugin.toml
https://github.com/qltysh/qlty/issues/2113
=> feat: add haml lint plugin

qlty-cli/src/export/analysis.rs
https://github.com/qltysh/qlty/issues/2156
=> feat: Batch build messages and stats into smaller files

qlty-coverage/src/publish/planner.rs
https://github.com/qltysh/qlty/issues/2166
=> feat: make strip prefix coverage transformer optional

qlty-coverage/src/parser/coverprofile.rs
https://github.com/qltysh/qlty/issues/2224
=> fix: coverprofile parser

.github/workflows/build.yml, .github/workflows/changelog.yml, .github/workflows/claude.yml, .github/workflows/cli.yml, .github/workflows/cli_integration.yml, .github/workflows/docker.yml, .github/workflows/fmt.yml, .github/workflows/installer_test.yml, .github/workflows/metadata.yml, .github/workflows/plugins.yml, .github/workflows/prepare_release.yml, .github/workflows/release.yml, .github/workflows/release_installer.yml, .github/workflows/release_promote.yml, .github/workflows/update_linter_versions.yml
(Excludes other CI security changes)
=> chore: pin GHA actions

qlty-plugins/plugins/linters/zizmor/fixtures/__snapshots__/basic_v1.11.0.shot, qlty-plugins/plugins/linters/zizmor/fixtures/basic.in/.github/workflows/bad.yaml, qlty-plugins/plugins/linters/zizmor/plugin.toml, qlty-plugins/plugins/linters/zizmor/zizmor.test.ts
https://github.com/qltysh/qlty/issues/2264
=> feat: add zizmor plugin

qlty-cli/src/commands/coverage/publish.rs, qlty-cli/tests/cmd/coverage/basic.toml, qlty-cli/tests/cmd/coverage/ignore_patterns.toml, qlty-cli/tests/cmd/coverage/json.stdout, qlty-cli/tests/cmd/coverage/json.toml, qlty-cli/tests/cmd/coverage/override_commit_time.toml, qlty-cli/tests/cmd/coverage/override_git_tag.toml, qlty-cli/tests/cmd/coverage/overrides.stdout, qlty-cli/tests/cmd/coverage/overrides.toml, qlty-cli/tests/cmd/coverage/publish_validate.toml, qlty-cli/tests/cmd/without_git/basic_coverage.toml
Reverts qltysh/qlty#2220
Going to release this more slowly with a no-op silent version first.
=> chore: Revert "feat: enable validation by default for qlty coverage publish"

qlty-coverage/src/ci/github.rs
Closes #2292 .
See issue for full context. TLDR: migrates the responsibility of detecting the head sha of the PR from the GitHub Action (or other outside script) into the CLI proper.
=> feat: Read GitHub SHA for PRs from EVENT PATH instead of requiring an override

.claude/commands/changelog.md, .github/workflows/prepare_release.yml, .qlty/qlty.toml
- I found the text describing how to specify a version confusing
- Added a custom claude command /changelog
=> chore: small workflow updates

qlty-check/src/executor.rs, qlty-check/src/parser/clippy.rs, qlty-check/src/planner/config_files.rs, qlty-cli/src/initializer/scanner.rs, qlty-cli/tests/cmd/check/copy_config_to_tool_install_with_exported_config.in/.gitignore, qlty-cli/tests/cmd/check/copy_config_to_tool_install_with_exported_config.in/.qlty/qlty.toml, qlty-cli/tests/cmd/check/copy_config_to_tool_install_with_exported_config.in/custom_source/source.toml, qlty-cli/tests/cmd/check/copy_config_to_tool_install_with_exported_config.stderr, qlty-cli/tests/cmd/check/copy_config_to_tool_install_with_exported_config.stdout, qlty-cli/tests/cmd/check/copy_config_to_tool_install_with_exported_config.toml
Right now configs files exported from sources using export_config_files directive do not behave correctly with copy_configs_into_tool_install directive used for certain plugins such as eslint 9, this PR fixes that by adding the path of the config to be exported to the config files list during planning phase (important for it to be inserted into the invocations details and to be used in `--config` flag correctly) and copying them into the root from sources first before anything else, such as copying them into tool install directory.
=> fix: interaction of exported_config_paths and copy_configs_into_tool_install directives

qlty-coverage/src/ci/buildkite.rs
Most crucially, we were missing the pull number.
=> feat: Ensure read important env vars for BuildKite for coverage publishing
